### ISSUE TITLE
Caliban client interface generation problem

### ISSUE THREAD

**Issue by Przemyslaw5** [ghostdogpr/caliban#1021]
Hi, I have a problem with interfaces. In the schema I have an interface defined, but after generating file by caliban cleint, the file does not contain this interface but uses it. Program compiles with error `not found: type xxx` where `xxx` is name of interface from schema

I minimized the problem: 

You can use this schema: 
```
type typeFirst {
    val: Int!
}

interface interfaceBug {
    key: [typeFirst!]!
}

type typeSecond {
    key: interfaceBug!
}

type Query {
    queryFirst: typeSecond!
}
```

Now using caliban client to generate file we get mentioned error during compilation.

**Comment by paulpdaniels** [comment]
That seems like it shouldn't even be a valid schema no? Nothing is implementing the interface.

**Comment by Przemyslaw5** [comment]
Okay, sorry i have a bug in generator.

**Comment by paulpdaniels** [comment]
Feel free to reopen if this turns out to be an issue with caliban
