### ISSUE TITLE
type with `then` field cause `deprecated` warning in `caliban-sbt`

### ISSUE THREAD

**Issue by ngbinh** [ghostdogpr/caliban#1031]
Using `caliban-sbt` on a schema with type like this:

```
type Order {
 then: String
}
```

would cause `then is a reserved word (since 2.10.0); usage as an identifier is deprecated` on the generated code.

is there a way to fix this?

Thanks

**Comment by ghostdogpr** [comment]
I think it might be enough just to add it to `reservedKeywords` here https://github.com/ghostdogpr/caliban/blob/8c52365cc73a8b064d3251fa5c77c79bb0c741a0/tools/src/main/scala/caliban/tools/ClientWriter.scala#L836

I don't remember where I found the initial list of keywords but `then` was not in there.

**Comment by RhnSharma** [comment]
I would like to take this one. Is it up for grabs?

**Comment by ghostdogpr** [comment]
Sure!

**Comment by ngbinh** [comment]
would be great if the list is configurable with sensible defaults.

**Comment by ghostdogpr** [comment]
In theory it's a finite list, but I can't find it. Even on the 2.13 language spec `then` is not included:
<img width="449" alt="Screen Shot 2021-09-06 at 11 15 07 PM" src="https://user-images.githubusercontent.com/7413894/132230542-9ff41269-c334-4806-b9f4-86b125d6f9f6.png">

**Comment by ngbinh** [comment]
`then` is reserved in `dotty`. More context here: https://github.com/scala/bug/issues/10309

**Comment by ghostdogpr** [comment]
Oh, interesting, the error message is actually incorrect.
