### ISSUE TITLE
Migrate to ZIO 2.0

### ISSUE THREAD

**Issue by paulpdaniels** [ghostdogpr/caliban#1041]
We should start adding a 2.0 branch once the ZIO 2.0 API stabilizes a bit more (and there is some more support across other libraries).

TODO:
- [x] zio-query
- [x] zio-config
- [x] zio-json
- [x] zio-http
- [x] sttp (async-http-client-backend-zio)
- [x] tapir
- [x] zio-interop-cats
- [x] zio-interop-reactivestreams

**Comment by ghostdogpr** [comment]
Added zio-interop-cats and zio-interop-reactivestreams

**Comment by ghostdogpr** [comment]
Note that for core, only `zio-query` is needed. All the rest is for interop (except zio-config, used for the tools).

**Comment by adamgfraser** [comment]
Will take care of `zio-query`.

**Comment by adamgfraser** [comment]
Created a ZIO 2.0 branch [here](https://github.com/zio/zio-query/tree/zio2). Can do a release whenever you want it.

**Comment by adamgfraser** [comment]
Snapshot version available [here](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-query_2.13/0.2.10+16-e3977c91-SNAPSHOT/).

**Comment by adamgfraser** [comment]
I am working on `zio-interop-cats`.

**Comment by adamgfraser** [comment]
Published snapshots for `zio-interop-cats` with support for interop between ZIO 2 and Cats Effect 2 [here](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-interop-cats_2.13/2.5.1.0+7-df3c69d3-SNAPSHOT) and interop between ZIO 2 and Cats Effect 3 [here](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-interop-cats_2.13/3.1.1.0+27-67652048-SNAPSHOT.)

**Comment by ngbinh** [comment]
This is the main hold back for us to move to zio from monix. Can't wait for it to happen

**Comment by ghostdogpr** [comment]
> This is the main hold back for us to move to zio from monix. Can't wait for it to happen

Really? Most libraries in the ecosystem are not compatible with ZIO 2.0 yet 🤔
ZIO 2.0 is still under heavy changes, I wouldn't consider it production-ready. Why not use ZIO 1.0?

**Comment by ngbinh** [comment]
> Really? Most libraries in the ecosystem are not compatible with ZIO 2.0 yet 🤔
ZIO 2.0 is still under heavy changes, I wouldn't consider it production-ready. Why not use ZIO 1.0?

Migrating the main effect type on a very large codebase is such a big task that we do not want to migrate to 1.0 and then immediately to 2.X right after. We also have some much smaller, independent projects using ZIO 2.X pre-release so we are OK with living on the edge for a short while.

**Comment by paulpdaniels** [comment]
I think zio-interop-reactivestreams also has a 2.x preview build available.

**Comment by ghostdogpr** [comment]
@adamgfraser first draft (I only migrated core and client, the rest needs dependencies), if you are curious. It was pretty straightforward, the only annoying part is `when`/`whenCase` not returning `Unit` anymore, which created a lot of compile errors and required adding a bunch of `.unit`.

**Comment by ghostdogpr** [comment]
Closing this as I had the first RC release for ZIO 2.0 yesterday
