### ISSUE TITLE
GQLInterface annotation ignored when no queries return the interface directly

### ISSUE THREAD

**Issue by kormbrek-rally** [ghostdogpr/caliban#1104]
Given some interface `Result` with `@GQLInterface` that is a sealed trait and some implementations of `Result`, if all queries only return implementations of `Result`, none of the return types will be defined in terms of `Result` and `Result` will not even be defined in the schema. 

[This gist](https://gist.github.com/kormbrek-rally/d1845edc6817bad10c8c09be655692d6) can be plopped right into /examples/src/main/scala/example/play.
As is, ResultTwo is defined like:
![image](https://user-images.githubusercontent.com/21181544/137979345-b5312e3a-c319-45de-8cd1-5f50135ebe4d.png)

If you comment out [the dummy line](https://gist.github.com/kormbrek-rally/d1845edc6817bad10c8c09be655692d6#file-reproapp-scala-L75) and run the server again, ResultTwo is defined like:
![image](https://user-images.githubusercontent.com/21181544/137979538-c2030d95-3135-4ee9-9de7-d6a4a13ef287.png)

**Comment by ghostdogpr** [comment]
Yeah, that is way interfaces are currently implemented in Caliban. This is because the typeclass derivation engine (magnolia with Scala 2, native Scala in Scala 3) doesn't give the list of sealed traits that a class extends, it only gives us the list of case classes implemented a sealed traits. So we are able to find the implementing classes from the sealed trait and not the opposite. 

But I wonder why you would need something like that. If you don't return the interface in any field, the interface is actually useless: you can't use it anywhere. It just has informative value. There are some workarounds to the issue but I don't really understand in which case you would even need it.

**Comment by kormbrek-rally** [comment]
Perhaps there isn't a good use case for it. I imagine a generated client might want to have a collection like `List[ResultInterface]` of the various types and the interface would allow that. But if the types are disparate, a typed collection is no longer possible.
My concern was that if you have something returning just the interface and later want to expand it to include more than what the interface has, now caliban is completely changing how the types are defined. So expanding a type would become backwards incompatible, which is not expected.

**Comment by frekw** [comment]
> But I wonder why you would need something like that. If you don't return the interface in any field, the interface is actually useless: you can't use it anywhere. It just has informative value. There are some workarounds to the issue but I don't really understand in which case you would even need it.

I think it can be quite important to efficiently re-use fragments in queries.

Consider the following schema:

```graphql
interface Listable {
  title: String!
}

type A implements Listable {
  title: String!
  color: String!
}

type B implements Listable {
  title: String!
  age: Int
}

union SearchResult = A | B

type Query {
  search(query: String!, first: Int!): SearchResult
}
```

then the following should be a valid query (this is actually a subtle consequence of field selection merging):

```graphql
{
  search(query: "foo", first: 10) {
    ...on Listable { title }
  }
}
```

In this example it may not make a lot of sense, but in larger code bases it can drastically cut down on the number of fragments / queries you need to write.

**Comment by frekw** [comment]
I wonder if we could use withAdditionalTypes as a workaround?

**Comment by ghostdogpr** [comment]
> I wonder if we could use withAdditionalTypes as a workaround?

I think it might work, yeah.

**Comment by Mxrynd** [comment]
btw expicitly generating schema of interface, calling it't toType and passing it to withAdditionalTypes  does not work for me

**Comment by ghostdogpr** [comment]
@Mxrynd this seems to work? https://scastie.scala-lang.org/5yPGSTIqTLaqrdSqXVnXJw

**Comment by ghostdogpr** [comment]
@Mxrynd there was a fix in https://github.com/ghostdogpr/caliban/pull/1170, hopefully it covers your case. I will add this to the FAQ.

**Comment by ghostdogpr** [comment]
Found a bug with `withAdditionalTypes` and fixed it: https://github.com/ghostdogpr/caliban/pull/1175
