### ISSUE TITLE
Using custom errors that do not extend throwable break schema derivation

### ISSUE THREAD

**Issue by kormbrek-rally** [ghostdogpr/caliban#1105]
[This gist](https://gist.github.com/kormbrek-rally/d1845edc6817bad10c8c09be655692d6) can be plopped right into /examples/src/main/scala/example/play.

If one changes [ServiceError](https://gist.github.com/kormbrek-rally/d1845edc6817bad10c8c09be655692d6#file-reproapp-scala-L53) to `extend throwable`, [the implicits](https://gist.github.com/kormbrek-rally/d1845edc6817bad10c8c09be655692d6#file-reproapp-scala-L79-L80) for schema generation are no longer needed and can be commented out.

It appears that by not extending throwable, the schema derivation is broken and now implicit Schema values are needed.

**Comment by ghostdogpr** [comment]
I think it's just caused by the fact you declared the implicit *after* you call `graphQL(...)`.
I copied your code and moved `customEffectSchema` before `val api: GraphQL[Has[ReproService]] = graphQL(`, then I can delete the 2 calls to `Schema.gen` and it compiles well.
