### ISSUE TITLE
Add Scala 3 keywords to the list of reserved keywords

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#1130]
In ClientWriter.scala 

See the list here: https://dotty.epfl.ch/docs/internals/syntax.html#regular-keywords

**Comment by jgoday** [comment]
Hi @ghostdogpr, I started to take a look at caliban, playing with both server and generating client code.
I have made a PR for this issue: #1145.

**Comment by ghostdogpr** [comment]
Closed by https://github.com/ghostdogpr/caliban/pull/1145
