### ISSUE TITLE
using java.time classes may cause runtime errors

### ISSUE THREAD

**Issue by aappddeevv** [ghostdogpr/caliban#1131]
When running scala 3.1 and using java.time.ZonedDateTime (or Instant) values in a case class causes the runtime to fail with:

```sh
cannot access class jdk.intenal.ValueBased (in module java.base) because module java.base does not export jdk.internal to unnamed module...
```

Using:

```sh
case class Entity(atime: ZonedDateTime)
```
causes the runtime error but using `Option[ZonedDateTime]` does not causes an error.

**Comment by ghostdogpr** [comment]
@aappddeevv I just gave it a try and it is working well: https://scastie.scala-lang.org/K4AFHpHCRPmLO0qSUXKM1w

I'll do a reproducer for you in order to dig into this.

**Comment by aappddeevv** [comment]
I'll try to do more testing. Perhaps it has to do with the latest graal. I'll try the standard java as well.

**Comment by ghostdogpr** [comment]
Closing this one for now, but feel free to reopen if you find how to reproduce.
