### ISSUE TITLE
Codegen: allow excluding files from generation

### ISSUE THREAD

**Issue by kubukoz** [ghostdogpr/caliban#1157]
This would be useful if you have one directory with all the schemas, but want to direct them to the `target` directory of multiple modules and/or configurations (main, test).

**Comment by ghostdogpr** [comment]
Do we still need this or is the workaround okay?

**Comment by kubukoz** [comment]
I think the workaround is sufficient.

For the reader: this means overriding with `caliban / sources := List(...files)`
