### ISSUE TITLE
Implement additions from 2021 spec update 

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#1159]
New spec: https://spec.graphql.org/October2021/
Changelog and diff: https://github.com/graphql/graphql-spec/blob/main/changelogs/October2021.md
- [x] Custom Scalar Specification URLs
- [x] Allow interfaces to implement other interfaces
- [x] Repeatable directives
- [x] Allow directives on variable definitions
- [x] `__typename` is not valid at subscription root
- [ ] Schema descriptions

**Comment by ghostdogpr** [comment]
Working on `Custom Scalar Specification URLs`.

**Comment by nukky94** [comment]
Hi, any updates on the remaining tasks, espacially implemeting `Repeatable directives`?
Thanks

**Comment by ghostdogpr** [comment]
I don't think anyone has been working on it so far. Wanna give it a shot? Or you need it?

**Comment by nukky94** [comment]
Yes, need it, I got a parsing error when trying to build the client for a schema which contains repeatable directives.
