### ISSUE TITLE
Subscription streams never close

### ISSUE THREAD

**Issue by gaspb** [ghostdogpr/caliban#1204]
Hi,

Since 1.3.0, subscriptions cannot be closed (with http4s at least).

Repro :

In the http4s example app, change

```scala
  def deletedEvents: ZStream[ExampleService, Nothing, String] =
    ZStream.accessStream(_.get.deletedEvents)
```

to 

```scala
  def deletedEvents: ZStream[ExampleService, Nothing, String] =
    ZStream.accessStream(_.get.deletedEvents.ensuring(ZIO.debug("> Completed")))
```

In 1.2.4, when the client emits `{"id": x, "type": "stop"}` the log is printed correctly and the server returns `{"id": x, "type": "completed"}`.
In 1.3.0, no event is emitted by the server, no log is printed, and subscription stays opened

**Comment by ghostdogpr** [comment]
@gaspb I believe I fixed it. I also added it to the test suite. Can you check with the latest snapshot if it's okay for you?

**Comment by gaspb** [comment]
yes it's fixed, thanks :pray:
