### ISSUE TITLE
Question about RequestInterceptor

### ISSUE THREAD

**Issue by darl** [ghostdogpr/caliban#1207]
I'm trying to upgrade caliban to 1.3.0. 
Found that ContextWrapper disappeared and RequestInterceptor takes its place.

My use case is to extract context from request and provide it as ZIO environment:
```scala
def contextExtractor(log: Logging.Service): ContextWrapper[World, HttpResponse] =
    new ContextWrapper[World, HttpResponse] {

      override def apply[R1 <: World, A1 >: HttpResponse](ctx: RequestContext)(effect: URIO[R1, A1]): URIO[R1, A1] = {
        for {
          world <- ZIO.service[World.Service]
          ctx = AkkaRequestContextReader.readFrom(ctx.request)
          braveNewWorld <- world.withContext(ctx)
          res <- effect.provideSomeLayer[R1](ZLayer.succeed(braveNewWorld))
        } yield res
      }
    }
```

RequestInterceptor doesn't have access to effect so the only solution I see is to pass information via FiberRef. Downside 

Can we make RequestInterceptor behave like the old ContextWrapper?

**Comment by ghostdogpr** [comment]
Good point! I restored that capability in https://github.com/ghostdogpr/caliban/pull/1208
