### ISSUE TITLE
Fields from other type in union appearing in output as null

### ISSUE THREAD

**Issue by guymers** [ghostdogpr/caliban#1211]
Given the following schema:

```graphql
schema {
  query: Test
}

union Base = BaseOne | BaseTwoOne

type BaseOne {
  id: String!
  name: String!
  inner: [BaseOneInner!]!
}

type BaseOneInner {
  a: String!
}

type BaseTwoInner {
  b: Int!
}

type BaseTwoOne {
  id: String!
  name: String!
  inner: [BaseTwoInner!]!
}

type Test {
  bases: [Base!]!
}
```

Running the following query:
```graphql
query {
  bases {
    ... on BaseOne {
      id
      name
      inner { a }
    }
    ... on BaseTwoOne {
      id
      name
      inner { b }
    }
  }
}
```

Produces the following output since 1.3.1
```json
{
  "bases": [
    {
      "id": "1",
      "name": "base 1",
      "inner": [
        {
          "a": "a",
          "b": null
        }
      ]
    },
    {
      "id": "2",
      "name": "base 2",
      "inner": [
        {
          "a": null,
          "b": 2
        }
      ]
    }
  ]
}
```

Note the `"b": null` in item 0 and `"a": null` in item 1.

Basic test case: https://gist.github.com/guymers/bce14ace58e2c6c57f594f7be1981536

**Comment by ghostdogpr** [comment]
Ah, I see what's going on. When merging fields, if there are 2 conditional fields with the same name, I should bubble the condition to the children. Thanks for the report. 

I'm traveling today so I should be able to get it fixed tomorrow.

**Comment by ghostdogpr** [comment]
@guymers I just merged the fix. A snapshot will be generated within 10 minutes. Can you check if this works well for you?

**Comment by guymers** [comment]
Can confirm that the fix solves the issue.
