### ISSUE TITLE
ZHttpAdapter adapter does not allow compilation and does run with recent versions of ZHttp

### ISSUE THREAD

**Issue by pmeheut** [ghostdogpr/caliban#1238]
In ZHttpAdapter.scala, definition of makeWebSocketService is:

```
 def makeWebSocketService[R <: Has[_], E]
```

The `Has[_]` prevents compilation in Scala 3 when passing a simple interpreter with no trait, no `Has`.

As far as I know, this is useless and not in the other http adapters.

BTW, the code runs compiles with ZHttp 1.0.0.0-RC21 but fails at runtime. Line 43, ` HttpApp.responseM` should be replaced by `Http.fromEffect` as the `HttpApp` object does not exist anymore in recent versions of ZHttp.

**Comment by ghostdogpr** [comment]
The `Has[_]` constraint is indeed no longer necessary, I just opened https://github.com/ghostdogpr/caliban/pull/1241 to remove it.

ZIO Http still being in RC, the API is not stable and versions are not binary compatible. It means you have to use the same version that caliban is using (1.0.0.0-RC17). RC18 and RC19 had some bugs preventing the upgrade. RC21 should be usable and work is in progress in https://github.com/ghostdogpr/caliban/pull/1216, waiting for a release of Tapir.

**Comment by pmeheut** [comment]
Thanks.
