### ISSUE TITLE
caliban-codegen-sbt generates scala 3, python style code in a 2.13.7 project

### ISSUE THREAD

**Issue by pmeheut** [ghostdogpr/caliban#1242]
Hi,
I have a scala full-stack project but in this case, I'm just using the JVM subprojects.
My build.sbt starts with `ThisBuild / scalaVersion := "2.13.7"` and I have no reference to Scala 3 anywhere. It compiles and run ok and the server works fine with GraphQL.

But as soon as I copy in my build.sbt the code from [https://ghostdogpr.github.io/caliban/docs/client.html#dependencies](https://ghostdogpr.github.io/caliban/docs/client.html#dependencies) to implements a client with code generation from the server side, I got a generated file like this:

```
import caliban.client.FieldBuilder.*
import caliban.client.*

object CalibanClient:

  type LocalDate = String

  type DailyReportError
  object DailyReportError:
```

As far as I know, there is nothing special in the CalibanClientGenerator file. It looks like this:

```
package caliban.generator

import caliban.tools.compiletime.CompileTime
import caliban.tools.compiletime.Config.ClientGenerationSettings
import zio.{ExitCode, URIO}

private[generator] object CalibanClientGenerator_0 extends zio.App {
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    CompileTime.generateClient(args)(
      io.softhedge.webreport.GraphQLDefinitions.api,
      ClientGenerationSettings(
  packageName = "io.softhedge.webreport.client.generated",
  clientName = "CalibanClient",
  scalafmtPath = None,
  genView = false,
  scalarMappings = List.empty,
  imports = List.empty,
  splitFiles = false,
  enableFmt = true,
  extensibleEnums = false
)
    )
}
```

I've tried many things including cleaning my Coursier cache, looking for references to Scala 3 but no luck. Any help?

**Comment by ghostdogpr** [comment]
That's weird, I've never observed that. I guess it comes from ScalaFmt formatting things for Scala 3 (the code caliban generates is not like that). By any chance, do you have a `.scalafmt.conf` file in your project?

**Comment by pmeheut** [comment]
Thanks. You just saved my life or at least hours of frustration.
I had indeed a .scalafmt.conf inherited from another project via my Scala 3 branch.

I would never have guessed that scalafmt was called on the generated source code and especially because I have `ctCalibanClientsVersionedCode := false`.
