### ISSUE TITLE
Parsing Error for missing empty block

### ISSUE THREAD

**Issue by cornerman** [ghostdogpr/caliban#1252]
We are getting a Parsing Error when generating client code for a graphql schema with the sbt plugin.

Our graphql schema contains the following line:
```
input foobar
```

And we get the following error:
```
Parsing Error: Position 5143:1, found ""
caliban.parsing.Parser$.$anonfun$parseQuery$7(Parser.scala:23)
zio.ZIO$.$anonfun$fail$1(ZIO.scala:2898)
zio.internal.FiberContext.evaluateNow(FiberContext.scala:413)
zio.Runtime.unsafeRunWith(Runtime.scala:221)
zio.Runtime.unsafeRunSync(Runtime.scala:84)
zio.Runtime.unsafeRunSync$(Runtime.scala:81)
zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:288)
zio.Runtime.unsafeRun(Runtime.scala:59)
zio.Runtime.unsafeRun$(Runtime.scala:58)
zio.Runtime$$anon$3.unsafeRun(Runtime.scala:288)
caliban.codegen.CalibanSourceGenerator$.generateSources$1(CalibanSourceGenerator.scala:122)
caliban.codegen.CalibanSourceGenerator$.$anonfun$apply$35(CalibanSourceGenerator.scala:131)
caliban.codegen.CalibanSourceGenerator$.$anonfun$apply$35$adapted(CalibanSourceGenerator.scala:130)
sbt.util.Tracked$.$anonfun$outputChangedW$1(Tracked.scala:128)
caliban.codegen.CalibanSourceGenerator$.apply(CalibanSourceGenerator.scala:144)
caliban.codegen.CalibanPlugin$.$anonfun$calibanScopedSettings$3(CalibanPlugin.scala:40)
scala.Function1.$anonfun$compose$1(Function1.scala:49)
sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
sbt.std.Transform$$anon$4.work(Transform.scala:68)
sbt.Execute.$anonfun$submit$2(Execute.scala:282)
sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
sbt.Execute.work(Execute.scala:291)
sbt.Execute.$anonfun$submit$1(Execute.scala:282)
sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
java.base/java.lang.Thread.run(Thread.java:831)
```

We can fix it by rewriting our graphql schema to:
```
input foobar {}
```

This also happens for `enum foobar` without braces.

Our graphql schema was generated from hasura with the following command:
```
npx --package=graphqurl gq http://localhost:8080/v1/graphql --introspect
```

**Comment by ghostdogpr** [comment]
That's not valid graphql, is it?

In the spec:
> An Input Object type must define one or more input fields.

> An Enum type must define one or more unique enum values.

**Comment by ghostdogpr** [comment]
Related code in the parser:
- Scala 2: https://github.com/ghostdogpr/caliban/blob/55dab61af88bbb0682198527e41e9f2a20272e16/core/src/main/scala-2/caliban/parsing/parsers/Parsers.scala#L79 and https://github.com/ghostdogpr/caliban/blob/55dab61af88bbb0682198527e41e9f2a20272e16/core/src/main/scala-2/caliban/parsing/parsers/Parsers.scala#L92
- Scala 3: https://github.com/ghostdogpr/caliban/blob/55dab61af88bbb0682198527e41e9f2a20272e16/core/src/main/scala-3/caliban/parsing/Parser.scala#L361 and https://github.com/ghostdogpr/caliban/blob/55dab61af88bbb0682198527e41e9f2a20272e16/core/src/main/scala-3/caliban/parsing/Parser.scala#L377

**Comment by cornerman** [comment]
Good point, I do not know. But that is what we get from hasura :)

Mind you, there are normally two schema with hasura. One for authorized users and one unauthorized users. As of now, we get multiple empty `inputs` and empty `enums` in the unauthorized case.

I just opened another issue regarding enums here: https://github.com/ghostdogpr/caliban/issues/1253.

**Comment by ghostdogpr** [comment]
According to the spec, `enum foo` and `input foo` should be supported during parsing.
