### ISSUE TITLE
CompileTime Plugin does not support cross-building nor changing scala version

### ISSUE THREAD

**Issue by pmeheut** [ghostdogpr/caliban#1261]
Test case is simple:

1. go to codegen-sbt/src/sbt-test/compiletime-codegen/test-compile
2. launch sbt
3. force Scala to 2.13.7 with `++ 2.13.7!`
4. compile. It works
5. Go back to the normal Scala version with `++ 2.12.14`
6. compile and it does not work because it does not generated the client files

If done the other way around, 2.12.14 works but not 2.13.7.

**Comment by guizmaii** [comment]
Do you `clean` before to regenerate with a new Scala version?

**Comment by pmeheut** [comment]
If I clean it works but I should have to do it because cross-building does not clean of course.
pure-set code generators are called when we change the scala version or when cross-building against multiple versions but not with sbt-codegen.
I had a quick look at the source code and my first guess would be this is because it caches the generated files but I'm not sure.

**Comment by guizmaii** [comment]
Does this PR https://github.com/ghostdogpr/caliban/pull/1264 fix your problem?

**Comment by pmeheut** [comment]
Hi
Unfortunately, it does not work because scalaVersion is always set to the version used to compile codegenSbt, i.e. 2.12.14.

So when we run `compile` in `codegen-sbt/src/sbt-test/compiletime-codegen/test-compile`, we still return the cached version.
We would want to depend on the current build `scalaVersion`.

**Comment by guizmaii** [comment]
@pmeheut I think I understood my mistake. I was not caching the correct version of Scala. I was caching the version used by sbt instead of caching the version used in your project.

I updated my PR to fix that. See https://github.com/ghostdogpr/caliban/pull/1264
If you have some time to give it a try that'd be nice 🙂

**Comment by pmeheut** [comment]
@[guizmaii](https://github.com/guizmaii): I finally found some time. Still some problems but I hope to fix them and if so, I will create a PR.

**Comment by pmeheut** [comment]
Fixed by #1415 #1426
