### ISSUE TITLE
Confusing behavior in the client when the server returns an error

### ISSUE THREAD

**Issue by javimartinez** [ghostdogpr/caliban#1265]
Attending Caliban's client code, when you make a query,  the result body type is: 

```scala
Either[CalibanClientError, T]
```

where the `CalibanClientError` is an ADT with the members: `CommunicationError`, `DecodingError`, `ServerError`

if the server returns a response like: 

```json
{
  "data": {
    "character": null
  },
  "errors": [
    {
      "message": "Effect failure",
      "locations": [
        {
          "line": 6,
          "column": 3
        }
      ],
      "path": [
        "character"
      ]
    }
  ]
}
``` 

I would expect as a response something like `Left(ServerError(.....))`. However, I'm getting `Right(None..)`

Is it the expected behavior? 

### How to reproduce? 

I've modified Caliban's examples for showing this behavior.  [Here](https://github.com/javimartinez/caliban/commit/3f9259c08de8a26d970a1a5875b088ad931039ed) 

Steps to reproduce: 
 1. Run one of the servers in the examples (I've tested with Http4s)
 2. Run the client example.  The result `None` will be displayed in the terminal, where an error would be expected

Researching out this behavior, I think the problem could be in https://github.com/ghostdogpr/caliban/blob/master/client/src/main/scala/caliban/client/SelectionBuilder.scala#L61 as the `parsed.data` could be an object with its field as a null.

**Comment by ghostdogpr** [comment]
It is intended. Please refer to http://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability

Basically, your `character` is nullable, so the error is absorbed and the field returns null. If that field was non-nullable, the query would fail and you would get an error on the client side. If the server is caliban and you don't want the field to be nullable, check https://ghostdogpr.github.io/caliban/faq/#the-auto-generated-schema-shows-a-field-is-nullable-but-i-want-it-non-nullable-instead

**Comment by javimartinez** [comment]
Understood. Thanks for your time!
