### ISSUE TITLE
Schema.gen causes infinite loop under certain circumstances

### ISSUE THREAD

**Issue by stivens** [ghostdogpr/caliban#1267]
Hi!

So let's consider example below:

```scala
  case class Foo(id: Int, bars: ZQuery[Any, Nothing, List[Bar]])
  case class Bar(id: Int, foos: ZQuery[Any, Nothing, List[Foo]])

  case class Query(test: Int => UIO[Foo])
  private val resolver = RootResolver(
    Query(id =>
      ZIO.succeed(
        Foo(
          id,
          bars = ZQuery.succeed(List.empty[Bar]))
      )
    ),
  )
```

```scala 
 lazy implicit val fooSchema: Schema[Any, Foo] = Schema.gen
 lazy implicit val barSchema: Schema[Any, Bar] = Schema.gen
 // ^ causes loop in runtime
```
```scala
  lazy implicit val fooSchema = Schema.gen[Any, Foo]
  lazy implicit val barSchema = Schema.gen[Any, Bar]
  // ^ works fine
```
(Scala 2.13.7, Caliban 1.3.2)

---------------

https://gist.github.com/stivens/f8e88544cd3e9301b487bc14a885a693

**Comment by ghostdogpr** [comment]
Yeah, derivation of recursive class is a known issue with magnolia. I opened https://github.com/softwaremill/magnolia/issues/190 back in the day but without much results. See also https://github.com/ghostdogpr/caliban/issues/858

I found that sometimes when 2 types depend on each other, making one of them lazy only worked. In case it really doesn't work, the proposed alternative is https://ghostdogpr.github.io/caliban/docs/schema.html#building-schemas-by-hand (which you can do only for a type or 2, and keep auto-derivation for the rest).

**Comment by stivens** [comment]
Ohh, ok. Thank you :)
