### ISSUE TITLE
Serialize Long as String 

### ISSUE THREAD

**Issue by devmentality0** [ghostdogpr/caliban#1306]
Hi!
Thanks for such a great graphQL framework!
I'm trying to handle Long values as strings for easier use in JS client: pass strings as input for mutation and get string back.

Following the documentaion https://ghostdogpr.github.io/caliban/docs/schema.html#custom-types I've written such a code.
```
implicit val longSchema: Schema[Any, Long] = Schema.scalarSchema[Long]("Long", None, None, l => caliban.Value.StringValue(l.toString))

implicit val longArgBuilder: ArgBuilder[Long] = {
  case Value.StringValue(value) =>
    Try(value.toLong)
      .fold(ex => Left(ExecutionError(s"Can't parse $value into a Long", innerThrowable = Some(ex))), Right(_))
  case other => Left(ExecutionError(s"Can't build a Long from input $other"))
}
```

And this way I can send string values as input for mutations. But, unfortunately, for responses caliban anyway serializes longs as numbers. 
Could you help me with that, please? Is there any way to override this behaviour?

**Comment by ghostdogpr** [comment]
@devmentality0 the following works as intended: https://scastie.scala-lang.org/fxhcoPhXQ7KFylGlkj3whA

I think maybe `longSchema` has a lower priority in scope in your case? Can you try to move it just before you call `graphQL`?

**Comment by devmentality0** [comment]
Thank you! Got the idea how to fix it
I was using GenericSchema like that
```
object schema extends GenericSchema[MyEnv]
import schema._
```

and it was imporing default longSchema

Changed it like that

```
object schema extends GenericSchema[MyEnv]
import schema.{longSchema => _, _}
```
Solved! Thank you!
