### ISSUE TITLE
Scala 3 query parser impl fails on custom directives

### ISSUE THREAD

**Issue by sergeykolbasov** [ghostdogpr/caliban#1312]
Hello there

Whenever I try to parse a schema that contains a custom directive definition, parser would fail:

```scala
import caliban.parsing.Parser
import zio.Runtime

Runtime.default.unsafeRun(caliban.parsing.Parser.parseQuery("directive @test on FIELD_DEFINITION")) 
//Parsing Error: Parsing error at offset 24, expected: InRange(24,|,|) 
```

It works just fine in Scala 2 (codegen in sbt), yet fails in Scala 3. I guess it's due to different parser implementations.

Here is a scastie, one can switch the Scala version to verify:
https://scastie.scala-lang.org/j6L2yuJtQSKF1eo5m5REdQ

**Comment by sergeykolbasov** [comment]
I suspect that in new implementation the order matters, so the parser hits `FIELD` and doesn't backtrack then. See fastparse `Parser.oneOf`:

```scala
/** go through the list of parsers trying each as long as they are epsilon failures (don't
    * advance) see @backtrack if you want to do backtracking.
    *
    * This is the same as parsers.foldLeft(fail)(_.orElse(_))
    *
    * recommended style: oneOf(p1 :: p2 :: p3 :: Nil) rather than oneOf(List(p1, p2, p3))
    *
    * Note: order matters here, since we don't backtrack by default.
    */
  def oneOf[A](parsers: List[Parser[A]]): Parser[A] 
  ```

**Comment by ghostdogpr** [comment]
Yes, you are right. I hmdidnt write the cats-parse one myself so I'm not sure if there's a function that backtracks, but an easy fix would be to change the order. Want to make a PR for it?
