### ISSUE TITLE
Bug: Adding a wrapper to a CE-interop app causes introspection to fail

### ISSUE THREAD

**Issue by kyri-petrou** [ghostdogpr/caliban#1338]
Hi there 👋

We've been implementing an app using Caliban and CE3 and I noticed that adding a wrapper to the GraphQL app causes introspection to stop working without any errors being displayed. We use a setup very similar to the example in `AuthExampleAppF`

Easiest way to reproduce the issue is to add `@@ maxDepth(5)` here: https://github.com/ghostdogpr/caliban/blob/master/examples/src/main/scala/example/http4s/AuthExampleAppF.scala#L81

Is this a known issue? Also, is there a temporary workaround this?

**Comment by paulpdaniels** [comment]
Do you see this happening on _all_ wrappers? I don't have an idea of what could be causing it atm but at least with max depth it could also be related to the depth of the query being too large

**Comment by kyri-petrou** [comment]
You're right, it works with `maxDepth >= 13` but fails with any values lower than that. 

I logged and printed the introspection query which seems to have quite a lot of fields and depth, which is why it was failing both with the `maxDepth` and `maxFields` wrappers that I tried.

```graphql
query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
```

Is there a way to make the wrappers not apply to introspection queries?

**Comment by kyri-petrou** [comment]
As for other wrappers, I admittedly haven't figured out how to use ones yet that require either `Clock` or `Console` when using context via a Kleisli 😅.

**Comment by ghostdogpr** [comment]
> Is there a way to make the wrappers not apply to introspection queries?

There is no way currently. It could potentially be a little dangerous to disable it if you use `maxDepth` to prevent a malicious query, because the attacker could use the introspection query. It's actually common to disable introspection in production (which we have a setting for).

**Comment by kyri-petrou** [comment]
Ah okay I understand. Thank you very much @ghostdogpr !
