### ISSUE TITLE
Runtime exception "cannot access class jdk.internal.ValueBased" on JDK 17

### ISSUE THREAD

**Issue by valzam** [ghostdogpr/caliban#1352]
Hey,

we are using caliban 2.0 with JDK 17 and Scala 3. When I include a `java.time` type with automatic schema derivation everything compiles but throws a runtime error. I was able to reproduce this in Scastie

https://scastie.scala-lang.org/fUOJ5OqzQoqbY1UmkEVysg

**Comment by ghostdogpr** [comment]
I was able to reproduce (only with Scala 3 and JDK 17), but I have no idea why it happens. It looks as if the Scala 3 typeclass derivation wasn't able to handle those types on the JDK 17. I tried making a dummy `Schema` for `Instant` and the same thing happens. The only workaround I see (besides not using JDK 17) is to define your own `Schema` for the class containing the `Instant` (here `Character`) instead of the auto-derivated one.

**Comment by valzam** [comment]
Hey, 

thanks for taking a look, yes creating a custom schema is what we did and it works fine. I still wanted to raise it. I guess we are quite ahead of the curve with Scala 3 and JDK 17 but I feel like this is something other people might run into.

**Comment by ghostdogpr** [comment]
Yeah I suspect a bug in the Scala 3 typeclass derivation with JDK 17. 

If I had enough time I'd try to reproduce with a dummy derivation and submit that to the Dotty GitHub. I don't have much time at the moment so if anyone is motivated you can give it a try. I'm also hoping others might run into the issue and report it 😃

**Comment by hollinwilkins** [comment]
We are getting this issue as well. Tried adding the following compiler/run options and it turns into another error:

```Compile / run / javaOptions ++= Seq(
  "--add-opens=java.base/jdk.internal=ALL-UNNAMED"
)
Compile / javaOptions ++= Seq(
  "--add-opens=java.base/jdk.internal=ALL-UNNAMED"
)
```

Turns into: `java.lang.InstantiationError: jdk.internal.ValueBased` instead of the module export error reported originally.

**Comment by ghostdogpr** [comment]
I investigated a little bit further and found the issue is not with typeclass derivation at all but with the macro to extract annotations. It can be reproduced by just running this:
```scala
package caliban.schema.macros

@main def hello: Unit = {
  println(Macros.annotations[java.time.Instant])
}
```

Here's the macro code:
```scala
inline def annotations[T]: List[Any] = ${ annotationsImpl[T] }

def annotationsImpl[T: Type](using qctx: Quotes): Expr[List[Any]] = {
  import qctx.reflect.*
  val tpe = TypeRepr.of[T]
  Expr.ofList {
    tpe.typeSymbol.annotations.filter { a =>
      a.tpe.typeSymbol.maybeOwner.isNoSymbol || a.tpe.typeSymbol.owner.fullName != "scala.annotation.internal"
    }.map(_.asExpr.asInstanceOf[Expr[Any]])
  }
}
```
If anyone knowing Scala macros is able to help...
