### ISSUE TITLE
Using `RootResolver` with no queries, only mutations

### ISSUE THREAD

**Issue by benrbray** [ghostdogpr/caliban#1369]
I would like to define a GraphQL API with no queries, only mutations.  At the moment, this seems not to be supported:

https://github.com/ghostdogpr/caliban/blob/739789d83c558b82fd686c7376c27122506802c5/core/src/main/scala/caliban/validation/Validator.scala#L1018-L1021

However I can still define a `RootResolver` this way, leading to the above error `caliban.CalibanError$ValidationError: The query root operation is missing.`.

```scala
@Annotations.GQLName("Mutations")
  private case class Mutations[F[_]](
      createSignup: protocol.CreateSignup => F[protocol.Signup]
  )

// ...

  val graphQL: GraphQL[R] =
    GraphQL.of(
      RootResolver[Unit, Mutations[F], Unit](
        Option.empty[Unit],
        Mutations(createFoo = createFoo).some,
        Option.empty[Unit]
      )
    )
```

Is there a reason that mutation-only apis are not supported?  As far as I can tell, mutations and queries are treated identically by `RootSchemaBuilder` etc..  I would propose relaxing this constraint to enforce that *at least one* of `queries` and `mutations` is defined.

**Comment by ghostdogpr** [comment]
It's the graphql spec that requires that: http://spec.graphql.org/June2018/#sec-Root-Operation-Types

**Comment by benrbray** [comment]
Thank you for the lightning-fast reply!

The reason we're doing this is that we are composing a bunch of these smaller GraphQL APIs into a larger global one.  The local ones may or may not have queries, but the global one definitely does.  We also tried the following, with an empty case class for `Queries`:

```scala
@Annotations.GQLName("Queries")
private case class Queries[F[_]]()

@Annotations.GQLName("Mutations")
private case class Mutations[F[_]](
    createSignup: protocol.CreateSignup => F[protocol.Signup]
)
```
```
val graphQL: GraphQL[R] =
  GraphQL.of(
    RootResolver(
      Queries(),
      Mutations(createSignup = createSignup)
    )
  )
```

The generated schema is below.  I don't think this is a valid GraphQL schema, so we get an error `caliban.CalibanError$ValidationError: Object 'Queries' does not have fields` when trying to execute a query against this schema.

```graphql
schema {
  query: Queries
  mutation: Mutations
}

type Queries

type Mutations {
  createSignup(emailAddress: String!): Signup!
}

type Signup {
  id: String!
}
```

So, the solution seems to be to add a dummy query -- which is definitely not ideal.

```scala
@Annotations.GQLName("Queries")
private case class Queries[F[_]](dummy: F[Unit])

@Annotations.GQLName("Mutations")
private case class Mutations[F[_]](
    createSignup: protocol.CreateSignup => F[protocol.Signup]
)
```
```scala
val graphQL: GraphQL[R] =
  GraphQL.of(
    RootResolver(
      Queries(dummy=/*...*/),
      Mutations(createSignup = createSignup)
    )
  )
```

Would you be able to offer any suggestions?  Should we be composing APIs differently?

**Comment by benrbray** [comment]
Since omitting the queries object is against the spec, would you be in favor of changing `RootResolver.queryResolver` to be:

```scala
case class RootResolver[+Query, +Mutation, +Subscription](
  queryResolver: Query,
  mutationResolver: Option[Mutation],
  subscriptionResolver: Option[Subscription]
)
```

Instead of:

https://github.com/ghostdogpr/caliban/blob/097cba660bdaa090535b6a49e12b6f73e95b7d83/core/src/main/scala/caliban/RootResolver.scala#L8-L12

Alternatively, making the case class `private` should offer the same protection.  I also wonder if there's a way to have compile-time checks against empty case classes.

**Comment by benrbray** [comment]
Looking more closely, here is how GraphQL objects are currently validated by `caliban`:

https://github.com/ghostdogpr/caliban/blob/739789d83c558b82fd686c7376c27122506802c5/core/src/main/scala/caliban/validation/Validator.scala#L905-L911

However, according to the [GraphQL spec](https://spec.graphql.org/June2018/#ObjectTypeDefinition), the fields declaration for an object is optional:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/221963/170418872-31500fcf-7b03-4d5c-ba9f-f8dd38e72fb6.png">

So, it looks like `caliban` should allow empty objects, as in:

```graphql
type Queries
```

**Comment by ghostdogpr** [comment]
You're composing these smaller APIs outside of Caliban?

Caliban allows you defining no queries in the case you compose them using Caliban itself. For example:
```scala
val queries   = ??? // only define queries
val mutations = ??? // only define queries

val api = queries |+| mutations
```

That is why we allow the construction of it without queries, but when we build the interpreter we assume the schema must be valid and we check then.

**Comment by ghostdogpr** [comment]
> An Object type must define one or more fields

See https://spec.graphql.org/June2018/#sec-Objects, there is a validation rule for that:

> Type Validation
>
> Object types have the potential to be invalid if incorrectly defined. This set of rules must be adhered to by every Object type in a GraphQL schema.
>
> An Object type must define one or more fields.

**Comment by benrbray** [comment]
Actually, now that you mention it, the errors come from our unit tests -- we are testing each of the local APIs individually without composing.

But, that does suggest a temporary workaround -- we only need dummy queries for our test suites.

**Comment by ghostdogpr** [comment]
Yeah you could do `val api = dummy |+| mutations` and run tests on that.
