### ISSUE TITLE
It seems that some data types in Cats(OptionT, fs2.Stream) is not support?

### ISSUE THREAD

**Issue by UkonnRa** [ghostdogpr/caliban#138]
Say having such the Queries:

```scala
final case class Queries[F[_]: Effect]( // Or any other traits?
    users: F[List[User]],
    userById: UserId => F[Option[User]],
    userByEmail: Email => F[Option[User]]
)

final case class PrettierQueries[F[_]: Effect]( // Or any other traits?
    users: fs2.Stream[F, User],
    userById: UserId => OptionT[F, User],
    userByEmail: Email => OptionT[F, User]
)
```

Neither of them can pass the compile. Just throw the errors:
```
Cannot find a Schema for type com.ukonnra.wonderland.user.endpoint.graphql.Queries[F].
[error]      Caliban derives a Schema automatically for basic Scala types, case classes and sealed traits, but
[error]      you need to manually provide an implicit Schema for other types that could be nested in endpoint.graphql.Queries[F].
[error]      If you use a custom type as an argument, you also need to provide an implicit ArgBuilder for that type.
[error]      See https://ghostdogpr.github.io/caliban/docs/schema.html for more information.
[error]   val interpreter = GraphQL.graphQL(RootResolver(queries)).interpreter
```

**Comment by ghostdogpr** [comment]
Did you add the caliban-cats module and the import mentioned in the [interop docs](https://ghostdogpr.github.io/caliban/docs/interop.html)? I think the first example should work as long as it’s able to derive a schema for `User`. If not, you can try to call `gen` directly and Magnolia might tell you what’s missing. 

For the second one, you need a `Schema` instance for `OptionT` and fs2 `Stream`. This would be a nice addition to the caliban-cats module if you manage to do it. 

I’m away from computer for the holiday until January 6. When I come back I’ll be able to test this code and help you more if needed 😀

**Comment by UkonnRa** [comment]
Thanks for quick response, I just wrote the fs2.Stream and OptionT Schemas:
```scala
  implicit def optionTSchema[F[_]: Effect, R, A](implicit ev: Schema[R, Option[A]]): Schema[R, OptionT[F, A]] =
    new Schema[R, OptionT[F, A]] {
      override def toType(isInput: Boolean): __Type =
        ev.toType(isInput)

      override def optional: Boolean =
        ev.optional

      override def resolve(value: OptionT[F, A]): Step[R] =
        QueryStep(ZQuery.fromEffect(value.value.toIO.to[Task].map(ev.resolve)))
    }

  implicit def fs2StreamSchema[F[_]: Effect, R, A](
      implicit ev: Schema[R, ZStream[R, Throwable, A]]
  ): Schema[R, fs2.Stream[F, A]] =
    new Schema[R, fs2.Stream[F, A]] {
      override def optional: Boolean                        = ev.optional
      override def toType(isInput: Boolean = false): __Type = ev.toType(isInput)
      override def resolve(value: fs2.Stream[F, A]): Step[R] =
        ev.resolve(ZStream.fromIterator(value.compile.toVector.toIO.to[Task].map(_.iterator)))
    }
```

OptionT Schema works fine, but it seems that the `Stream` cannot work in Query?

Say having a Query schema:

```scala
final case class SimpleQueries[F[_]: Effect](
    items: fs2.Stream[F, String],
)
```
And if the query is `  val query    = """
  {
    items
  }"""`, you will just get `{"items":<stream>}` rather than **a list of String**.

But if:
```scala
final case class SimpleQueries[F[_]: Effect](
    items: F[List[String]],
)
```
Everything works fine.

So I think: **Stream can only use in Subscription operators, but not in Query operators?**

**Comment by ghostdogpr** [comment]
Yes, that is correct: streams are for subscriptions only. If you want to return a list in your queries, you need to run the stream so the type will be an F of List.

**Comment by ghostdogpr** [comment]
Actually it could be a good idea to change the executor logic so that if it’s a subscription it returns the stream but otherwise it just runs it and return the result.

**Comment by UkonnRa** [comment]
It would be great if Stream can be used in both subscription and query! Like this solution!

**Comment by ghostdogpr** [comment]
If you want you could make a PR with those instances for OptionT and Stream in the cats interop module. I’ll work on the case of stream for queries when I get back from vacation.

**Comment by UkonnRa** [comment]
Sure, I think it's not difficult. And here is another thing, maybe I should open another issue to discuss. You know http4s is totally based on cats, but your http4s interop is still use zio. So if I want to use the http4s-interop, I must use the type like `type ExampleTask[A] = RIO[Console with Clock, A]` rather than simply use `cats.IO`. So I wonder why you choose ZIO when implement http4s-interop?

**Comment by ghostdogpr** [comment]
There’s also an F-based function in http4s interop: check `makeHttpServiceF`.

**Comment by ghostdogpr** [comment]
Created #155 for the change of behavior when using a stream with queries and mutations.

**Comment by satorg** [comment]
Hello @ghostdogpr , @UkonnRa !
Just to clarify – is there any update on adding interop for `fs2.Stream` to cats-interop? 
Thank you!

**Comment by ghostdogpr** [comment]
@satorg it has never been added, but it should be doable considering zio-interop-cats allows conversion between fs2 and zio-streams

**Comment by satorg** [comment]
@ghostdogpr take a look please: #1737. Thank you!
