### ISSUE TITLE
Ability to inject context into ZEnvironment in `WebSocketHooks.beforeInit`

### ISSUE THREAD

**Issue by kyri-petrou** [ghostdogpr/caliban#1385]
Hi there. Apologies if this question is very trivial, but I'm not too familiar with ZIO and I haven't had much luck getting this to work.

We're using GraphQL subscriptions with an HTTP4s server and CE interop. For normal queries / mutations, we're using a Kleisli / Local to do Authentication and inject user info into the request context, with a setup similar to [this example](https://github.com/ghostdogpr/caliban/blob/master/examples/src/main/scala/example/http4s/AuthExampleAppF.scala).

With GQL subscriptions though my understanding is that clients can't provide custom HTTP headers during the connection request, which means that the token must be passed as a connection param. I've been using `WebSocketHooks.beforeInit` to do the authentication, but I can't seem to figure out a way to inject the user information into the context and for it to persist for the duration of the connection.

One way I can think of is to use persistent storage, however for that we'd need a way to uniquely identify a user during `beforeInit`, which can be done via the token but unsure on how to do that on subsequent messages.  I was also wondering whether there is a way that this can be done via ZEnvironment / Local to avoid using persistent storage instead

**Comment by ghostdogpr** [comment]
There is an example with zio-http here: https://github.com/ghostdogpr/caliban/blob/c2e272cdc8f6ec7d1368d2bd3e238488e0ac6fc9/examples/src/main/scala/example/ziohttp/AuthExampleApp.scala#L73
I'm not very familiar with the MTL version (wasn't done by me) but isn't it possible to do the same thing?

**Comment by kyri-petrou** [comment]
Nice, the example is very helpful and should work with MTL & CE `Ref`. 

Initially I didn't think of wrapping the `Http4sAdapter.makeWebSocketServiceF` (i.e., `ZHttpAdapter.makeWebSocketService` in the ZIO example) within a `Ref`. I'll try it out and see if it ow

**Comment by kyri-petrou** [comment]
I got it working at the end, thanks again for pointing me to the example!

Going to leave this code here for anyone that might want to implement something similar (Note that the code uses Scala 3.1.3 and Caliban 2.0.0-RC2). With this in place, calls to `Local[F, RequestCtx].ask` will return the ctx that was injected as part of this middleware.

I'm sure there are probably better ways to do the conversions but as I said, I'm not too familiar with interops between ZIO and CE

```scala

private val calibanErrorMapper: PartialFunction[Throwable, CalibanError] =
  case e: CalibanError => e
  case e               => ExecutionError(e.getMessage, innerThrowable = Some(e))

def websocketAuthMiddleware[F[_]: Async](
    routes: WebSocketHooks[RequestCtx, CalibanError] => HttpRoutes[F]
)(using
    interop: Contextual[F, RequestCtx]
): HttpRoutes[F] = {

  val session = Deferred[F, RequestCtx.CtxData].map { deferred =>
    new WebSocketHooks[RequestCtx, CalibanError] {
      override def beforeInit: Option[InputValue => ZIO[RequestCtx, CalibanError, Any]] = Some { inputValue =>
        val ctxF = inputValue match
          case InputValue.ObjectValue(fields) =>
            fields.find(_._1.toLowerCase === "authorization").map(_._2) match
              case Some(StringValue(maybeToken)) =>
                Authorization.parse(maybeToken) match
                  case Right(token) => ??? // Some auth method that accepts Http4s `org.http4s.headers.Authorization`
                  case _            => InvalidAuthentionToken.raiseError
              case _ => MissingAuthenticationToken.raiseError
          case _ => MissingAuthenticationToken.raiseError

        interop.fromEffect(ctxF.flatMap(deferred.complete)).mapError(calibanErrorMapper)
      }

      override def onMessage: Option[StreamTransformer[RequestCtx, CalibanError]] = Some {
        new StreamTransformer[RequestCtx, CalibanError] {
          override def transform[R1 <: RequestCtx, E1 >: CalibanError](
              stream: ZStream[R1, E1, GraphQLWSOutput]
          ): ZStream[R1, E1, GraphQLWSOutput] =
            for
              ctx <- ZStream.fromZIO(interop.fromEffect(deferred.get).mapError(calibanErrorMapper))
              out <- stream.updateService[RequestCtx](_ => ctx)
            yield out
        }
      }
    }
  }

  Kleisli { (req: Request[F]) =>
    for
      hooks <- OptionT.liftF(session)
      resp  <- routes(hooks).run(req)
    yield resp
  }
}
```

And when initializing the app:

```scala
val routes: F[WebSocketBuilder2[F] => HttpRoutes[F]] =
  interpreter.map { i => ws =>

    val httpRoutes = ???

    val wsRoutes = CtxLocal.websocketAuthMiddleware { h =>
      Http4sAdapter.makeWebSocketServiceF[F, RequestCtx, CalibanError](ws, i, webSocketHooks = h)
    }

    Router[F](
      "/api/graphql" -> httpRoutes,
      "/ws/graphql"  -> wsRoutes,
    )
  }
```

**Comment by ghostdogpr** [comment]
Thanks for sharing!
