### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by DGolubets** [ghostdogpr/caliban#1387]
Http4s AuthExampleAppF fails to compile in Scala 3.
`Cannot find a Schema for type F[String]`

**Comment by ghostdogpr** [comment]
With Scala 3 instead of using `GenericSchema` you have to specificy type parameters when you call `graphQL`:
```scala
graphQL[AuthInfo, Query[F], Unit, Unit](RootResolver(query))
```
See https://ghostdogpr.github.io/caliban/docs/schema.html#effects
