### ISSUE TITLE
WS server doesn't start on Http4s since 1.4.2

### ISSUE THREAD

**Issue by gaspb** [ghostdogpr/caliban#1419]
Hello,

We just tried to update from 1.4.1 to 1.4.2, but our http4s websocket server stopped working (no error on the server, but the ws endpoint becomes unreachable)

```
❯ npx diagnose-endpoint@1.1.0 --endpoint=wss://app/ws/graphql
Diagnosing wss://app/ws/graphql
⚠️  Could not resolve (ENOTFOUND)
Is the address correct?
Is the server running?
```

I get the same result with the http4s example app, the http endpoint works but the ws doesn't

**Comment by guizmaii** [comment]
Might be related to this recently-fixed-but-not-yet-released bug: https://github.com/ghostdogpr/caliban/pull/1417

**Comment by ghostdogpr** [comment]
Yeah it was fixed yesterday, not released yet (https://github.com/ghostdogpr/caliban/pull/1417).
Can you try with snapshot `1.4.2+6-5472838d-SNAPSHOT`?

**Comment by gaspb** [comment]
seems to fix it :+1: thanks

**Comment by ghostdogpr** [comment]
In case anybody needs, the snapshot for 2.x is `2.0.0+5-66bf1858-SNAPSHOT`.
I will probably release by the end of the week, just want to check a couple reported issues first.
