### ISSUE TITLE
Find a way to inject `HTTPRequest` in middleware

### ISSUE THREAD

**Issue by UkonnRa** [ghostdogpr/caliban#142]
Now it seems that there is not a way to get the `HTTPRequest` in the wrap phase, which is important handling the Authentication. I think we need a way to inject `HTTPRequest` during the wrap phase

**Comment by ghostdogpr** [comment]
Can you be more specific? I’m using http4s and I was able to add a middleware on top of the route created by caliban. There’s also a blog post by @fokot here http://fokot.github.io/post/caliban-auth.html

**Comment by UkonnRa** [comment]
**Problem**

The core problem is, I cannot **access the Request** when using `Http4sAdapter.makeHttpServiceF`, so that if I want to do the Auth work, I have to rewrite `makeHttpService` function. Like the link from @fokot.

**One More Step**

Well, what I really want is like:
```scala
final case class Auth(email: String)

case class Mutations[F[_]: Effect](
    createUser: (Auth, CreateUser) => F[User],
    updateUser: (Auth, UpdateUser) => F[User]
)

object Mutations {

  def createUser[F[_]: Effect](auth: Auth, command: CreateUser): F[User] = {
    val M = implicitly[Effect[F]]
    if (!createSpecificAuthLogic(auth)) {
      M.raiseError(new Throwable("Auth not passed"))
    } else {
      ???
    }
  }
}
```

Where `class Auth` is the Authentication payload from HTTP Header, like a JWT or other stuff.

Then when constructing a router, I will **inject the Auth class**, like:
```scala
Http4sAdapter.makeHttpServiceF[IO, Any](endTup._1.interpreter) { case req: Request[F] =>
    elegantWayToInject(req.header)
}
```

**Comment by ghostdogpr** [comment]
You can't use `createUser: (Auth, CreateUser) => F[User]` and provide `Auth` dynamically because all argument values are expected to come from the graphql query.

I think the way to go is to use `Kleisli` or `ApplicativeAsk` from cats-mtl in your Queries/Mutations objects and write a custom `Schema` that converts the input value to a ZIO environment requirement.

**Comment by UkonnRa** [comment]
Thanks, I will try to find a way

**Comment by AlixBa** [comment]
Hey @UkonnRa , how did you do it in the end?
