### ISSUE TITLE
Add module for Play support

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#143]
With support for Play Json serialization and routing.

**Comment by paulpdaniels** [comment]
For reference: 
Describes the compile time entry point for a play application
https://www.playframework.com/documentation/2.8.x/ScalaCompileTimeDependencyInjection#Application-entry-point

Describes how a router is instantiated:
https://www.playframework.com/documentation/2.8.x/ScalaCompileTimeDependencyInjection#Providing-a-router

Note the above is for generated routers, it is also possible to create a router directly using an embedded syntax:

```
Router.from {
  case POST("/graphql") => controller.graphql
}
```

Routers are essentially just a wrapper over a `PartialFunction[RequestHeader, Handler]` where the `Handler` is a marker trait for something that handles a request. The two most common handlers are `Action[A]` and `WebSocketHandler`. `Action`s are generally defined using a callback syntax i.e.

```
Action.async(parse.json[Body]) { request =>
  Future.successful(Ok)
}
``` 

There is also `apply` if the execution block will be synchronous.

For our purposes I think the most "battery included" method of incorporating `caliban` into play would be to create a custom `Router`, but it should be possible to also do a single handler implementation similar to the `AkkaHttp` version.

**Comment by fagossa** [comment]
hello, can I take this one?

**Comment by ghostdogpr** [comment]
@fagossa Hi! I think @yoohaemin was already working on it but he also wanted to get some feedback from people with Play experience.

@yoohaemin let us know where you're at and if @fagossa can help. Thanks!

**Comment by vpavkin** [comment]
Hello, all :)
I have both incentive and time to bring this one to completion soon. Please let me know if I can pick it up from here

Thanks!

**Comment by yoohaemin** [comment]
Hi @vpavkin , it's all yours. Thanks.

**Comment by ghostdogpr** [comment]
Play-json integration is now part of caliban core. The work of creating the adapter with an example (which should be easier now that play-json is supported) is still TODO if anyone is interested.

**Comment by javimartinez** [comment]
Anyone working on this already? Otherwise, I'd like to tackle it.

**Comment by ghostdogpr** [comment]
@javimartinez that'd be awesome! As mentioned earlier, the json serialization is already included in caliban so you can reuse it. We also agreed previously on supporting Play 2.8 only.

**Comment by javimartinez** [comment]
Great! I'm going to work on it then
