### ISSUE TITLE
Can't sent Upload that are in the case class (some Input) and not at the root level

### ISSUE THREAD

**Issue by vlazarew** [ghostdogpr/caliban#1430]
Hello

I created mutation with next spec:

`case class HtmlInput (url: String, html: Upload, attachments: Seq[Attachment] = Seq.empty) `
`case class Attachment(url: Option[String], file: Upload)` , where Upload is caliban.uploads type.

So, UI passed to me correct HtmlInput.

But, when i send this mutation like this 
![image](https://user-images.githubusercontent.com/32881769/182826191-5d571997-6f3c-4a52-8164-44b57646725e.png)

i have next problem 
![image](https://user-images.githubusercontent.com/32881769/182826236-82d63cfc-cd53-4784-a702-3d90ff42cf82.png)

I think, that Caliban doesn't recognize any Upload, which located into nested Input.
I came to this conclusion, because if i send mutation like this 
![image](https://user-images.githubusercontent.com/32881769/182826558-f6015667-6a40-4cbb-b842-eab4609c6c9a.png)

or

`mutation uploadHTML($html: Upload!, $file1: Upload!, $file2: Upload!) {
  uploadHtml(
    url: "test"
    html: $html
    attachments: [{ url: "test", file: $file1 }, { url: "test2", file: $file2 }]
  )
}
`
all works great.

But in last case, i must create Upload variable for every file, instead conside AttachmentInput.

Any idea what can cause this issue and how to fix it?

**Comment by ghostdogpr** [comment]
We have a unit test for this case, so it should be supported, see the code in https://github.com/ghostdogpr/caliban/blob/66bf18582048910082fb73f2077ebd865df70655/interop/tapir/src/test/scala/caliban/interop/tapir/TapirAdapterSpec.scala#L125 and https://github.com/ghostdogpr/caliban/blob/66bf18582048910082fb73f2077ebd865df70655/interop/tapir/src/test/scala/caliban/interop/tapir/TestApi.scala#L35

If not working, can you provide some way to reproduce it easily?

**Comment by vlazarew** [comment]
Thank you,

Can you tell me which version of this functionality appeared?

We're using caliban 1.2.4 and have this behaviour

Maybe i should use newer version?

**Comment by frekw** [comment]
I think this was fixed in 1.3.0 https://github.com/ghostdogpr/caliban/releases/tag/v1.3.0
