### ISSUE TITLE
Schemas without String scalars produce invalid introspection

### ISSUE THREAD

**Issue by onsoup42** [ghostdogpr/caliban#1432]
The introspection will be invalid if the schema doesn't contain any String scalars. If the String type is not used it will be omitted from the introspection result.  However, the introspection for the @specifiedBy directive still references the String scalar, which is invalid:

```json
{
    "name": "specifiedBy",
    "description": "The @specifiedBy directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar types. The URL should point to a human-readable specification of the data format, serialization, and coercion rules. It must not appear on built-in scalar types.",
    "locations": [
        "SCALAR"
    ],
    "args": [
        {
            "name": "url",
            "description": null,
            "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                    "kind": "SCALAR",
                    "name": "String",
                    "ofType": null
                }
            },
            "defaultValue": null
        }
    ]
}
```

This is a problem for tools like GraphiQL.

Work around: Just add a String scalar to the schema.

**Comment by paulpdaniels** [comment]
Strings are built in scalars though so I don't know how you'd have a schema without them. Are you saying it needs to be used by something to be included in introspection,

**Comment by ghostdogpr** [comment]
You're right, I hardcoded `Boolean` because of `skip` and `include` directives, should do the same for `String` because of `specifiedBy`. Opening a PR right now.
