### ISSUE TITLE
Unable to run zio-quickstart-graphql-webservice with zio 2 and Scala 3

### ISSUE THREAD

**Issue by trival** [ghostdogpr/caliban#1442]
I have cloned the quickstart repo https://github.com/zio/zio-quickstart-graphql-webservice
and changed the scalaVersion to "3.1.3" in build.sbt and now the code doesn't compile any more, giving following error: 

``` 
[error] -- [E007] Type Mismatch Error: src/main/scala/dev/zio/quickstart/MainApp.scala:36:12 
[error] 36 |            ZHttpAdapter.makeHttpService(interpreter)
[error]    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |            Found:    zhttp.http.HttpApp[Any, Throwable]
[error]    |            Required: zhttp.http.Http[Any, Nothing, Any, Nothing]
```

Seems like `makeHttpService` doesn't provide the expected Type any more in scala 3. ScalaVersion "2.13.8" compiles fine. 
Is there any way to make this example work with scala 3 or is this incompatibility expected? I am new to scala / zio and unable to figure out how to proceed.

**Comment by ghostdogpr** [comment]
`Http.collectHttp` needs to be changed to `Http.collectHttp[Request]`. Would you like to do a PR for zio-quickstart-graphql-webservice?

**Comment by trival** [comment]
Thanks for the help!
