### ISSUE TITLE
Subscriptions do not work in client-laminex example

### ISSUE THREAD

**Issue by pmeheut** [ghostdogpr/caliban#1443]
Hi,
I've cloned the current series/2.x code, ran Example.app in http4s and the client using yarn as described in the documentation.
The page I got from http://localhost:3000/ displays the list of characters. Pressing the "delete first" button does the mutation, ``subscribers.publish(name)`` line 50 of ExampleService.scala is called but the client never receives the notification.

I checked the network traffic using Chrome and I see nothing sent to Websocket.

**Comment by ghostdogpr** [comment]
Indeed, the subscription needs to happen only after the connection has been initialized. I fixed the example in https://github.com/ghostdogpr/caliban/commit/e8c046ab83bda4b72516358fb3ca66c0fc083f02 and https://github.com/ghostdogpr/caliban/commit/719a61c339682cc6847dccc1aa3a547764915337 (also fixed the docs)
