### ISSUE TITLE
Validation is now failing with extra fields

### ISSUE THREAD

**Issue by gaspb** [ghostdogpr/caliban#1445]
Hello,

Prior to 1.4.2 (specifically [this change](https://github.com/ghostdogpr/caliban/pull/1376/files#diff-615a525e20015b8f613cbcc81603fa073d321eb09a0323d260c487f8f861111fL129-R131 )) extra fields were accepted by the server and discarded. 
So if a server were to remove a field from the schema (or if a client were to send some unexpected or utility field like a __typename), the clients would still be working. After 1.4.2 requests fail with ValidationError

Is this side effect expected ? 
If yes it could make sense to add a warning in the changelog as it can break existing applications

**Comment by frekw** [comment]
This is expected and in [accordance to the spec](https://spec.graphql.org/June2018/#sec-Input-Object-Field-Names). This is to prevent things like unintended typos of field names.

However, removing a field in a GQL API will always be backwards incompatible no matter what so I don't see any issues with it.

If you wish you can opt out of validation by providing `skipValidation = true` to your interpreter.
