### ISSUE TITLE
Regarding Order of DataSource Requests

### ISSUE THREAD

**Issue by iida-hayato** [ghostdogpr/caliban#1454]
I read this document.
https://ghostdogpr.github.io/caliban/docs/optimization.html

and found the following comment about DataSource

`fromFunctionBatchedZIO`

```
Constructs a data source from an effectual function that takes a list of requests and returns a list of results of the same size.
```

`result list must correspond to the item at the same index in the request list`
This in this specification, I think it is inconvenient to use.

I think it would be convenient to have a method to get data with Request as a key, but should it be in Calban or ZQuery?

Or should it better that such an implementation be left to the programmer and noted in the documentation?

**Comment by adamgfraser** [comment]
@iida-hayato See `DataSource.fromFunctionBatchedWithZIO`.

**Comment by ghostdogpr** [comment]
Indeed I believe `fromFunctionBatchedWithZIO` is what you needed 😄

**Comment by iida-hayato** [comment]
Thanks, It seems work well.
