### ISSUE TITLE
AuthExampleApp.scala bug

### ISSUE THREAD

**Issue by lachezar** [ghostdogpr/caliban#1476]
In the current example for ziohttp the following line blocks the execution and no messages can be exchanged. Removing the line fixes it.

```
WebSocketHooks.afterInit(ZIO.failCause(Cause.empty).delay(10.seconds))
```

**Comment by ghostdogpr** [comment]
Discussed this a long time ago but forgot to actually fix it 🤦 https://discord.com/channels/629491597070827530/633200096393166868/1002199513798299698

Fix is simple but test is not. Will look into it.
