### ISSUE TITLE
Wildcard underscore breaks dotty assumptions

### ISSUE THREAD

**Issue by avanov** [ghostdogpr/caliban#1500]
Hi,

For the given valid graphql definition:
```graphql
type Query {
  _: Boolean
}
```

the server codegen produces the following:

```scala
object Operations:

    final case class Query(
        `_`: zio.UIO[scala.Option[Boolean]]
    )
```

and it breaks this Scala3 assumption: https://github.com/lampepfl/dotty/issues/14746

Perhaps, the codegen can substitute wildcards of this sort with `_unused` or something and make resolution working based on `_` => `_unused` mapping.

**Comment by ghostdogpr** [comment]
Just realized we already had an issue for the underscore problem https://github.com/ghostdogpr/caliban/issues/1388
