### ISSUE TITLE
[Docs] Why ArgBuilders have to be defined as lazy

### ISSUE THREAD

**Issue by coderfromhere** [ghostdogpr/caliban#1509]
Hi,

I couldn't find a note on the matter in the docs and I couldn't find another place to ask about it, so maybe let's cover it here as a ticket that can be used for the purpose of docs improvement.

Is there a particular reason why all ArgBuilders are defined as implicit lazy vals rather than just implicit vals? Is there a particular non-trivial resolution order that requires sequencing, or maybe other reasons? Thanks!

**Comment by guizmaii** [comment]
> Is there a particular reason why all ArgBuilders are defined as implicit lazy vals rather than just implicit vals? Is there a particular non-trivial resolution order that requires sequencing, or maybe other reasons? Thanks!

Where did you see that they have to be defined with `lazy val`? 🤔

**Comment by ghostdogpr** [comment]
It's mostly because of recursive types or types that use each other.
If you define them as `val`, the order in which they are defined may be important, but when they are lazy you can define them in any order.
