### ISSUE TITLE
[CodeGen] Generated files are invalid according to scalafmt

### ISSUE THREAD

**Issue by jfwilson** [ghostdogpr/caliban#1510]
The scalafmt formatting done by `calibanGenClient` is very nearly correct, but has an extra newline at the end of the file that `scalafmtCheck` rejects (at least when using default settings).

I've created an [example project](https://github.com/jfwilson/caliban-newline-issue) that demonstrates the problem, or you can reproduce from scratch by:

1. Create a `.scalafmt.conf` file, e.g.

    ```
    version = 3.6.1
    runner.dialect = scala213
    preset = default
    ```

2. Create minimal `sbt` project with scalafmt and caliban-codegen

    ```
    addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
    addSbtPlugin("com.github.ghostdogpr" % "caliban-codegen-sbt" % "2.0.1")
    ```

4. Run `calibanGenClient` to generate client scala

    ```
    calibanGenClient project/ClientSchema.graphql src/main/scala/client/ClientSchema.scala
    ```

Expected behaviour:

`scalafmtCheck` passes

Actual:

`scalafmtCheck` fails due to extra newline at the end of the client scala file

I suspect the issue is due to the use of `PrintWriter.println` on already-formatted `objectCode` here: https://github.com/ghostdogpr/caliban/blob/series/2.x/tools/src/main/scala/caliban/tools/Codegen.scala#L69

**Comment by jfwilson** [comment]
Happy to take a look myself and see if replacing `println` with `print` fixes it (or introduces problems elsewhere).

**Comment by ghostdogpr** [comment]
The workaround sounds correct. PR welcome!
