### ISSUE TITLE
Client code generation does not appropriately map ID to custom Scalar type

### ISSUE THREAD

**Issue by thehyperactivedeveloper** [ghostdogpr/caliban#1524]
When using the client generator `` --sclarMappings ID:ID`` maps the ID to a String rather than a custom type ID. 

### For context: 

The ``--scalarMappings ID:ID `` works appropriately in the schema generation on the server side.

**Comment by ghostdogpr** [comment]
@thehyperactivedeveloper I just merged a fix. Can you try with the latest snapshot and confirm that it works?
