### ISSUE TITLE
Generated client code isn't compatible with scala 3.1.x and higher

### ISSUE THREAD

**Issue by kwyczesany** [ghostdogpr/caliban#1539]
Generated Client code contains imports, that are using `_` wildcard, which is removed from scala 3.1.x and 3.2.x, instead of `*`

```
import caliban.client.FieldBuilder._
                                   ^
`_` is no longer supported for a wildcard import; use `*` instead
```

**Comment by ghostdogpr** [comment]
Is it really not supported? 

https://scastie.scala-lang.org/Te5NKxhcQDe7y7qpRgF7xA looks okay. Also caliban code cross compiles to Scala 3.2.1 and uses `_` evrywhere 🤔

**Comment by ghostdogpr** [comment]
Guessing it's because you use the `-source:future` flag?

**Comment by kwyczesany** [comment]
Yes, I haven't noticed that I had this flag enabled. Sorry for the trouble
