### ISSUE TITLE
Errors: must be a non-empty list

### ISSUE THREAD

**Issue by eamelink** [ghostdogpr/caliban#159]
According to the spec (https://graphql.github.io/graphql-spec/June2018/#sec-Errors):

> The errors entry in the response is a non‐empty list of errors, where each error is a map.

> If no errors were encountered during the requested operation, the errors entry should not be present in the result.

Currently Caliban returns an empty list if there are no errors, breaking at least one client (elm-graphql).

**Comment by ghostdogpr** [comment]
Actually I think this was recently fixed by @paulpdaniels in #145 

Is that blocking you? I can do a patch release tomorrow if you need it.

**Comment by eamelink** [comment]
Ah, yes that seems to fix need. No need to rush a release for me, I'll post-filter it out myself for now. Thanks!
