### ISSUE TITLE
MonixInterop does not work correctly

### ISSUE THREAD

**Issue by satorg** [ghostdogpr/caliban#1619]
Several methods in `MonixInterop` are implemented incorrectly. E.g. consider:
https://github.com/ghostdogpr/caliban/blob/a6a9e128de011eb7a28f0f977b3221c2c3ae342a/interop/monix/src/main/scala/caliban/interop/monix/MonixInterop.scala#L48-L53

It creates a `MonixTask` with `async` that provides a callback `cb` to the inner closure. The callback _must_ be used to report a result of the underlying async execution, but it is not the case actually. Therefore, the created `MonixTask` will never complete.

Moreover, there are other methods in `MonixInterop` that share the same issue: `executeAsync` and `checkAsync`.

**Comment by ghostdogpr** [comment]
Indeed looks like it was broken in https://github.com/ghostdogpr/caliban/pull/1407/files#diff-7ac6ec76e4321488c5b63218de463ecddf29492ca1e47cefc8f5679ed83b29d1

**Comment by satorg** [comment]
I am not a pro in such sort of interop, but I would suppose that a working conversion from ZIO to Monix Task (with regards to cancellation) could look like
```scala
def zio2monix[R, A](zioTask: RIO[R, A], zioRuntime: Runtime[R]): MonixTask[A] = {
  MonixTask.cancellable0 { (scheduler, callback) =>
    Unsafe.unsafe { implicit u =>
      val future = runtime.unsafe.runToFuture(zioTask)
      future.onComplete(res => callback(res))(scheduler)
      MonixTask.deferFuture(future.cancel()).void
    }
  }
}
```
(disclaimer: not really verified)

Perhaps, there's a simpler/more correct way to achieve that though...

**Comment by ghostdogpr** [comment]
Opened a PR https://github.com/ghostdogpr/caliban/pull/1628
