### ISSUE TITLE
Add module for Finch support

### ISSUE THREAD

**Issue by hderms** [ghostdogpr/caliban#162]
an HTTP adapter for https://github.com/finagle/finch would be useful to us. We're very interested in Caliban

**Comment by ghostdogpr** [comment]
Sounds good (even though I've never used Finch myself, it's totally doable).
Is there a JSON library that is more commonly used with Finch? Is Circe okay?

**Comment by hderms** [comment]
@ghostdogpr I'm working on a PR for this btw. I'd be using Circe. I had some questions I'll add once I have a draft PR
