### ISSUE TITLE
Type names validations

### ISSUE THREAD

**Issue by fokot** [ghostdogpr/caliban#170]
You can write output type like `case class XXXInput` and input type `case class XXX` which would produce invalid schema. `Graphiql` will fail on this.

Also another possible error is having two  output types with same name from different packages which will result in error that the first type is used in Schema, so `graphiql` does not report error but wrong type is there and it will fail when executing request if I use field which is present in first type but not in second.

**Comment by ghostdogpr** [comment]
I agree some kind of check would be useful. The question is at which point do we perform that check and how do we report the problem. Most functions for building and combining apis are pure and without effects. The one that’s effectful is run for each request so it’s not ideal for this.

**Comment by ghostdogpr** [comment]
Since #227 , we now validate the schema when calling `.interpreter`. So we have a place to implement these checks.

**Comment by ghostdogpr** [comment]
Working on this.
