### ISSUE TITLE
Schema derivation: optionality is derived incorrectly for `zio.Task` effects

### ISSUE THREAD

**Issue by satorg** [ghostdogpr/caliban#1774]
Caliban version: 2.2.1

Consider an example:
```scala
case class Foo(id: Int)

case class Queries(
    optionalUIO: UIO[Option[Foo]],
    mandatoryUIO: UIO[Foo],
    optionalTask: Task[Option[Foo]],
    mandatoryTask: Task[Foo]
)

object ExampleApp extends ZIOAppDefault {

  val queries =
    Queries(
      optionalUIO = ZIO.succeed(Some(Foo(id = 123))),
      mandatoryUIO = ZIO.succeed(Foo(id = 456)),
      optionalTask = ZIO.succeed(Some(Foo(id = 321))),
      mandatoryTask = ZIO.succeed(Foo(id = 654))
    )
  val api = graphQL(RootResolver(queries))

  override def run = Console.printLine(api.render)
}
```
Actual output:
```graphql
schema {
  query: Queries
}

type Foo {
  id: Int!
}

type Queries {
  optionalUIO: Foo
  mandatoryUIO: Foo!
  optionalTask: Foo
  mandatoryTask: Foo
}
```
Note that `mandatoryUIO` is derived as a mandatory field indeed whereas `mandatoryTask` is derived as an optional one.

Expected output:
```graphql
...

type Queries {
  optionalUIO: Foo
  mandatoryUIO: Foo!
  optionalTask: Foo
  mandatoryTask: Foo!
}
```
I.e. the `mandatoryTask` field has to be mandatory the same way as the `mandatoryUIO` field is.

**Comment by satorg** [comment]
Update: looks like the same is applicable to `UQuery`/`TaskQuery` effects:
```scala
case class Queries(
    optionalUIO: UIO[Option[Foo]],
    mandatoryUIO: UIO[Foo],
    optionalTask: Task[Option[Foo]],
    mandatoryTask: Task[Foo],
    optionalUQuery: UQuery[Option[Foo]],
    mandatoryUQuery: UQuery[Foo],
    optionalTaskQuery: TaskQuery[Option[Foo]],
    mandatoryTaskQuery: TaskQuery[Foo]
)
```
which renders the following:
```graphql
type Queries {
  optionalUIO: Foo
  mandatoryUIO: Foo!
  optionalTask: Foo
  mandatoryTask: Foo # incorrect
  optionalUQuery: Foo
  mandatoryUQuery: Foo!
  optionalTaskQuery: Foo
  mandatoryTaskQuery: Foo # incorrect
}
```

**Comment by ghostdogpr** [comment]
This is intentional, see https://ghostdogpr.github.io/caliban/docs/schema.html

**Comment by satorg** [comment]
@ghostdogpr , oh, I see the table, thanks for pointing it out.. But what is the reasoning behind such a decision? Not that obvious to me, because it seems it does not convert a Throwable into a null value automatically. In other words, if I declare it as `foo: Task[Foo]` and the effect that resolves `Foo` raises an error, it will results to a query error rather than a null value, won't it? 

It is especially strange if we compare it to the cats-interop: if I declare `foo: F[Foo]` where `F` is backed by `Async` then the type will be derived as a not nullable one, even though `Async[F]` is semantically closer to `zio.Task` rather than `UIO`.

**Comment by ghostdogpr** [comment]
ZIO has 2 error channels (`ZIO.fail` and `ZIO.die`), so we took advantage of that to express the 2 different ways to handle errors in GraphQL: return null for the errored field (fail), or fail the whole query (die). In the first case, it will convert a Throwable to a null value. You can add `.orDie` to your resolvers to change them from the first mode to the second (and change the type to `UIO`).

**Comment by satorg** [comment]
Ok, I see the difference now, thank you for the clarification. Just for a record, if someone runs into it, then the following can help them to save their time in the future:
```scala
case class Queries(uio: UIO[Int], task: Task[Int])

val queries = Queries(
  uio = ZIO.fail(new RuntimeException("UIO failed")).orDie,
  task = ZIO.fail(new RuntimeException("Task failed"))
)
val api = graphQL(RootResolver(queries))
```
Generated Schema:
```graphql
schema {
  query: Queries
}

type Queries {
  uio: Int!
  task: Int
}
```
Then the query `{ uio }` fails this way:
```
response.data:
null
response.errors:
Execution Error: Effect failure java.lang.RuntimeException: UIO failed
```
Whereas the query `{ task }` fails like this:
```
response.data:
{"task":null}
response.errors:
Execution Error: Effect failure java.lang.RuntimeException: Task failed
```
Closing this issue.
