### ISSUE TITLE
Pekko variant?

### ISSUE THREAD

**Issue by MichelEdkrantz** [ghostdogpr/caliban#1823]
Hi!
Thanks for this great lib :) Now that Pekko 1.0 has been released, is there any interest from your end to provide a pekko variant of this?

https://github.com/apache/incubator-pekko

I believe it would be most a copy of this, but with imports changed to pekko. 
https://github.com/ghostdogpr/caliban/blob/series/2.x/adapters/akka-http/src/main/scala/caliban/AkkaHttpAdapter.scala

Tapir has no pekko support yet, but looks like it's in the making
https://github.com/softwaremill/tapir/issues/2884

**Comment by ghostdogpr** [comment]
Yeah, I'm definitely okay with having a pekko-http adapter.

As you said, we need tapir support first but as soon as it's available we can add that adapter (it'll be quite easy).

**Comment by MichelEdkrantz** [comment]
Created a fork and a PR in #1862. Some issues remain but hoping to move this forward somehow 😅
