### ISSUE TITLE
Support deprecation of InputValues

### ISSUE THREAD

**Issue by brodin** [ghostdogpr/caliban#1848]
The support for deprecation of input values was added to the spec about a year a ago (https://github.com/graphql/graphql-spec/pull/805) would it be possible to modify [InputValue.scala#L8-L12 ](https://github.com/ghostdogpr/caliban/blob/series/2.x/core/src/main/scala/caliban/introspection/adt/__InputValue.scala#L8-L12) in a way so that it also honours the deprecation decorator (`GQLDeprecated`)?

**Comment by ghostdogpr** [comment]
We usually work off the "released" spec (https://spec.graphql.org/) but for some features such as Defer or more recently the `oneof` directive, we add support earlier than that so I have no problem adding this one.

**Comment by brodin** [comment]
Ah, my bad @ghostdogpr ! Did not know about the difference between "merged" and "released" for the spec!

Appreciate the flexibility thou 🙏
