### ISSUE TITLE
Codegen: support input

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#186]
The sbt plugin caliban-codegen generate your case classes from a GraphQL schema. It currently doesn't support input types.

Parse inputs and generate the appropriate case classes.

You can have a look at how `type` is currently handled and apply the same logic. Let me know if you need some guidance, I'll be happy to help.

**Comment by atapin** [comment]
@ghostdogpr I started working on this. It looks like we need to support of inputs in the parser as well. Is it ok to do both core and codegen changes in a single PR?

**Comment by ghostdogpr** [comment]
@atapin Awesome! You're correct, each of those issues requires extending the parser to support the missing [type definitions](http://spec.graphql.org/June2018/#TypeDefinition), and then adding the corresponding code generation. Perfectly fine to do all in one PR.
