### ISSUE TITLE
Example shuts down immediately

### ISSUE THREAD

**Issue by oyvindberg** [ghostdogpr/caliban#1911]
Hey there!

I wanted to check out the example for tapir integration by running it locally.
It starts fine, but immediately shuts down before I could try it. 
This is on `series/2.x` branch, cd0824e8

By looking at the other examples, I noticed that some of them had sprinkled some `zio.Console.readLine` in there. I added one to the tapir example, and that made it work.

Maybe take a pass through all the examples and handle this in a less hacky-looking manner?

**Comment by ghostdogpr** [comment]
I just fixed it, this was an oversight. Thanks for the report!
