### ISSUE TITLE
GraphQL instances get combined incorrectly if one or both root queries are somehow deferred

### ISSUE THREAD

**Issue by satorg** [ghostdogpr/caliban#1918]
Initial discussion in Discord: [link](https://discord.com/channels/629491597070827530/633200096393166868/1157359669795360969)

There's a test suite I've created in my fork of **caliban** that shows a bunch of various scenarios where the combine method does not work correctly:
https://github.com/satorg/ghostdogpr.caliban/blob/76f44085db19f619b3d5b6ac464ba5dd9382bec1/core/src/test/scala/caliban/execution/GraphqlCombineSpec.scala

In short, let's assume there are two root queries we would like to combine:
```scala
case class Query1(one: Int)
case class Query2(two: Int)

val query1 = Query1(1)
val query2 = Query2(2)
```

Basically, the `GraphQL#combine` only  works correctly, if both queries are provided as direct values:
```scala
val api = graphQL(RootResolver(query1)) |+| graphQL(RootResolver(query2))
```
However, if any of the root queries or both are somehow deferred, then even though the `combine` method completes successfully and pretends producing a correct combined schema, the result combined GraphQL instance won't not work correctly. It won't be failing, though, but simply returning `null` for the deferred source root query, which is very confusing.

For example, assume:
```scala
val api = graphQL(RootResolver(query1)) |+| graphQL(RootResolver(() => query2)) // watch `query2` here
```

Now if we print `api.render` then pretty much correct combined GraphQL schema will be rendered:
```graphql
schema {
  query: Query2
}

type Query2 {
  one: Int!
  two: Int!
}
```
Nothing suspicious at this point yet, is it? However, if we execute a valid GraphQL query on such an instance:
```scala
for {
  interpreter <- api.interpreter
  response    <- interpreter.execute("query test { one two }")
} yield response.data.toString
```
Then we get a pretty surprising response:
```json
{"one":1,"two":null}
```
Note: there will be no errors in the response, i.e. `response.errors` will be empty. It is just the `two` value will be set to `null` even though the rendered schema above claims it is a non-nullable one.

The same thing happens for `query1` as well as any other kind of deferring or indirection: `ZIO.succeed(query)`, `(_: Field) => query` or even `(_: Field) => ZIO.succeed(query)`. In all the cases, the combined GraphQL instance gets created without an error and renders the correct combined schema. It just does not work correctly.

**Comment by ghostdogpr** [comment]
If you do `RootResolver(() => query2)`, the type of your query will be `Function1` instead of `Query2` which is why it's not working properly. You can try adding type parameters explicitly and you will see it won't work with `Query2`.

**Comment by satorg** [comment]
> If you do RootResolver(() => query2), the type of your query will be Function1 instead of Query2 which is why it's not working properly.

Not exactly so. Actually, if I do
```scala
val api = graphQL(RootResolver(() => query))
```
then `api` _will_ be working correctly. It stops working only when combined with any other `GraphQL` instance.

All these cases are shown in my test suite - i.e. any kind of deferring/indirection I could think of works perfectly fine for any single, non-combined GraphQL instance. But stops working once it gets combined with anything else.

**Comment by ghostdogpr** [comment]
It works but that's luck because it was not intended to be used that way 😄

May I ask why you need such a thing?

**Comment by satorg** [comment]
For me it is not something I can not live without. I've worked it around already.

But my point is that it would be really helpful if the behavior was more predictable (rather than just return a `null` result afterwards).
In other words, if some feature (like deferred query) is prohibited, then
- it either should fail (with a clear error) at compile time;
- or if the former option is difficult to implement then at least fail at runtime when the a `GraphQL` instance is about to be created.

The latter means (probably) that the `graphQL` function's return type should not be just `GraphQL` but rather `ZIO` or `Either` (or whatever) – this is why the first option is preferable, of course.
