### ISSUE TITLE
Codegen: Incorrect order of description in server sealed trait generation

### ISSUE THREAD

**Issue by queirosa** [ghostdogpr/caliban#1999]
I noticed a codegen problem when the result is a sealed trait:

```graphql
"""TypeNameDescription"""
interface TypeName {
  """fooDescription"""
  foo: AType!
}
```

```scala
@GQLInterface
@GQLDescription("traitDescription")
sealed trait TypeName extends scala.Product with scala.Serializable  {
         def @GQLDescription("description") foo : AType
}
```

And

```scala
def @GQLDescription("description") foo : AType
```
Isn't valid scala and should be : 

```scala
@GQLDescription("description") def status : AType
```

I suspect the problem comes from : https://github.com/ghostdogpr/caliban/blob/2a2479a4647eef592203df1538094a8d7deb84c9/tools/src/main/scala/caliban/tools/SchemaWriter.scala#L116

I can solve this but I'm afraid I don't know what is the correct way relatively to the rest of the codebase.

**Comment by ghostdogpr** [comment]
Woops, opened a PR to fix it
