### ISSUE TITLE
Support for IO in the tapir interop adapter

### ISSUE THREAD

**Issue by davisuga** [ghostdogpr/caliban#2047]
I want to create a graphql endpoint using Caliban:
https://ghostdogpr.github.io/caliban/docs/interop.html#tapir
It only works with Zio but my project uses cats.
Is it possible without a full refactor of my endpoints?

**Comment by kyri-petrou** [comment]
Hi @davisuga, there is a section in the documentation on how to interop Cats Effect with Caliban: https://ghostdogpr.github.io/caliban/docs/interop.html#cats-effect

Is this what you need?

**Comment by davisuga** [comment]
> Hi @davisuga, there is a section in the documentation on how to interop Cats Effect with Caliban: https://ghostdogpr.github.io/caliban/docs/interop.html#cats-effect
> 
> Is this what you need?

It doesn't work with tapir since .toGraphQL is only implemented using ZIO.

**Comment by kyri-petrou** [comment]
@davisuga I'm not sure I fully understand at which point is it that you want to extract an `IO` instead of a `ZIO`. Could you provide some sample code to help me understand the issue you're facing?

Also, if you prefer, you can also reach out to us on our Discord channel: https://discord.com/channels/629491597070827530/633200096393166868

**Comment by ghostdogpr** [comment]
Also you can look at [this example](https://github.com/ghostdogpr/caliban/blob/series/2.x/examples/src/main/scala/example/interop/cats/ExampleCatsInterop.scala) for a schema using Cats IO and [that example](https://github.com/ghostdogpr/caliban/blob/series/2.x/examples/src/main/scala/example/http4s/ExampleAppF.scala) for using the http4s adapter with Cats IO.

**Comment by davisuga** [comment]
> @davisuga I'm not sure I fully understand at which point is it that you want to extract an `IO` instead of a `ZIO`. Could you provide some sample code to help me understand the issue you're facing?
> 
> Also, if you prefer, you can also reach out to us on our Discord channel: https://discord.com/channels/629491597070827530/633200096393166868

I would like to reuse my tapir endpoints with Caliban without rewriting all the way down to use F[_].

My goal is to do something like
https://github.com/ghostdogpr/caliban/blob/ee2d9e9366ec123cb5e98bc4ef72cd3ee2816a94/examples/src/main/scala/example/tapir/Endpoints.scala

In this example, the logic functions return ZIO, but all my logic functions return cats.effect.IO[Either[_,_]]
The tapir integration documentation says to use the .toGraphQL method, which is only implemented using ZIO.

For example, let's say I have a tapir project that looks like this:

```scala
package com.davisuga

import sttp.tapir.*

import Library.*
import cats.effect.IO
import io.circe.generic.auto.*
import sttp.tapir.generic.auto.*
import sttp.tapir.json.circe.*
import sttp.tapir.server.ServerEndpoint

object Endpoints:
  case class User(name: String) 
  val helloEndpoint: PublicEndpoint[User, Unit, String, Any] = endpoint.get
    .in("hello")
    .in(query[User]("name"))
    .out(stringBody)
  val helloServerEndpoint: ServerEndpoint[Any, IO] = helloEndpoint.serverLogicSuccess(user => IO.pure(s"Hello ${user.name}"))

  val booksListing: PublicEndpoint[Unit, Unit, List[Book], Any] = endpoint.get
    .in("books" / "list" / "all")
    .out(jsonBody[List[Book]])
  val booksListingServerEndpoint: ServerEndpoint[Any, IO] = booksListing.serverLogicSuccess(_ => IO.pure(Library.books))

  val apiEndpoints: List[ServerEndpoint[Any, IO]] = List(helloServerEndpoint, booksListingServerEndpoint)

  val all: List[ServerEndpoint[Any, IO]] = apiEndpoints

object Library:
  case class Author(name: String)
  case class Book(title: String, year: Int, author: Author)

  val books = List(
    Book("The Sorrows of Young Werther", 1774, Author("Johann Wolfgang von Goethe")),
    Book("On the Niemen", 1888, Author("Eliza Orzeszkowa")),
    Book("The Art of Computer Programming", 1968, Author("Donald Knuth")),
    Book("Pharaoh", 1897, Author("Boleslaw Prus"))
  )
  ```

I would like to create a graphql API without modifying any code inside `Endpoints` or rewriting

**Comment by kyri-petrou** [comment]
@davisuga I think your best option in this case is to convert the Cats-effect IO to ZIO using the `zio-cats-interop` library:

```scala
import zio.interop._
import zio.interop.catz._
import cats.effect.unsafe.implicits._
import cats.effect.std.Dispatcher

object WithoutDispatcher {
  // Uses global IORuntime, not recommended
  val io  = cats.effect.IO(42)
  val zio = liftIOInstance.liftIO(io)
}

class WithDispatcher(implicit dispatcher: Dispatcher[IO]) {
  val io  = cats.effect.IO(42)
  val zio = fromEffect(io)
}
```

**Comment by kyri-petrou** [comment]
~Actually this gave me an idea, I might be able to add support for interop with concrete IO in the caliban-interop module directly~

Edit: Nevermind me I was thinking of something irrelevant. My previous comment is still valid though

**Comment by ghostdogpr** [comment]
Ah, I understand your question now. The confusion comes from the fact that there are 2 things in the tapir module:
- the tapir adapter is a tapir endpoint that exposes the typical GraphQL GET and POST endpoints and can be used with various interpreters to expose your API
- the tapir "interop" allows you to reuse existing REST tapir endpoints and turn them into GraphQL

Your question is on the latter. There is currently only support for `ServerEndpoint` that wrap a `ZIO`, not a cats `IO`. However, I think you can add it easily by adapting the ZIO one.

Here's the one for ZIO:
```scala
implicit class GraphQLServerEndpoint[R, I, E, O](e: ServerEndpoint.Full[Unit, Unit, I, E, O, Any, ZIO[R, E, *]]) {
  def toGraphQL(implicit
    inputSchema: caliban.schema.Schema[R, I],
    outputSchema: caliban.schema.Schema[R, O],
    argBuilder: ArgBuilder[I]
  ): GraphQL[R] =
    tapir.toGraphQL(
      e.endpoint.serverLogic(input => 
        ZQuery.fromZIO(e.logic(monadError)(())(input).either.map(_.flatMap(identity)))
      )
    )
}
```
You could add the following for cats IO that transforms it into a ZIO:
```scala
import _root_.zio.interop._
import _root_.zio.interop.catz._
import _root_.sttp.tapir.integ.cats.effect.CatsMonadError

implicit val catsMonad: CatsMonadError[cats.effect.IO]              = new CatsMonadError[cats.effect.IO]
implicit val dispatcher: cats.effect.std.Dispatcher[cats.effect.IO] = ???

implicit class GraphQLServerEndpointCats[I, O](
  e: ServerEndpoint.Full[Unit, Unit, I, Throwable, O, Any, cats.effect.IO[*]]
) {
  def toGraphQL(implicit
    inputSchema: caliban.schema.Schema[Any, I],
    outputSchema: caliban.schema.Schema[Any, O],
    argBuilder: ArgBuilder[I]
  ): GraphQL[Any] =
    tapir.toGraphQL(
      e.endpoint.serverLogic(input =>
        ZQuery.fromZIO(fromEffect(e.logic(catsMonad)(())(input)).either.map(_.flatMap(identity)))
      )
    )
}
```

Note that you will need `tapir-cats-effect` for `CatsMonadError` as well as a `Dispatcher` for cats IO.

**Comment by davisuga** [comment]
> Ah, I understand your question now. The confusion comes from the fact that there are 2 things in the tapir module:
> 
> * the tapir adapter is a tapir endpoint that exposes the typical GraphQL GET and POST endpoints and can be used with various interpreters to expose your API
> * the tapir "interop" allows you to reuse existing REST tapir endpoints and turn them into GraphQL
> 
> Your question is on the latter. There is currently only support for `ServerEndpoint` that wrap a `ZIO`, not a cats `IO`. However, I think you can add it easily by adapting the ZIO one.
> 
> Here's the one for ZIO:
> 
> ```scala
> implicit class GraphQLServerEndpoint[R, I, E, O](e: ServerEndpoint.Full[Unit, Unit, I, E, O, Any, ZIO[R, E, *]]) {
>   def toGraphQL(implicit
>     inputSchema: caliban.schema.Schema[R, I],
>     outputSchema: caliban.schema.Schema[R, O],
>     argBuilder: ArgBuilder[I]
>   ): GraphQL[R] =
>     tapir.toGraphQL(
>       e.endpoint.serverLogic(input => 
>         ZQuery.fromZIO(e.logic(monadError)(())(input).either.map(_.flatMap(identity)))
>       )
>     )
> }
> ```
> 
> You could add the following for cats IO that transforms it into a ZIO:
> 
> ```scala
> import _root_.zio.interop._
> import _root_.zio.interop.catz._
> import _root_.sttp.tapir.integ.cats.effect.CatsMonadError
> 
> implicit val catsMonad: CatsMonadError[cats.effect.IO]              = new CatsMonadError[cats.effect.IO]
> implicit val dispatcher: cats.effect.std.Dispatcher[cats.effect.IO] = ???
> 
> implicit class GraphQLServerEndpointCats[I, O](
>   e: ServerEndpoint.Full[Unit, Unit, I, Throwable, O, Any, cats.effect.IO[*]]
> ) {
>   def toGraphQL(implicit
>     inputSchema: caliban.schema.Schema[Any, I],
>     outputSchema: caliban.schema.Schema[Any, O],
>     argBuilder: ArgBuilder[I]
>   ): GraphQL[Any] =
>     tapir.toGraphQL(
>       e.endpoint.serverLogic(input =>
>         ZQuery.fromZIO(fromEffect(e.logic(catsMonad)(())(input)).either.map(_.flatMap(identity)))
>       )
>     )
> }
> ```
> 
> Note that you will need `tapir-cats-effect` for `CatsMonadError` as well as a `Dispatcher` for cats IO.


That's great! thanks for the response.
Is it possible/easy to include security (the first 2 type parameters of ServerEndpoint.Full in your example)? It looks like the ZIO implementation does not work with endpoint security.
Almost all my endpoints have some kind of security. How difficult would it be to implement this?

**Comment by ghostdogpr** [comment]
> That's great! thanks for the response. Is it possible/easy to include security (the first 2 type parameters of ServerEndpoint.Full in your example)? It looks like the ZIO implementation does not work with endpoint security. Almost all my endpoints have some kind of security. How difficult would it be to implement this?

Endpoint security is currently not supported (only works with `Unit`). I just looked into it but I don't think it matches the current behavior well. Currently all "input" is converted into GraphQL arguments. But security input is typically passed using headers or cookies and it seems inappropriate to convert it into GraphQL arguments. But on the other hand a `GraphQL` object doesn't have any knowledge about headers since it's independent from the HTTP layer. So there's no easy fix for this, I think it requires re-thinking the whole approach.

**Comment by davisuga** [comment]
> > That's great! thanks for the response. Is it possible/easy to include security (the first 2 type parameters of ServerEndpoint.Full in your example)? It looks like the ZIO implementation does not work with endpoint security. Almost all my endpoints have some kind of security. How difficult would it be to implement this?
> 
> Endpoint security is currently not supported (only works with `Unit`). I just looked into it but I don't think it matches the current behavior well. Currently all "input" is converted into GraphQL arguments. But security input is typically passed using headers or cookies and it seems inappropriate to convert it into GraphQL arguments. But on the other hand a `GraphQL` object doesn't have any knowledge about headers since it's independent from the HTTP layer. So there's no easy fix for this, I think it requires re-thinking the whole approach.

Understood. Given that there's a String (jwt) => AuthData (jwt metadata and claims case class), how to implement authorization using tapir and Caliban? Some kind of external header parsing + resolver context?

**Comment by ghostdogpr** [comment]
> Understood. Given that there's a String (jwt) => AuthData (jwt metadata and claims case class), how to implement authorization using tapir and Caliban? Some kind of external header parsing + resolver context?

You can look at the various [examples](https://github.com/search?q=repo%3Aghostdogpr%2Fcaliban+AuthExampleApp+language%3AScala&type=code&l=Scala).
