### ISSUE TITLE
Derive operations schema from traits

### ISSUE THREAD

**Issue by Krever** [ghostdogpr/caliban#218]
Right now deriving schema for operations (queries, mutations, subscriptions) requires defining a case class in form of 
```
case class MyOpInput(p1: Int, p2: String)
case class Foo(myOp: MyOpInput => String)
```
which is slightly inconvenient because you need to define `MyOpInput` for each operation.
Instead, we could derive the schema from trait like this:
```
trait Foo {
  def myOp(p1: Int, p2: String): String
}
```
so we can scrap this one layer of boilerplate.
I think there are no technical limitations in general but it would require custom macro (or even macro annotation) instead of magnolia-based derivation.

**Comment by ghostdogpr** [comment]
The idea is nice but as you mentioned, Magnolia doesn’t allow doing this. If anyone has macro skills (I have zero) and want to give it a try, let us know 😄

**Comment by Krever** [comment]
Unfortunately, the amount of my macro experience is just the same. In case either of us or anyone else would like to give it a shot in the future I link below some examples of similar macros

1. cats-tagless derives FunctorK, so something that is able to transform all methods returning `F[_]` into methods returning `G[_]` when provided `F ~> G`: https://github.com/typelevel/cats-tagless/blob/master/macros/src/main/scala/cats/tagless/DeriveMacros.scala
2. autowire provides an RPC layer based on traits so something rather similar to what Caliban needs: https://github.com/lihaoyi/autowire/blob/master/autowire/shared/src/main/scala/autowire/Macros.scala

I understand nothing from this code though :)

**Comment by argson67** [comment]
Ask and ye shall receive :-)

**Comment by ghostdogpr** [comment]
Addressed by https://github.com/zio/caliban-deriving
