### ISSUE TITLE
Schema validation: interfaces

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#229]
In `Validator.validateSchema`, verify the [rules for interface types](https://spec.graphql.org/June2018/#sec-Interfaces)

1. An Interface type must define one or more fields.
2. For each field of an Interface type:
   1. The field must have a unique name within that Interface type;
      no two fields may share the same name.
   2. The field must not have a name which begins with the
      characters {"__"} (two underscores).
   3. The field must return a type where {IsOutputType(fieldType)}
      returns {true}.
   4. For each argument of the field:
      1. The argument must not have a name which begins with the
         characters {"__"} (two underscores).
      2. The argument must accept a type where {IsInputType(argumentType)}
         returns {true}.

**Comment by TobiasPfeifer** [comment]
I'd like to work on this

**Comment by TobiasPfeifer** [comment]
From the given rules its not 100% clear to me if empty names for fields and arguments are valid. Empty names don't make sense imo though. Other thoughts on this?

**Comment by ghostdogpr** [comment]
@TobiasPfeifer I don't think we need to check for empty names because they are derived from Scala case class parameters and those can't be empty anyway.

**Comment by ghostdogpr** [comment]
Closed by #243
