### ISSUE TITLE
Schema validation: unions

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#230]
In `Validator.validateSchema`, verify the [rules for union types](https://spec.graphql.org/June2018/#sec-Unions)

1. A Union type must include one or more unique member types.
2. The member types of a Union type must all be Object base types;
   Scalar, Interface and Union types must not be member types of a Union.
   Similarly, wrapping types must not be member types of a Union.

**Comment by palanga** [comment]
Can I take this ?
