### ISSUE TITLE
Schema validation: input objects

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#231]
In `Validator.validateSchema`, verify the [rules for input object types](https://spec.graphql.org/June2018/#sec-Input-Objects)

1. An Input Object type must define one or more input fields.
2. For each input field of an Input Object type:
   1. The input field must have a unique name within that Input Object type;
      no two input fields may share the same name.
   2. The input field must not have a name which begins with the
      characters {"__"} (two underscores).
   3. The input field must accept a type where {IsInputType(inputFieldType)}
      returns {true}.

**Comment by mriceron** [comment]
I can work on this if no ones is

**Comment by ghostdogpr** [comment]
@mriceron sure! 👍
