### ISSUE TITLE
Schema validation: directives

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#232]
In `Validator.validateSchema`, verify the [rules for directives](https://spec.graphql.org/June2018/#sec-Type-System.Directives)

1. A directive definition must not contain the use of a directive which
   references itself directly.
2. A directive definition must not contain the use of a directive which
   references itself indirectly by referencing a Type or Directive which
   transitively includes a reference to this directive.
3. The directive must not have a name which begins with the characters
   {"__"} (two underscores).
4. For each argument of the directive:
   1. The argument must not have a name which begins with the
      characters {"__"} (two underscores).
   2. The argument must accept a type where {IsInputType(argumentType)}
      returns {true}.

**Comment by spf3000** [comment]
I would like to attempt this

**Comment by javimartinez** [comment]
Working on this

**Comment by ghostdogpr** [comment]
Closed by #333
