### ISSUE TITLE
[Feature request] Support for feature toggle directives

### ISSUE THREAD

**Issue by lervag** [ghostdogpr/caliban#2348]
My organization has recently started to use feature flags/toggles with [Unleash](https://docs.getunleash.io/). We realize that it would probably be very nice to be able to use these toggles with the schema derivation. I.e. some way to specify that a certain field is only available given that a particular feature flag is active.

My first idea was something like `GQLOnFeatureEnabled(flag: String, ffImpl: FFImpl)`, where `FFImpl` is some relatively simple object that we can pass to determine if the passed flag is true or false. However, my understanding is that annotations like `@GQLExclude` are _compile time_ toggles. So, this initial idea may be hard or impossible to work within the core ideas of Caliban?

I was also curious if anyone has an experience with the use of feature flags/feature toggles with GraphQL APIs and in particular with Caliban. Perhaps there already exist similar solutions or best practises here?

**Comment by kyri-petrou** [comment]
@lervag just to clarify, do you want to be able to dynamically change the flag during runtime (after the application was initialized) or are you happy with the flag being determined once during the application initialization?

**Comment by lervag** [comment]
> do you want to be able to dynamically change the flag during runtime (after the application was initialized) or are you happy with the flag being determined once during the application initialization?

I want to be able to dynamically change the flag during runtime, yes.

However, I realize that I am also curious about strategies for using different _contracts_ (e.g. similar to the [Apollo contracts](https://www.apollographql.com/docs/graphos/delivery/contracts/)). But I think that's a tangent and I haven't investigated this within the Caliban/Scala community yet, so let's keep this thread about _dynamic_ feature toggles on the schema.

**Comment by kyri-petrou** [comment]
Interestingly, we already support a variant of contracts (via [schema transformations](https://ghostdogpr.github.io/caliban/docs/schema.html#schema-transformations))

I'm just thinking out loud, but assuming the number of feature flags is small, you could in theory create all possible permutations via Transformers, and then at the HTTP layer decide which schema you'll use. e.g., the ExampleApp under `example.quick` could be changed to something like this to do this:

```scala
package example.quick

import caliban._
import example.ExampleData._
import example.{ ExampleApi, ExampleService }
import zio._
import zio.http._

object ExampleApp extends ZIOAppDefault {
  override def run: ZIO[Any, Throwable, Unit] =
    ZIO
      .serviceWithZIO[GraphQL[Any]] { api =>
        val allFeatures     = QuickAdapter(api.interpreterUnsafe).handlers.api
        val disableFeatureA = QuickAdapter(api.transform(???).interpreterUnsafe).handlers.api
        val disableFeatureB = QuickAdapter(api.transform(???).interpreterUnsafe).handlers.api

        Routes(
          Method.GET / "api" / "graphql" -> handler((req: Request) =>
            if (???)
              disableFeatureA.runZIO(req)
            else if (???)
              disableFeatureB.runZIO(req)
            else {
              allFeatures.runZIO(req)
            }
          )
        ).serve[Any]
      }
      .provide(
        Server.defaultWithPort(8080),
        ExampleService.make(sampleCharacters),
        ExampleApi.layer
      )
}
```

This is not necessarily a great approach, and doesn't really solve the issue, but I think this is the best that we can do at this stage without rewriting the half of the library's internals :/

**Comment by ghostdogpr** [comment]
I think you could even create them dynamically with a `Ref[Map[Set[FeatureFlag], QuickAdapter]]`?

**Comment by kyri-petrou** [comment]
> I think you could even create them dynamically with a `Ref[Map[Set[FeatureFlag], QuickAdapter]]`?

Ah yeah that's a good point. Depending on the size of the schema, there might be a bit of a small delay the first time a new transformation is applied but that should be fairly minimal (assuming you're storing the transformed schema and reusing it afterwards)

**Comment by lervag** [comment]
> Interestingly, we already support a variant of contracts (via [schema transformations](https://ghostdogpr.github.io/caliban/docs/schema.html#schema-transformations))

Oh, thanks! This definitely resolves my curiosity about supporting different contracts.

> > I think you could even create them dynamically with a `Ref[Map[Set[FeatureFlag], QuickAdapter]]`?
> 
> Ah yeah that's a good point. Depending on the size of the schema, there might be a bit of a small delay the first time a new transformation is applied but that should be fairly minimal (assuming you're storing the transformed schema and reusing it afterwards)

My initial reaction is that this seems like a bad idea and that it would end up looking ugly. But I might be wrong.

In any case, I realize that my original idea is not really that important and does not really solve any immediate requirements or needs that I have. It will be more important to allow having a few contracts/versions, which seems to be well supported with the transformations.

----

Thanks both for quick and useful replies! I'll close the issue as resolved by the discussion.
