### ISSUE TITLE
Upgrade or remove zio-config

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#2371]
Currently we are using zio-config 3.x even though the latest version is 4.x. The problem is that 4.x removed the `CommandLine` source, which is the main reason we were using it (see https://github.com/zio/zio-config/releases/tag/v4.0.0-RC2).

We should either find a way to upgrade or remove that dependency so that we are not blocked in the future.

**Comment by paulpdaniels** [comment]
I can probably address this or provide guidance on upgrading if someone gets to it first. I just had to do something similar in a personal project.
