### ISSUE TITLE
Support creating graphiql endpoints for tapir based adapters 

### ISSUE THREAD

**Issue by calvinlfer** [ghostdogpr/caliban#2376]
Currently only the quick adapter provides the graphiql endpoint but the other (tapir based) adapters are left to the user to implement. 

It would be nice to provide graphiql endpoints to more adapters

**Comment by calvinlfer** [comment]
Should we create a graphiql module which exposes the [html method](https://github.com/ghostdogpr/caliban/blob/series/2.x/adapters/quick/src/main/scala/caliban/GraphiQLHandler.scala#L25-L92) that `quick` currently uses and then have all the dependencies depend on this module and expose the appropriate datatypes?

**Comment by ghostdogpr** [comment]
If it doesn't require any extra dependency I think it's okay to put it in core.
