### ISSUE TITLE
Support type system extensions in Parser

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#238]
Schema extensions will make the codegen commands fail. We need to add support for it in the parser.

See http://spec.graphql.org/June2018/#TypeSystemExtension

**Comment by jorge-vasquez-2301** [comment]
Hi @ghostdogpr I'd like to work on this as my first contribution 😃

**Comment by ghostdogpr** [comment]
@jorge-vasquez-2301 sure! Let me know if you need any help.
