### ISSUE TITLE
Serving GraphQL API with QuickAdapter no longer works with zio-http-v3.0.0-RC10

### ISSUE THREAD

**Issue by tymm** [ghostdogpr/caliban#2387]
I'm following the recipe from https://ghostdogpr.github.io/caliban/docs/adapters.html#usage to serve my GraphQL api via zio-http.
```
val api: GraphQL[Any] = ???

for {
    handlers  <- api.handlers
    // Alternatively, without imported syntax:
    handlers2 <- api.interpreter.map(QuickAdapter(_).handlers)
    // Creates a handler which serves the GraphiQL API from CDN
    graphiql = GraphiQLHandler.handler(apiPath = "/api/graphql", graphiqlPath = "/graphiql")
    app = Routes(
            Method.ANY / "api" / "graphql"     -> handlers.api,
            Method.GET / "graphiql"            -> graphiql,
            Method.POST / "upload" / "graphql" -> handlers.upload
            // Add more routes, apply middleware, etc.
          )
    _ <- app.serve[Any].provide(Server.defaultWithPort(8080))
} yield ()
```

The above worked with zio-http-v3.0.0-RC9 but no longer works with zio-http-v3.0.0-RC10 where http://localhost:8080/api/graphql returns a HTTP status code of 500.

**Comment by kyri-petrou** [comment]
Hi @tymm thanks for reporting. This is an issue with ZIO-HTTP breaking binary compatibility between RC9 and RC10.

Please refer to https://github.com/ghostdogpr/caliban/pull/2383 for more info. In short, we're waiting for v3.0.0 to be released (which should be next week) so that we break binary compatibility on our end just once

**Comment by tymm** [comment]
@kyri-petrou I updated to zio-http 3.0.0 and Caliban 2.9.0 but somehow the above problems persist.

**Comment by ghostdogpr** [comment]
Are you sure the versions are correct? You can check it with the `evicted` sbt task. If yes, can you provide more details on the error or ideally a reproducer? Our test suite is using these versions.

**Comment by tymm** [comment]
The correct versions are selected but after trying it out in a minimal example project things work with the new versions. So it must be something else. Thanks!
