### ISSUE TITLE
SchemaComparison ignores TypeExtension:s

### ISSUE THREAD

**Issue by joheriks** [ghostdogpr/caliban#2417]
`caliban.tools.SchemaComparison.compare` is a very useful tool for writing unit tests for code that produces and transforms schemas. However, it is currently limited by not checking extension definitions. For example:
```scala
  def run =
    val first = SchemaLoader.fromString( "extend type Query {a: Int}")
    val second = SchemaLoader.fromString("extend type Query {b: Int}")
    for
      diff <-
        SchemaComparison
          .compare(first, second)
          .mapError(SchemaComparisonErrorException.apply)
      _ <- ZIO.log(s"Expected non-empty diff: $diff")
    yield ()
```

Diff is empty but would expect two diffs on the `Query` type: 
*  field `b` has been added
*  field `a` has been deleted.

**Comment by ghostdogpr** [comment]
Yeah it would be a nice addition. Would you like to make a PR for it?
