### ISSUE TITLE
Invalid value too long string exceeded 'maxCharBufSize'

### ISSUE THREAD

**Issue by kaaveland** [ghostdogpr/caliban#2458]
I should probably be able to figure this one out on my own, but I haven't been able to. I'm getting this error for very long strings in graphql requests to my graphql api -- it's simply being returned as a 400 Bad Request. I would like to adjust jsoniters `maxCharBufSize`, which as far as I can tell, can be set in `ReaderConfig`:

https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/ReaderConfig.scala#L38

I could also provide by own instance to `JsonReader`: 

https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/js/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L36

Alternatively, perhaps set up caliban to use a different json library, although https://github.com/ghostdogpr/caliban/pull/2341 makes it seem like the project wants to avoid this in the future. 

Is there an easy way to convince caliban to accept strings that are a little longer?

**Comment by ghostdogpr** [comment]
Ah actually we did this for Caliban Client: https://github.com/ghostdogpr/caliban/pull/2085
I think we could do the same on the server side too. Wanna make a PR?

**Comment by kaaveland** [comment]
I'll take a stab at this 👍 

What's the right place to start, should I just start to looking for usages of `readFromString` in `core`?

**Comment by ghostdogpr** [comment]
So for the quick adapter that would be in `QuickRequestHandler` (look for `readFromString` and `readFromArray`). For the tapir-based adapters it's trickier because the decoding is done by Tapir, and I am not sure if they let you configure it. It requires some research (I see that when we import `sttp.tapir.json.jsoniter._`, it calls `TapirJsonJsoniter` so maybe we have to make a custom version of that).

**Comment by kaaveland** [comment]
It looks like doing something like this is fairly simple for the tapir adapters:
```scala

object MaxCharBufSizeJsonJsoniter extends TapirJsonJsoniter {
  override lazy val readerConfig: ReaderConfig =
    ReaderConfig
      .withAppendHexDumpToParseException(false)
      .withMaxCharBufSize(2147483645)
      .withMaxBufSize(2147483645)
}

```

Then just edit the imports. That's strictly speaking different than the way it was solved in the client package, but functionally similar (the buffer size error won't occur unless you send a DVD). Is that an acceptable solution, or do we need to be able to pass options to `ReaderConfig`?

**Comment by ghostdogpr** [comment]
Sounds acceptable!

**Comment by ghostdogpr** [comment]
Closed by https://github.com/ghostdogpr/caliban/pull/2459
