### ISSUE TITLE
Generate graphql interface from non-sealed trait

### ISSUE THREAD

**Issue by hostgaard** [ghostdogpr/caliban#2469]
Hello,

I am trying to implement error handling using the pattern from this [LogRocket example](https://blog.logrocket.com/handling-graphql-errors-like-a-champ-with-unions-and-interfaces/).

To get Caliban to generate the correct graphql schema we need something like this:
```scala
@GQLInterface
sealed trait Error {
  val message: String!
}

case class User(name: String)

sealed trait GetUserResult
case class GetUserPayload(user: User) extends GetUserResult
case class SomeError(message: String) extends GetUserResult with Error
case class SomeOtherError(message: String, moreInfo: Option[String]) extends GetUserResult with Error

val errorSchema: Schema[Any, Error] = Schema.gen

case class Query(getUser: GetUserResult)
val gql = graphQL(RootResolver(queryResolver = Query(getUser = User("foo"))))
  .withAdditionalTypes(List(errorSchema.toType_()))
```

which produces the following schema:

```graphql
schema {
  query: Query
}

union GetUserResult = GetUserPayload | SomeError | SomeOtherError

interface Error {
  message: String!
}

type User {
  name: String!
}

type Query {
  getUser: GetUserResult!
}

type SomeError implements Error {
  message: String!
}

type SomeOtherError implements Error {
  message: String!
  moreInfo: String
}
```

Which is really nice. However, since our api has grown quite a bit we have split our graphql types across several files and packages. This of course makes it impossible to have a common sealed `Error` trait. When I try to make it non sealed the schema derivation fails, and I guess it is because the compiler does not provide a `Mirror` for non sealed traits.

So I was wondering if this is even possible in our situation? Or do we have to put all our result types in the same file?

Related: https://github.com/ghostdogpr/caliban/issues/2397

**Comment by ghostdogpr** [comment]
There's a way to cheat that: look for `@GQLValueType` in this page: https://ghostdogpr.github.io/caliban/docs/schema.html#enums-unions-interfaces

That lets you create an Error supertype that has members that don't directly extend it.

See this example: https://scastie.scala-lang.org/fuIVLHdpQyeeLJcOrYqcgQ

**Comment by hostgaard** [comment]
Ok, thank you, I didn't realize that was applicable for my use case. But we still need to have all error types in the same file, correct? For example:

```scala
// File ErrorTypes.scala

@GQLInterface
sealed trait Error {
  val message: String
}

case class SomeUserRelatedError(message: String) extends Error
```

```scala
// File UserQueries.scala

case class User(user: String)

sealed trait GetUserResult
case class GetUserPayload(user: User) extends GetUserResult
@GQLValueType case class SomeUserRelatedErrorWrapper(value: SomeUserRelatedError) extends GetUserResult
```

**Comment by ghostdogpr** [comment]
Your case is a little tricky because you have both an interface and a union but I think both of them can use @GQLValueType. You will need a file with all the error wrappers but the errors can be elsewhere.

**Comment by hostgaard** [comment]
Yeah, I see. This workaraound works for us I think. Thank you!
