### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by user753** [ghostdogpr/caliban#283]
```
implicit val runtime = Runtime.unsafeFromLayer(Console.live ++ Clock.live)
```
There isn't `unsafeFromLayer`, `Console.live`, `Click.live`

**Comment by ghostdogpr** [comment]
Ah, this is because the master branch is using the new ZIO RC18 but I didn't release caliban with it yet (I'll probably release tomorrow). If you use caliban 0.6.0, you can look at the examples at the time of tag 0.6.0: https://github.com/ghostdogpr/caliban/tree/v0.6.0/examples
