### ISSUE TITLE
Support recursive types

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#3]

**Comment by valentin-panalyt** [comment]
@ghostdogpr Does this issue mean that recursive schemas won't be supported? I have a recursive one that derives a wrong schema.

```
sealed trait RecursiveType
...
case class NestedType(value: List[RecursiveType]) extends RecursiveType
```

Interestingly it derives a schema where the `value` field is of type `ListRecursiveType` with `::` and `Nil` as members, so apparently `List` didn't get derived correctly but as a "normal" sealed trait.

Will this not be supported?
