### ISSUE TITLE
Codegen: add options to sbt command

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#322]
Add an option to specify headers when using a URL. Also make the scalafmt path an option.

The current code isn't very convenient for dealing with options, maybe use something like https://github.com/scopt/scopt?

**Comment by joprice** [comment]
This one is nice too https://github.com/alexarchambault/case-app

**Comment by ghostdogpr** [comment]
@joprice thanks. Anything is fine, since it's for the codegen tool we don't need to worry about transitive dependencies 😄

**Comment by kiranbayram** [comment]
I can give this a go if nobody else is working on it

**Comment by ghostdogpr** [comment]
@kiranbayram awesome! In addition to the libraries mentioned above, zio-config also supports command-line arguments: https://zio.github.io/zio-config/docs/sources/sources_index#command-line-arguments. It might be a good choice considering we already depend on zio.

**Comment by kiranbayram** [comment]
Thanks for the hint @ghostdogpr , i'll try to use `zio-config` 👍
