### ISSUE TITLE
Codegen: make it usable without sbt

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#326]
Move the sbt-specific code to a new module `caliban-codegen-sbt` and make `caliban-codegen` a regular module that can be used without sbt.

**Comment by joprice** [comment]
I did this here https://github.com/ghostdogpr/caliban/pull/327. I haven't published locally yet to test yet. Looks like there's no scripted tests integrated. Is there an example project that I should modify to test it?

**Comment by ghostdogpr** [comment]
I usually use https://github.com/ghostdogpr/caliban-blog-series for testing this.
