### ISSUE TITLE
Add maxBatchSize support

### ISSUE THREAD

**Issue by hepin1989** [ghostdogpr/caliban#336]
Then when do an auto batching, Caliban can do a grouped call first.
Below is what I did in our internal java implementation.
![image](https://user-images.githubusercontent.com/501740/79685759-ba7cab00-826d-11ea-8b9f-051f7491b8db.png)

**Comment by adamgfraser** [comment]
I will work on this.

**Comment by ghostdogpr** [comment]
Closing since ZQuery moved to another repo.

**Comment by hepin1989** [comment]
So this will be implemented in ZQuery?

**Comment by ghostdogpr** [comment]
Yeah, I just created an issue for it so you can track it: https://github.com/zio/zio-query/issues/46

**Comment by adamgfraser** [comment]
@hepin1989 Just submitted a PR to add this [here](https://github.com/zio/zio-query/pull/47).
