### ISSUE TITLE
GenericSchema doesn't seem to work with Generic Types

### ISSUE THREAD

**Issue by carlminden** [ghostdogpr/caliban#343]
I am trying to get a project set up using caliban and I wanted to be able to abstract out some of the Api and Service logic so that I could have different implementations of these pieces for each object in my data model.

To test this out I started building a simple "blog" app just to see if I could get things hooked up the way I wanted, when I set it up with a single model everything worked fine, but when I tried to make the  API generic, the schema generation seems to break down. I've tried to make the simplest example showing the issue:

this works:

```
class PostService {
  def getPosts(): UIO[List[Post]] = {
    UIO.succeed(List(Post(1)))
  }
}

class Api extends GenericSchema[Has[PostService]] {

  case class PostQueries(
    @GQLDescription("Return all posts")
    posts: Unit => URIO[Has[PostService], List[Post]] = _ => URIO.accessM(service => service.get.getPosts())
  )

  def api(): GraphQL[Console with Clock with Has[PostService]] =
    GraphQL.graphQL(
      RootResolver(
        PostQueries()
      )
    )
}
```

but this doesn't work:

```
class PostService {
  def getPosts(): UIO[List[Post]] = {
    UIO.succeed(List(Post(1)))
  }
}

class Api[T] extends GenericSchema[Has[T]] {

  case class PostQueries(
    @GQLDescription("Return all posts")
    posts: Unit => URIO[Has[PostService], List[Post]] = _ => URIO.accessM(service => service.get.getPosts())
  )

  def api(): GraphQL[Console with Clock with Has[T]] =
    GraphQL.graphQL(
      RootResolver(
        PostQueries()
      )
    )
}
```

In the generic example I get the following error:

```
Error:(28, 35) Cannot find a Schema for type Api.this.PostQueries.
     Caliban derives a Schema automatically for basic Scala types, case classes and sealed traits, but
     you need to manually provide an implicit Schema for other types that could be nested in Api.this.PostQueries.
     If you use a custom type as an argument, you also need to provide an implicit ArgBuilder for that type.
     See https://ghostdogpr.github.io/caliban/docs/schema.html for more information.
  implicit val schema = implicitly[Schema[Console with Clock with Has[T], PostQueries]]
```

I've tried explicitly asking for a schema to be generated with the "gen" method, but that also fails with:

```
Error:(27, 28) magnolia: could not find Schema.Typeclass for type zio.ZIO.Adopt
    in coproduct type zio.URIO[zio.Has[framework.PostService],List[post.Post]]
    in chained implicit Schema.Typeclass for type zio.ZIO.Adopt
    in coproduct type zio.URIO[zio.Has[framework.PostService],List[post.Post]]
    in chained implicit Api.Typeclass for type zio.ZIO.Adopt
    in coproduct type zio.URIO[zio.Has[framework.PostService],List[post.Post]]
    in chained implicit Schema.Typeclass for type zio.ZIO.Adopt
    in coproduct type zio.URIO[zio.Has[framework.PostService],List[post.Post]]
    in chained implicit Api.Typeclass for type Unit => zio.URIO[zio.Has[framework.PostService],List[post.Post]]
    in parameter 'posts' of product type Api.this.PostQueries
  implicit val schema = gen[PostQueries]
```

or if I try to run "gen" on the generic type T I get:

```
Error:(27, 28) magnolia: could not infer Api.Typeclass for type T
  implicit val schema = gen[T]
```

Is what I am trying to do not possible? is there a better way?

**Comment by ghostdogpr** [comment]
Hi! I am not sure I clearly understand what you are trying to achieve.

If you want your schema to require a generic `Has[T]`, your query field can't return `Has[PostService]`. You would have to make the case class generic too and wouldn't be able to give an implementation if T is unknown.

But is your goal just to have different implementations of `getPosts`? If so, you can simply create a `trait PostService` that you use in your schema, and use `provideLayer` to give the proper implementation class at runtime.

Feel free to come chat on Discord if you'd like.

**Comment by ghostdogpr** [comment]
Closing now but feel feee to reopen or reach out on Discord if you’d like to discuss more.
