### ISSUE TITLE
Masking parts of the schema based on permissions

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#344]
This was suggested on Discord. I don't think it is possible in the current state to hide some parts of the schema during introspection.

**Comment by ghostdogpr** [comment]
Related discussion: https://github.com/graphql/graphql-js/issues/113

**Comment by paulpdaniels** [comment]
I'd probably file this under providing some more flexibility around introspection, maybe just allowing access to it through something like the wrapper mechanism, I don't know if the case of hiding introspection based on user roles is really super compelling or even really necessary in most cases. I think Lee's points are fairly compelling to that end.

**Comment by ghostdogpr** [comment]
A type of wrapper that only applies to introspection, that's an idea 🤔

**Comment by ghostdogpr** [comment]
`IntrospectionWrapper` was added in #753
