### ISSUE TITLE
Variables in Subscription

### ISSUE THREAD

**Issue by mitsutaka-takeda** [ghostdogpr/caliban#348]
Hi. Thank you for the great library! 

I started playing around with caliban and  tried to use a variable in my subscription query like this one.

```graphql
subscription OnEvent($topic: String!) {
    onEvent(topic: $topic) {
        name
    }
}
```

But caliban fails to execute query because it can not resolve the variable "$topic". I checked the WebSocket message and it contains variable definitions as expected.

```json
{
  "id": "1",
  "type": "start",
  "payload": {
    "variables": {
      "topic": "mytopic"
    },
    "extensions": {},
    "operationName": "OnEvent",
    "query": "subscription OnEvent($topic: String!) { onEvent(topic: $topic) {name}}"
  }
}
```

The code for Http4sAdapter ignores the variables in payload is this intentional?

https://github.com/ghostdogpr/caliban/blob/dac5817f687479493e2a200dee2e5fa214411247/adapters/http4s/src/main/scala/caliban/Http4sAdapter.scala#L178

When I change the line to something like this it can execute a query

```scala
val payload = msg.hcursor.downField("payload")
val id = msg.hcursor.downField("id").success.flatMap(_.value.asString).getOrElse("")
Task.whenCase(payload.as[GraphQLRequest]) {
   case Right(req) =>
       (for {
          result <- interpreter.execute(req.query.get, req.operationName, req.variables.getOrElse(Map.empty), req.extensions.getOrElse(Map.empty), skipValidation = skipValidation)
```

**Comment by ghostdogpr** [comment]
Hi! This is definitely not intentional, good catch 😄 Would you like to submit a PR to fix it? I’m guessing the problem might exist on all adapters that support WebSockets (that’s be http4s, Akka and uzhttp).
