### ISSUE TITLE
Codegen for server: conflict between argument case classes

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#367]
With the following schema:
```
schema {
  query: Queries
}

type Post {
  similar(limit: Int!, offset: Int): [Post!]!
}

type Queries {
  users: [User!]!
  posts: [Post!]!
}

type User {
  similar(limit: Int!): [User!]!
}
```
SchemaWriter will generate 2 case classes named `SimilarArgs` that clash with each other.

**Comment by asachdeva** [comment]
@ghostdogpr I can work on this...unless its been picked up?

**Comment by ghostdogpr** [comment]
@asachdeva Sure, you can take it. Thank you!

**Comment by ghostdogpr** [comment]
@asachdeva any news about this one? Should someone else pick it? Thanks 😄

**Comment by asachdeva** [comment]
@ghostdogpr sorry for the delay on this...started a couple of new jobs and have been swamped with life.  I can work on this Monday of next week but if someone else is willing and able ...please assign away

**Comment by ghostdogpr** [comment]
@asachdeva no problem! There's a PR for it now 😄
