### ISSUE TITLE
Is there a way to diff two GraphQL schemas?

### ISSUE THREAD

**Issue by tovbinm** [ghostdogpr/caliban#372]
Such feature is quite important for versioning the GraphQL schemas, when one would like to compare the differences between two schema versions.

**Comment by ghostdogpr** [comment]
@tovbinm a couple questions to help me figure out how it should look like:
- do you see that as a method you can call from your own code or as a tool? (like the codegen sbt plugin)
- where would the schemas come from? introspection from URLs? or your own code (but that would mean keeping both versions)?

**Comment by paulpdaniels** [comment]
I would think HEAD vs a remote schema would be the most reasonable, though that is just for our CI setup. Apollo-cli tools have something similar as well that we could look to for inspiration.

**Comment by tovbinm** [comment]
@ghostdogpr I would like to be able to use it from the code. Currently we use a service with a GraphQL API that serves our schema version N with tens of thousands of types. The service supports schema merging (upserting). Currently when we change the schema to version N+1 we upload the whole schema to the service, but it takes significant amount of time to merge between them. Since the majority of the types are unchanged, we would like to only upload the delta to improve the performance.

**Comment by javimartinez** [comment]
In my opinion, it'd be nice to have both:
* Methods that we can use in the code:

    Maybe something similar to https://sangria-graphql.org/learn/#schema-comparison. With that, we can cover  @tovbinm 's use case, and also it'd possible to identify the breaking changes and generate the release notes. 

* A tool (sbt plugin) which can be used in the CI. Besides the above features, it could have the ability to validate schemas.

**Comment by ghostdogpr** [comment]
That sounds very similar to `caliban-codegen` and `caliban-codegen-sbt`. These modules already depends on both caliban client and server and contain the code to introspect by URL. Maybe we just rename them `caliban-tools` and `caliban-tools-sbt`?

**Comment by javimartinez** [comment]
Yes, it makes sense for me

**Comment by ghostdogpr** [comment]
I started working on this and now have a common format for a schema whether it’s coming from a graphql IDL file, a remote introspection or a caliban `GraphQL` object. What’s remaining is the actual diff. 

What are your thoughts regarding the output? One option is to use something generic like diffx that compares 2 case classes with some pretty colorful rendering. Another way would be to have a custom ADT with precise types such as `FieldAdded`, `TypeDeleted`, etc.

**Comment by paulpdaniels** [comment]
I prefer the custom ADT, since I think it would be easier to build tooling off of that and there is a precedent with how the apollo-tools or sangria does it as well.

**Comment by javimartinez** [comment]
I'll bet for a custom ADT too. We can interpret it in different ways, more flexibility, etc.

**Comment by ghostdogpr** [comment]
Thanks for the feedback, will do that!

**Comment by ghostdogpr** [comment]
Opened a PR, feedback welcome: https://github.com/ghostdogpr/caliban/pull/436#discussion_r436341163
