### ISSUE TITLE
Wrong type of field in interface

### ISSUE THREAD

**Issue by szymonrodziewicz** [ghostdogpr/caliban#404]
I have a following case class structure:
```
...
  @GQLInterface
  sealed trait Q {
    def foo: String
    def bar: String
  }

case class A(
    foo: String,
    bar: String,
    problematicField: ResponseIO[SomeType]
  ) extends Q

  case class B(
    foo: String,
    bar: String,
    problematicField: ResponseIO[List[SomeType]]
  ) extends Q

  case class C(
    foo: String,
    bar: String,
    problematicField: ResponseIO[String]
  ) extends Q
...
```
I use it to generate my GraphQL schema. `ResponseIO` is a wrapper for ZIO type. It results in a schema that has a ` problematicField: [SomeType!]` in the Question interface:
```
interface Q {
  foo: String!
  bar: String
  problematicField: [SomeType!]
}
```
 It seems like it was trying to incorrectly optimise the schema and pull answer type to Q interface, despite them having different type arguments - at one case it's a String, in other List of objects and in the latter one a single object.

I'm using Scala 2.12 with caliban 0.7.8.

**Comment by ghostdogpr** [comment]
Thanks for the report. The reason for this optimization is that Magnolia doesn’t give access to the fields of the interface trait, so we find ourselves what are the fields in common in the subtypes. We should definitely add a check to only take fields that return the same type (here: https://github.com/ghostdogpr/caliban/blob/af23ac346759c27612186c0106a44dc40d3a1f2d/core/src/main/scala/caliban/schema/Schema.scala#L409).

**Comment by ghostdogpr** [comment]
I'll get this one fixed during the weekend, but if anyone wants to jump on it earlier, let me know. It should be an easy one.

**Comment by joprice** [comment]
> Magnolia doesn’t give access to the fields of the interface trait

 It seems like there's still going to be issues even if you fix it to handle differing types. I haven't used interfaces yet, but am going to be experimenting with Relay, where e.g., according to the spec, the interface for Node must contain only one field called "id". If every object happens to also have a field `name: String`, does that mean Node will acquire that as well? If so, maybe the fix demands going outside of magnolia and writing a custom macro that can grab the interface fields?

**Comment by ghostdogpr** [comment]
I’d prefer staying away from more macros. Maybe the annotation could take some optional parameters allowing you to specify the field names to take.
