### ISSUE TITLE
Use scala-steward?

### ISSUE THREAD

**Issue by takayahilton** [ghostdogpr/caliban#42]
**Description**
>Scala Steward is a robot that helps you keeping library dependencies and sbt plugins up-to-date.

https://github.com/fthomas/scala-steward

All you have to do is edit this [repos](https://github.com/scala-steward-org/repos/edit/master/repos.md) and send PR.

**Comment by ghostdogpr** [comment]
Definetely, I already did it in the past for a couple projects. Will add it there.

**Comment by ghostdogpr** [comment]
https://github.com/scala-steward-org/repos/pull/37

**Comment by ghostdogpr** [comment]
Done
