### ISSUE TITLE
Add support for application/graphql content type

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#420]
From https://graphql.org/learn/serving-over-http/:

> If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

To be done in each adapter:
- [x] http4s
- [x] akka http
- [x] finch
- [ ] play

**Comment by ghostdogpr** [comment]
If anyone wants to work on this, you can totally do one adapter only, no need to do all at once😄

**Comment by dgeyer-mdsol** [comment]
Hi 👋  I would like to pick up this ticket for the hackathon, I see play is the only one pending, am I right?

**Comment by ghostdogpr** [comment]
@dgeyer-mdsol This is right, we only need to add it in the Play Adapter. You can have a look at the other PRs linked here to see how it was added to the other adapters. Let me know if you have any question 😄
