### ISSUE TITLE
Support "query" query string parameter in POST endpoint 

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#421]
From https://graphql.org/learn/serving-over-http/:

> If the "query" query string parameter is present (as in the GET example above), it should be parsed and handled in the same way as the HTTP GET case.

To be done in each adapter:
- [x] http4s
- [x] akka http
- [x] finch
- [ ] play

**Comment by ghostdogpr** [comment]
If anyone wants to work on this, you can totally do one adapter only, no need to do all at once😄

**Comment by jessenr** [comment]
I'll take the play adaptor.
