### ISSUE TITLE
Schema derivation doesn't handle nested types

### ISSUE THREAD

**Issue by kiranbayram** [ghostdogpr/caliban#425]
Hello there, as already discussed in Discord, opening the issue here:
```
@ final case class ApiTranslated[T](value: T )
defined class ApiTranslated

@ case class Data2(a: ApiTranslated[Option[Double]], b: ApiTranslated[Option[Int]])
defined class Data2

@ val data2 = Data2(ApiTranslated(Some(1.0)), ApiTranslated(Some(5)))
data2: Data2 = Data2(ApiTranslated(Some(1.0)), ApiTranslated(Some(5)))

@ GraphQL.graphQL(RootResolver(data2))
res44: GraphQL[Any] = caliban.GraphQL$$anon$5@1ef8f1ca

@ res44.render
res45: String = """schema {
  query: Data2
}

type ApiTranslatedOption {
  value: Float
}

type Data2 {
  a: ApiTranslatedOption!
  b: ApiTranslatedOption!
}
```

Second field's(`Data2.b`) type is ApiTranslated[Option[Int]] but it's mapped to Float in schema

**Comment by ghostdogpr** [comment]
The problem comes from https://github.com/ghostdogpr/caliban/blob/master/core/src/main/scala/caliban/schema/Schema.scala#L456
Instead of just taking the type argument names `typeName.typeArguments.map(_.short)`, we could call the same function recursively to get the full name.
