### ISSUE TITLE
Schema validation does not allow for ZQuery in interface

### ISSUE THREAD

**Issue by WojciechMazur** [ghostdogpr/caliban#442]
In case when sealed trait annotated with `GQLInterface` defines field taking ZQuery it does not pass schema validations with exception 
`Interpreter error: Field 'foo' in Object 'FooBar1' is an invalid subtype - An object field type must be equal to or a possible type of the interface field type`
It's a downgrade since version 0.8.0, on which there were no such problems. 

Example
```
@GQLInterface
sealed trait Foo {
    def foo: ZQuery[Env, Err, T]
}

case class FooBar1(
    foo: ZQuery[Env, Err, T]
) extends Foo
```

**Comment by ghostdogpr** [comment]
Would you able to test with the latest master? I fixed a related issue a couple days ago, it may have fixed this too.

**Comment by ghostdogpr** [comment]
FYI this is the PR that should have fixed it: #440
I am planning to do a new release this weekend, if you can confirm the fix works in your case it would be awesome.

**Comment by WojciechMazur** [comment]
It works on build from master branch in my case.

**Comment by ghostdogpr** [comment]
Thanks for the confirmation! I’ll release tomorrow.
