### ISSUE TITLE
Codegen: support custom scalar mapping

### ISSUE THREAD

**Issue by paulpdaniels** [ghostdogpr/caliban#453]
We should add the ability to do type to scalar mappings when running the client code generation.
If one of the mappings is not present the generation would fail. This would be useful in scenarios where we want to create a CI tool that builds the client after every server release.

```bash
// Encode the map similar to a CURL request, where the classes are fully specified.
// built in types have default handling (could think of another way to support alternative decoders)
// Multiple declarations of `--scalarMappings` would create leftward merge
--scalarMappings='{"JSON": "io.circe.Json", "Other": "Int"}'
```

We could also allow passing in a filename for `scalarMappings` which would look for types with an annotations perhaps i.e.

```scala
@ScalarType("Json")
case class JsonAdt(...)

// Note the required decoder so that we could derive a `ScalarDecoder`
object JsonAdt {
 implicit val decoder: Decoder[JsonAdt] = ???
}


```

**Comment by AlixBa** [comment]
I would add two options. The first one to map scalars to types (and vice-versa), and the other one to fail or pass if a mapping is not found. We currently use a package object with the same package as the codegen where we define type aliases for graphql scalars. But I guess that sometimes you can not just rely on type alias so not failing at codegen phase would be appreciable. wdyt?

**Comment by paulpdaniels** [comment]
> But I guess that sometimes you can not just rely on type alias so not failing at codegen phase would be appreciable

Yes that seems reasonable for non-CI cases where you are using the codegen as a starting point. Though I'm wondering if would get used a lot, since in most cases it might be quicker to just generate it broken, then fix it yourself since you'd presumably have your IDE/compiler to help you at that point.

**Comment by ghostdogpr** [comment]
Maybe a simpler solution could be to just pass an optional `import` to add to the generated file, so that you could define the type aliases as well as the required `ScalarDecoder` in that file?
