### ISSUE TITLE
Upgrade to ZIO RC21

### ISSUE THREAD

**Issue by paulpdaniels** [ghostdogpr/caliban#456]
The following dependencies need to be upgraded and released first:

- [x] [zio-query](https://github.com/zio/zio-query/pull/65) (critical issue found in ZIO)
- [x] [zio-interop-cats](https://github.com/zio/interop-cats/pull/195)
- [x] [zio-interop-reactive-streams](https://github.com/zio/interop-reactive-streams/pull/135)
- [X] [zio-config](https://github.com/zio/zio-config/pull/361)
- [X] [sttp](https://github.com/softwaremill/sttp/pull/606)
- [x] [uzhttp](https://github.com/polynote/uzhttp/pull/30)

**Comment by ghostdogpr** [comment]
Closed by #472
