### ISSUE TITLE
UIO / URIO field failures are not available in interpreter mapError

### ISSUE THREAD

**Issue by amiralies** [ghostdogpr/caliban#462]
to make it simple aussme that we got a resolver which is returning something like this
```scala
ZIO.fromFuture { ec => 
  Future.failed(new Exception("myerror"))
}.orDie
```
It seems like the exception is not passed through interpreter mapError, It just creates error message in response (`java.lang.exception myerror`).

Note that if i omit orDie and use Task instead of UIO it will be passed through mapError. but makes my field type Optional which is not what I want.

**Comment by ghostdogpr** [comment]
@amiralies You're totally right, thanks for raising this. I just opened a PR for fixing this, which also improves the error you get (providing error path and location): https://github.com/ghostdogpr/caliban/pull/463
