### ISSUE TITLE
calibanGenSchema does not escape double quote in GQLDescription

### ISSUE THREAD

**Issue by MasseGuillaume** [ghostdogpr/caliban#476]
I'm generating the schema for the Shopify API and they have double quotes in their descriptions.

Caliban generates the following code:

obtained

```scala
case class Location(
// ...
deactivatable: Boolean, @GQLDescription("Date and time the location was deactivated (null if location is still active). Following UTC ISO8601 format, e.g.: "2019-04-24T13:42:24Z".")
// ...
)
```

expected:

```scala
case class Location(
// ...
deactivatable: Boolean, @GQLDescription("Date and time the location was deactivated (null if location is still active). Following UTC ISO8601 format, e.g.: \"2019-04-24T13:42:24Z\".")
// ...
)
```

A similar issue happens in `calibanGenClient` with `@deprecated`.

**Comment by ghostdogpr** [comment]
Good finding!

We have some logic to use triple quotes when there is a \n, maybe we can extend it to cover this case too: https://github.com/ghostdogpr/caliban/blob/046b3a075b581b62023a8f0b92d8dd6ae99cb525/tools/src/main/scala/caliban/tools/SchemaWriter.scala#L171

In ClientWriter it's not handled at all.

**Comment by MasseGuillaume** [comment]
With quasiquotes, you can get these pretty-printing rules and have the safely construct valid scala code.

```scala
import scala.meta._

val description = """Quoted "2019-04-24T13:42:24Z"."""
val descriptionLit = Lit.String(description)
val descriptionAnnotation = List(mod"""@GQLDescription($descriptionLit)""")

q"""
object A {
  ..$descriptionAnnotation
  def f = 1
}
""".syntax
```

https://scastie.scala-lang.org/26nmiyc3RIih5C5OUaTq4w
