### ISSUE TITLE
Task query result is optional

### ISSUE THREAD

**Issue by user753** [ghostdogpr/caliban#477]
```
  case class Query(
    foo: () => Task[Int],
  )

  val api =
    graphQL(
      RootResolver(
        Query(
          () => Task.succeed(1),
        )))
```
```
type Query {
  foo: Int
}
```
I thinks `foo` should be `Int!` and for `Int` `Task[Option[Int]]` should be used.
Is there another way to remove optional when Task result is used?

**Comment by ghostdogpr** [comment]
To express the 2 possible desired behaviors on errors, we rely on the 2 error channels of ZIO:
- failures in the E error channel are mapped to null and won’t prevent the rest of the query from being executed
- failures in the Die error channel will fail the whole query

If you want the latter, you can change your type to `UIO` and call `.orDie` on your effect.
