### ISSUE TITLE
Connection leak in AkkaHttpAdapter websocket connection when client forcibly closes

### ISSUE THREAD

**Issue by moonkev** [ghostdogpr/caliban#482]
Hello

I believe I may have identified a connection leak in AkkaHttpAdapter when using subscriptions with the websocket endpoint.  This issue only happens when the client abruptly closes without initiating the proper subscriptions-transport-ws termination sequence.  

The issue I see is that the sink side (input from the client) will die, but the source side streaming to the client stays alive perpetually.  They are bridged into a flow using `fromSinkAndSource` here https://github.com/ghostdogpr/caliban/blob/master/adapters/akka-http/src/main/scala/caliban/AkkaHttpAdapter.scala#L193 .  Depending on how much data one is streaming down the subscription, or if they have keep-alive enabled via the keepAliveTime param to makeWebSocketService the Source.queue will eventually overflow and fail, terminating the connection and the associated ZStream.  

However, an issue I ran into, is that my ZStream is performing heavy computation, and it is also bridging subscriptions from a bi-direction GRPC stream, yet I only send data down stream on conditions which may net be met for several minutes.  In the even that a client abruptly closes the connection, this could keep this ongoing for hours unless I have a very aggressive keep-alive set.  However, even this is not exactly ideal as when the Source.queue overflows, it will die with a nasty error that cannot easily be controlled.  However, most clients will unfortunately just close their browser before cleanly terminating a connection.

A solution I believe would be to change the call to merge the sink and source into a flow from `fromSinkAndSource` to `fromSinkAndSourceCoupled`.  This will cause the resultant flow to terminate the stream completely if either the sink or source side fail.  I made this change locally and tested several times terminating the connection abruptly and also normally.  I wrapped the components of my connected stream with some logging for proper shutdown, and can verify that they are cleanly terminated.  If you agree this is the correct change to make, I will happily open a PR.  If you can think of any other scenario you would like me to verify, I'm happy to do that as well.  Thanks for the great work by the way!

**Comment by ghostdogpr** [comment]
Wow, thanks for the detailed analysis. Your solution sounds like the right way to go, a PR would be welcome!

**Comment by ghostdogpr** [comment]
Closed by #483
