### ISSUE TITLE
Problem with deriving schema for type tree with two traits as union and interface

### ISSUE THREAD

**Issue by szymonrodziewicz** [ghostdogpr/caliban#492]
Hi, I have encountered an error with the Schema generation and succeeded in reproducing it. The Schema is defined as follows:

```scala
  case class C(c: A)

  @GQLInterface
  sealed trait A {
    def a: Int
    def z: C
  }

  sealed trait B

  case class A1(a: Int, z: C) extends A
  case class B1(a: Int, b: Int, z: C) extends A with B
  case class B2(a: Int, b: Int, z: C) extends A with B

  case class Mutation(
    a: Int => A1,
    b: Int => B,
)
```

It results in the following Schema:

```
interface A {
  a: Int!
  z: C!
}

type A1 {
  a: Int!
  z: C!
}

union B = B1 | B2
type B1 implements A {
  a: Int!
  b: Int!
  z: C!
}
​
type B2 implements A {
  a: Int!
  b: Int!
  z: C!
}
​
type C {
  c: A!
}
```

The important part here is that `A1` doesn't implement `A` interface in the generated schema - despite specifying that A1 implements A in Scala code. While reproducing this error I've experimented a bit and I may've got some idea about this issue that may help you resolve it. If I introduce a mutation that uses `A` type before other mutations in `Mutation` case class, the issue is fixed and A1 derives from A. And by `before` I mean introducing it as a first field in Mutation object - order is important here. Moreover, explicitly writing something like `implicit val xyz = gen[A]` or `implicit val xyz = gen[A1]` doesn't help at all. From my understanding, the reason for all this is that the type `A` is derived after type `A1` (after deriving nested `C`), and all that while deriving the `Mutation` type. What I ended up doing in my case is just having a `dummy` mutation as first field in `Mutation` object that uses `A` type:
```
    @GQLDescription("Dummy value introduced to fix Caliban type derivation error. Will throw an exception when called.")
    dummy: Int => A,
```
It's definitely not perfect and I would be really thankful if you could help me :)

**Comment by ghostdogpr** [comment]
Wow, that was a tough one. Thanks for the easy reproducer, that helped me a lot figuring it out.

What happens is that Magnolia doesn't provide information about which trait a class is extending. So I'm getting the `implements` info from the sealed trait itself, because there I know what are the subtypes. That means I define those OBJECT types in 2 different ways depending on the Schema. When I collect all types for introspection and rendering, I was merging duplicated types by keeping an arbitrary one. I changed it to collect all interfaces in the object I keep.

Fix is here: https://github.com/ghostdogpr/caliban/pull/493

I'm guessing you have a more complex schema than your example. Would you be able to confirm my branch fixes it (doing `publishLocal`)? Thanks!

**Comment by szymonrodziewicz** [comment]
I'm using scala 2.13 and I've tried to call sbt +publishLocal. However, I ended up having some errors thrown end everything ended with:
```
[error] (core / Compile / compileIncremental) java.lang.AssertionError: assertion failed: ClassBType.info not yet assigned: Ljava/lang/Object;
[error] (clientJS / Compile / compileIncremental) java.lang.AssertionError: assertion failed: ClassBType.info not yet assigned: Ljava/lang/Object;
[error] (clientJVM / Compile / compileIncremental) java.lang.AssertionError: assertion failed: ClassBType.info not yet assigned: Ljava/lang/Object;
```
I rarely use sbt and I may've got something wrong. Do you know what could be causing it? You could also just upload the built jar for me if it would be a faster way for you.

**Comment by ghostdogpr** [comment]
Can you try `++publishLocal`?

**Comment by szymonrodziewicz** [comment]
It's the same, even after `sbt clean`.

**Comment by ghostdogpr** [comment]
Hmm not sure what is happening 🤔 

Here's the jar I published locally: [caliban_2.13.jar.zip](https://github.com/ghostdogpr/caliban/files/4896318/caliban_2.13.jar.zip)

**Comment by szymonrodziewicz** [comment]
For some reason I had to add zio-streams and fastparse dependencies manually. But after that - everything works and your fixes resolved the problem. I can remove the dummy mutation and everything is working as I intended it to. Thank you :)

**Comment by ghostdogpr** [comment]
Cool, thanks for the confirmation! I will merge the PR and probably release this weekend.
