### ISSUE TITLE
Caliban Client: Add extensions to GraphQLResponseError

### ISSUE THREAD

**Issue by cilicio** [ghostdogpr/caliban#502]
I am currently working on a project with both, caliban server and client.  I am trying to consume data from the server where I have extra information in the extensions when errors are thrown. In server we have the option to add [extensions](https://ghostdogpr.github.io/caliban/docs/middleware.html#customizing-error-responses), but on the client we cannot obtain this.
So, to support this, I changed the client code locally, and add extensions like GraphQLResponse #486, and it works for me.   I guess this should be part of the standard library, so I'll probably be doing a pull request soon unless someone tells me I'm wrong.

**Comment by ghostdogpr** [comment]
Sounds good to me 👍
