### ISSUE TITLE
Upgrade ZIO to 1.0.0

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#534]
The following dependencies need to be upgraded and released first:

- [x] [zio-query](https://github.com/zio/zio-query/releases/tag/v0.2.4)
- [x] [zio-interop-cats](https://github.com/zio/interop-cats/releases/tag/v2.1.4.0)
- [x] [zio-interop-reactive-streams](https://github.com/zio/interop-reactive-streams/releases/tag/v1.0.3.5)
- [x] [zio-config](https://github.com/zio/zio-config/releases/tag/v1.0.0-RC26)
- [x] [sttp](https://github.com/softwaremill/sttp/pull/648)
- [ ] [uzhttp](https://github.com/polynote/uzhttp/pull/31)

**Comment by tusharmath** [comment]
Eagerly waiting :D

**Comment by ghostdogpr** [comment]
Hehe, interop-cats is coming soon. For sttp and uzhttp it depends on other maintainers though.
