### ISSUE TITLE
[CodeGen] Argument type names do not match with case class generated

### ISSUE THREAD

**Issue by galales** [ghostdogpr/caliban#552]
Code generation does not create a unique name for the argument case classes.

Examples below are taken from the first public graphql service I found online 
https://lucasconstantino.github.io/graphiql-online/

```
case class Comment(
      post: CommentPostArgs => Option[Post],
      ...
)

case class PostArgs(filter: Option[PostFilter])
```

In the `Comment` type the argument type has the right unique name, but the generated case class is instead `PostArgs`.
So we have 2 issues:
* names do not match
* `PostArgs` name is not unique, because a class with the same name is generated also for every `post` field that takes parameters

Caliban code gen version 0.9.1

**Comment by ghostdogpr** [comment]
The name clash is already documented in https://github.com/ghostdogpr/caliban/issues/367
But the names not matching is not, so maybe you could change the title and description of this issue to focus on that problem?

Looking at the code this one is easy to fix: in `SchemaWriter`, on one side (`writeField`) we call `${of.name.capitalize}${field.name.capitalize}Args` and on the other side (`writeArguments`) just `${field.name.capitalize}Args`.

**Comment by galales** [comment]
Ok, I'll make these changes and see if it solve the issue and, as per Discord chat, maybe the #367 too
