### ISSUE TITLE
[CodeGen] Arguments name do not match for root level operation

### ISSUE THREAD

**Issue by galales** [ghostdogpr/caliban#560]
This is related to issue #552 . The previous PR solved most of the mismatches, but in the current snapshot (`0.9.1+20-40e9f3a2-SNAPSHOT`) arguments in root level operations still do not match.

Example
```
object Operations {
  @GQLDescription("query root")
  case class query_root(
      posts: PostsArgs => zio.UIO[List[Post]]
  )
}

case class Query_rootPostsArgs(
    ...
)
```

I can work on this if you want

**Comment by ghostdogpr** [comment]
Right, there were 2 more methods to modify: `writeRootField` and `writeSubscriptionField`. Both have the same kind of code as in the previous PR. It's awesome if you can do it 🙏

**Comment by galales** [comment]
hi @ghostdogpr , sorry for the delay, I was on vacation, I started working on this issue today.
I just have one concern, right now this
```
type Mutation {
  post(author: String): Post
}
```

is generated as

```
case class Mutation(
  post: PostArgs => zio.UIO[Option[Post]]
)
```

this means that if we have also a Query named `post`, a new class with the same `PostArgs` will be generated.
I know that this should be unlikely, because it's not the best approach to use the same name for a mutation and a query, but it could happen.

The solution here could be, instead of `PostArgs`, to generate `MutationPostArgs`, and in the same way eventually `QueryPostArgs`.

I know this is a bit _ugly_, but this should prevent the name duplication at all levels, and use the same approach as the lower level types.

What do you think?

**Comment by ghostdogpr** [comment]
I think this is a good idea 👍
