### ISSUE TITLE
Schemas for higher-kinded types do not use the inner type annotations

### ISSUE THREAD

**Issue by iida-hayato** [ghostdogpr/caliban#573]
I try this schema definition code

```.scala
        case class Queries(a: Page[UserEntity], b: Page[UserEntity])
        case class Page[T](value: T)
        @GQLName("User")
        case class UserEntity(value: String)
```
and generate gql then get `PageUserEntity`, I expected this for `PageUser`

**Comment by iida-hayato** [comment]
sample test code

```.scala
      test("nested gql named types") {
        case class Queries(a: Page[UserEntity], b: Page[UserEntity])
        case class Page[T](value: T)
        @GQLName("User")
        case class UserEntity(value: String)
        assert(Types.collectTypes(introspect[Queries]).map(_.name.getOrElse("")))(
          contains("PageUserEntity")
          // contains("PageUser") // fail
        )
      },
```

**Comment by iida-hayato** [comment]
My understanding is,  `getName` function is called inside Magnolia's combine function.
and, Magnolia not suppose high-kinded types
https://github.com/propensive/magnolia/issues/29

so, In current version, Is such a class design less recommended?

**Comment by ghostdogpr** [comment]
I'm afraid this is a limitation of Magnolia. You can see the logic here: https://github.com/ghostdogpr/caliban/blob/master/core/src/main/scala/caliban/schema/Schema.scala#L515

Magnolia exposes `typeArguments` which is a `Seq[TypeName]` and doesn't contain any information about annotations on that type.

It would be nice to have a workaround though. I need to think about it 🤔

**Comment by ghostdogpr** [comment]
I digged a little bit more and I don't think we can do this in a generic way. However you can rename it easily like this: https://scastie.scala-lang.org/WCikDYiARXG1NO7h9SvNOA

```scala
implicit val pageUserEntitySchema = Schema.gen[Page[UserEntity]].rename("PageUser")
```
