### ISSUE TITLE
Question about ZQuery

### ISSUE THREAD

**Issue by dantodor** [ghostdogpr/caliban#586]
Hello!

Total ZIO/Caliban n00b here, so please excuse any mistakes I will make.

I'm taking my first steps in Caliban/ZIO world, until now I have been working in the Akka world. 
I like a lot where these libraries are taking me, but I have some troubles understanding... 
I'm trying to use the akka-slick template, with a slightly more complicated structure, that is prone to N+1, so I'm looking into integrating it with the approach described in the Medium post about ZQuery, caching, batching, etc. Where I have problems understanding is: how do I inject the SlickRepository into the resolver function, instead of the fixed DbService used in the demo ? 
How do I modify the original example ? 
```
def getExpenseByName(name: String): ZIO[ExpenseRepository, DomainError, List[Expense]] =
    ZIO.accessM(_.get.getByName(name))
```
to move it to ZQuery ? 
Is it correct to use the type `type MyQuery[+A] = ZQuery[Repository, RepositoryError, A]` ? 
If yes, how do I access the underlying functions in the repo ?

TIA!

**Comment by ghostdogpr** [comment]
That is correct, you need to use `ZQuery[Repository, RepositoryError, A]`, then when you implement your `DataSource`, you need to provide a ZIO anyway, so you can use `accessM` there. You can see an example with `Console` here: https://github.com/ghostdogpr/caliban/blob/master/examples/src/main/scala/caliban/optimizations/OptimizedTest.scala

**Comment by dantodor** [comment]
Thanks for the quick answer!
If I understand correctly, I can use it exactly like in the example, as ZIO.accessM(_.get.(functionFromTheRepo) ) ?

**Comment by ghostdogpr** [comment]
Yeah, you can see in the example I posted above, the DataSource is calling `putStrLn` which is itself using `accessM`. The difference is that the call is in the DataSource instead of directly in the resolver.

**Comment by ghostdogpr** [comment]
@dantodor is it okay to close this? Let me know if you still have more questions :D

**Comment by dantodor** [comment]
So... Here is where I am :
```
type MyQuery[+A] = ZQuery[ExpenseRepository, RepositoryError, A]
...
def getReviewers(id: DocId): MyQuery[List[ReviewerView]] =
    ZQuery
      .fromEffect(ZIO.accessM(_.get.getDocumentReviewers(id)))
...
  case class GetUser(id: UserId) extends Request[Nothing, UserView]
  val UserDataSource: DataSource[DocumentRepository, GetUser] =
    DataSource.fromFunctionBatchedM("UserDataSource")(
      requests => ZIO.accessM(_.get.getUsers(requests.map(_.id).toList)).map(Chunk.fromIterable)
    )
  def getUser(id: UserId): MyQuery[UserView] = ZQuery.fromRequest(GetUser(id))(UserDataSource)
```

The `getReviewers` goes well. But in the case of `getUser`, compiler complains:
```
[error] .../application/ApplicationService.scala:33:31: missing parameter type for expanded function ((<x$6: error>) => x$6.get.getUsers(requests.map(((x$7) => x$7.id)).toList))
[error]       requests => ZIO.accessM(_.get.getUsers(requests.map(_.id).toList)).map(Chunk.fromIterable)
[error]                               ^

```

What did I got wrong from your answer ?

**Comment by ghostdogpr** [comment]
I think you need to specify the type parameter when you call `accessM` (like `ZIO.accessM[DocumentRepository]`).
Also your DataSource uses `DocumentRepository` but `MyQuery` uses `ExpenseRepository`, is that okay? (it's okay if one includes the other but not if they're different).

**Comment by dantodor** [comment]
Damn 👍 .... Worked like a charm :) ... Thanks a lot for spending time with a n00b issue :D ... You're right, I reconciled the repositories.

**Comment by ghostdogpr** [comment]
Cool! I'm closing then. Feel free to join the Discord for quick Q&A 😀
