### ISSUE TITLE
Exception classes should override getMessage instead of toString

### ISSUE THREAD

**Issue by mleclercq** [ghostdogpr/caliban#603]
Exceptions sub classes overrides `toString` instead of `getMessage` for instance in https://github.com/ghostdogpr/caliban/blob/master/client/src/main/scala/caliban/client/CalibanClientError.scala#L13

As a result when these exceptions are logged through SLF4J, the stack trace does not contain the actual error message. For instance I get:

```
caliban.client.CalibanClientError$CommunicationError: null
	at caliban.client.SelectionBuilder.$anonfun$toRequestWithExtensions$2(SelectionBuilder.scala:95)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at caliban.client.SelectionBuilder.$anonfun$toRequestWithExtensions$1(SelectionBuilder.scala:95)
        ...
```

I'll try to contribute a PR.

**Comment by ghostdogpr** [comment]
Good point. I think we might still need the `toString` override since it's called in a few places. Maybe both?

**Comment by tdrozdowski** [comment]
I'd be interested in taking a shot at this for the Hackathon

**Comment by ghostdogpr** [comment]
@tdrozdowski cool! Let me know if you have any question.
