### ISSUE TITLE
Example with ExecutionError

### ISSUE THREAD

**Issue by BorderCloud** [ghostdogpr/caliban#614]
Can you add a fake query in the class "ExampleService.scala" where you show how to build an error message with the class "ExecutionError" ?

I tried with "throw", "IO.fail", "IO.FromEither", etc but I cannot replace  the message by default "Effect failure".

Thanks

**Comment by ghostdogpr** [comment]
@BorderCloud I just tried calling `Task.fail(CalibanError.ExecutionError("Blah"))` in `ExampleService.scala` and I get "Blah" in the returned error message. It requires changing `UIO` to `Task` and `URIO` to `RIO`.

If it still doesn't work, could you share what code you tried?

**Comment by BorderCloud** [comment]
Thank you for your quick response.

It works.

I suffer with ZIO ;-)
