### ISSUE TITLE
Nested effect with environments don't generate schema

### ISSUE THREAD

**Issue by Gryfit** [ghostdogpr/caliban#620]
Maybe I'm doing something wrong but it doesn't generate a schema when `RIO[R,T]` is nested in Query definition. 
Let's look at an example:
```scala
object t {
  type Env = Console with Clock
}
case class A(a: RIO[t.Env, String])
case class Queries(query1: () => RIO[t.Env, A])
object test extends GenericSchema[t.Env]{
  val schema = Schema.gen[A]
}
```
this gives me the error: ` magnolia: child object Yield of trait ZIO is neither final nor a case class`
If I change to: `case class A(a: RIO[Any, String])`
It compiles again.
How can I make it work?

**Comment by ghostdogpr** [comment]
`Schema` is actually just `object Schema extends GenericSchema[Any]`, so when you use it like this, you're forcing the env to be `Any`. Instead, you need to use the `gen` coming from `GenericSchema[t.Env]`.

So just change your code to the following will work:
```scala
  val schema = gen[A]
```

**Comment by Gryfit** [comment]
Thank you. :D 
I missed that.
