### ISSUE TITLE
Control generated name for existing types

### ISSUE THREAD

**Issue by ksonj** [ghostdogpr/caliban#622]
It is currently quite difficult to change the GraphQL type name of an existing scala type (that is e.g. imported from a third party library), because the only provided means is via the `GQLName` annotation, which obviously cannot be applied to already existing types.

I am envisioning something like this

```scala

final case class UglyName(bar: Int)

object UglyName {
  implicit val uglyNameSchema: Schema[Any, UglyName] = Schema.gen[UglyName].rename("VeryNiceName")
}
```

which I currently achieve by doing

```scala
implicit class RenamableSchemaExtension[-R, A](val schema: Schema[R, A])
    extends AnyVal {
  def rename(name: String): Schema[R, A] =
    new Schema[R, A] {
      override protected[this] def toType(
          isInput: Boolean,
          isSubscription: Boolean
      ): __Type = {
        val typeName = if (isInput) s"${name}Input" else name
        schema.toType_(isInput, isSubscription).copy(name = typeName.some)
      }
      override def resolve(value: A): Step[R] =
        schema.resolve(value) match {
          case step: ObjectStep[R] => step.copy(name = name)
          case step                => step
        }
    }
}

```

with which I can now call `rename` as above:

```scala
implicit val uglyNameSchema = Schema.gen[UglyName].rename("NiceName")
```

That feels a little brittle though and I'm not very sure that it even accounts for all possibilities (in fact I'd seriously doubt it does).

Would this be something the community is interested in?

**Comment by ksonj** [comment]
I just realized this might be duplicate of https://github.com/ghostdogpr/caliban/issues/130, right?

**Comment by ghostdogpr** [comment]
It's not the same thing as #130. With #130 you do the renaming on the `GraphQL` object once all schemas are generated. It's useful for example to add a prefix to all types. But your suggestion is more precise and would cover the case of a conflict where you don't want to generate the API with 2 types having the same name. 

So I think your proposal is a good thing. I'll dig into it when I have time, possibly during the ZIO Hackathon.

**Comment by ghostdogpr** [comment]
@ksonj I opened a PR for it. Would you be able to confirm it works for your case?
