### ISSUE TITLE
Expose selection information in resolve

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#632]
Add a way to receive the selection information and use it in resolvers (e.g. for optimizations).

**Comment by ghostdogpr** [comment]
As discussed on Discord, a better approach would be to have a Schema for `Field => A` or `FieldInfo => A`.
Something similar to `functionSchema` except it's `Field => B` of `FieldInfo => B` (whichever is more convenient to implement) instead of `A => B`, and it would return either a `FunctionStep` with some special data, or another dedicated `Step`. Then in the executor, when we meet that case, we would feed it the Field/FieldInfo instead of reading from arguments.

**Comment by jweaver-personal** [comment]
I'm taking this issue for the hackathon.
