### ISSUE TITLE
Make the examples to compile

### ISSUE THREAD

**Issue by palutz** [ghostdogpr/caliban#66]
Trying the examples (to understand the lib), but they not compile.
Is it also possible to have a build.sbt as example for running the project?

Thanks

**Comment by ghostdogpr** [comment]
@palutz the examples project is part of the whole project's build.sbt but I added this README in case you want to compile only the examples: https://github.com/ghostdogpr/caliban/tree/master/examples

Does that work for you? Let me know if you still have some errors.

**Comment by ghostdogpr** [comment]
Closing but feel free to reopen if the instructions aren't enough.

**Comment by palutz** [comment]
Hi,
thanks for the answer.
Anyhow the code provided (with the readme) is at least solving most of the problems but still have some compile errors

> no type parameters for method apply: (http: org.http4s.Http[F,G], config: org.http4s.server.middleware.CORSConfig)(implicit F: cats.Applicative[F])org.http4s.Http[F,G] in object CORS exist so that it can be applied to arguments (org.http4s.HttpRoutes[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$]], org.http4s.server.middleware.CORSConfig)
> [error]  --- because ---
> [error] argument expression's type is not compatible with formal parameter type;
> [error]  found   : org.http4s.HttpRoutes[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$]]
> [error]     (which expands to)  cats.data.Kleisli[[β$0$]cats.data.OptionT[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$],β$0$],org.http4s.Request[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$]],org.http4s.Response[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$]]]
> [error]  required: org.http4s.Http[?F,?G]
> [error]     (which expands to)  cats.data.Kleisli[?F,org.http4s.Request[?G],org.http4s.Response[?G]]
> [error]                 "/api/graphql" -> CORS(Http4sAdapter.makeRestService(interpreter)),
> 
> type mismatch;
> [error]  found   : org.http4s.HttpRoutes[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$]]
> [error]     (which expands to)  cats.data.Kleisli[[β$0$]cats.data.OptionT[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$],β$0$],org.http4s.Request[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$]],org.http4s.Response[[β$0$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$0$]]]
> [error]  required: org.http4s.Http[F,G]
> [error]     (which expands to)  cats.data.Kleisli[F,org.http4s.Request[G],org.http4s.Response[G]]
> [error]                 "/api/graphql" -> CORS(Http4sAdapter.makeRestService(interpreter)),
> 
> no type parameters for method apply: (http: org.http4s.Http[F,G], config: org.http4s.server.middleware.CORSConfig)(implicit F: cats.Applicative[F])org.http4s.Http[F,G] in object CORS exist so that it can be applied to arguments (org.http4s.HttpRoutes[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$]], org.http4s.server.middleware.CORSConfig)
> [error]  --- because ---
> [error] argument expression's type is not compatible with formal parameter type;
> [error]  found   : org.http4s.HttpRoutes[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$]]
> [error]     (which expands to)  cats.data.Kleisli[[β$0$]cats.data.OptionT[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$],β$0$],org.http4s.Request[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$]],org.http4s.Response[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$]]]
> [error]  required: org.http4s.Http[?F,?G]
> [error]     (which expands to)  cats.data.Kleisli[?F,org.http4s.Request[?G],org.http4s.Response[?G]]
> [error]                 "/ws/graphql"  -> CORS(Http4sAdapter.makeWebSocketService(interpreter))
> 
> type mismatch;
> [error]  found   : org.http4s.HttpRoutes[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$]]
> [error]     (which expands to)  cats.data.Kleisli[[β$0$]cats.data.OptionT[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$],β$0$],org.http4s.Request[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$]],org.http4s.Response[[β$3$]zio.ZIO[zio.console.Console with zio.clock.Clock,Throwable,β$3$]]]
> [error]  required: org.http4s.Http[F,G]
> [error]     (which expands to)  cats.data.Kleisli[F,org.http4s.Request[G],org.http4s.Response[G]]
> [error]                 "/ws/graphql"  -> CORS(Http4sAdapter.makeWebSocketService(interpreter))

Didn't use http4s so much so having some trouble helping you here.

**Comment by ghostdogpr** [comment]
@palutz are you maybe using http4s 0.20.12? caliban depends on version 0.21.0-M5, that could explain the errors maybe?

If that's not the reason, any chance you make your repo public so I can have a look?

**Comment by palutz** [comment]
I didn't import any https dependencies (just used the lib use showed on the readme). If I used the https libs nothing changed (with 0.20.10)
Trying the 0.21.0-M5 I've got the same problem

**Comment by palutz** [comment]
This is my build.sbt 

val zioLib = Seq(
  "dev.zio" %% "zio" % "1.0.0-RC15",
  "dev.zio" %% "zio-streams" % "1.0.0-RC15",
  "dev.zio" %% "zio-interop-cats" % "2.0.0.0-RC6",

  "org.http4s"      %% "http4s-dsl"          % Http4sVersion,
  "org.http4s"      %% "http4s-blaze-server" % Http4sVersion,
  "org.http4s"      %% "http4s-blaze-client" % Http4sVersion,
//  "org.http4s"      %% "http4s-circe"        % Http4sVersion,
//  "io.circe"        %% "circe-generic"       % CirceVersion,
//  "org.specs2"      %% "specs2-core"         % Specs2Version % "test",
//  "ch.qos.logback"  %  "logback-classic"     % LogbackVersion
)

lazy val myScalacOptions = Seq(
  "-Ypartial-unification"
)

> lazy val root = (project in file("."))
>   .settings(
>     name := "calibanTest",
>     libraryDependencies ++= Seq(
>       "com.github.ghostdogpr" %% "caliban" % "0.2.0",
>       "com.github.ghostdogpr" %% "caliban-http4s" % "0.2.0",
>       "com.github.ghostdogpr" %% "caliban-cats" % "0.2.0",
>     ),
>     libraryDependencies ++= zioLib
> 


same things happened also if importing only the http4s dependencies (+ caliban ones)

**Comment by ghostdogpr** [comment]
Ah i think it might be ZIO itself. Caliban uses 1.0.0-RC16 and the interop-cats is RC7. Is that better?

**Comment by palutz** [comment]
Nope... I uploaded the whole prj on this repo:
https://github.com/palutz/calibanTest

**Comment by ghostdogpr** [comment]
You miss the `-Ypartial-unification` flag:
```scala
scalacOptions ++= Seq("-Ypartial-unification")
```
After I added this, it compiles well. This is required by http4s: https://http4s.org/v0.21/

**Comment by palutz** [comment]
Gosh... so silly mistake.
Thanks ;)
