### ISSUE TITLE
Fields annotated with @GQLDeprecated disappear from GraphQL#render

### ISSUE THREAD

**Issue by YulawOne** [ghostdogpr/caliban#669]
Fields annotated with `@GQLDeprecated` disappear from GraphQL#render, while expected behavior is fields should remain and annotation `@deperecated` should be set on the field.

**Comment by ghostdogpr** [comment]
The logic is in Rendering.scala. When we gather fields, the `__DeprecatedArgs` arguments should be changed to include deprecated fields.
