### ISSUE TITLE
Empty object dummy field returns __typename

### ISSUE THREAD

**Issue by amiralies** [ghostdogpr/caliban#672]
from examples, if you resolve `Mechanic` it has a dummy `_` Nullable Boolean field but it contains `Mechanic`'s  __typename which is `"Mechanic"` String.

Note that if you use a case class with no fields instead of case object, it returns `null` which is correct behaviour I think.

```scala
sealed trait Role
object Role {
  case class Captain(shipName: String) extends Role
  case class Engineer(specialty: String) extends Role
  case object Mechanic extends Role
}
```
Case object:
![image](https://user-images.githubusercontent.com/13261088/101266490-768ad780-3764-11eb-8d28-7d32378b2b12.png)

Empty case class:
![image](https://user-images.githubusercontent.com/13261088/101266462-4c391a00-3764-11eb-95df-747a5a665c5f.png)

**Comment by ghostdogpr** [comment]
Actually this field is not meant to be queried:

> GraphQL does not support empty objects, so in case a sealed trait mixes case classes and case objects, a union type will be created and the case objects will have a "fake" field named _ which is not queryable.

Basically only `__typename` should be used there. I admit the difference between case object and empty case class is a little weird though.

**Comment by ghostdogpr** [comment]
Closing since the docs and the field description both say to not use it, I don't think it's worth investigating 😄

**Comment by amiralies** [comment]
yup, I'm aware of that.
In some cases it may break clients. when they try to deserialize/parse the response they are trying to parse a boolean instead they face a string i.e https://github.com/reasonml-community/graphql-ppx. and docs don't prevent consumers from querying this.
maybe we can return null in all cases?

**Comment by ghostdogpr** [comment]
Alright, keeping it open 😄

**Comment by ghostdogpr** [comment]
Turns out it was pretty simple: https://github.com/ghostdogpr/caliban/pull/673
