### ISSUE TITLE
Add implicit class for ZServerEndpoint inside  interop.tapir

### ISSUE THREAD

**Issue by dylandoamaral** [ghostdogpr/caliban#674]
Hi there,

I propose to add an `implicit class GraphQLZServerEndpoint[R, I, E, O](e: ZServerEndpoint[R, I, E, O])` to support `ZServerEndpoint` from [tapir](https://tapir.softwaremill.com/en/latest/endpoint/zio.html).

I personally failed to use `GraphQLServerEndpoint` for my `ZServerEndpoints` because of their definitions:
`type ZServerEndpoint[R, I, E, O] = ServerEndpoint[I, E, O, Nothing, RIO[R, *]]` that contains a ZIO that can throws an error instead of returning an `E`.

To be honest, I tried to add it myself but I failed ^^'

**Comment by dylandoamaral** [comment]
I tried something but I need at least a mapping from `Throwable` to `E`:

```scala
  implicit class GraphQLZServerEndpoint[R, I, E, O](e: ZServerEndpoint[R, I, E, O]) {
    def toGraphQL(mapping: Throwable => E)(
      implicit inputSchema: caliban.schema.Schema[R, I],
      outputSchema: caliban.schema.Schema[R, O],
      argBuilder: ArgBuilder[I]
    ): GraphQL[R] =
      tapir.toGraphQL(
        e.endpoint.serverLogic(input =>
          ZQuery.fromEffect(e.logic(monadError)(input).mapError(mapping).either.map(_.flatMap(identity)))
        )
      )
  }
```

**Comment by ghostdogpr** [comment]
Tapir defines `ZServerEndpoint` as follows:
```scala
type ZServerEndpoint[R, I, E, O] = ServerEndpoint[I, E, O, Nothing, RIO[R, *]]
```
but Caliban expects the `E` to be the same as the effect error type which is fixed to `Throwable` by Tapir.

If `E` = `Throwable`, you can use the existing `GraphQLServerEndpoint`.

That's a little weird to me that tapir uses `E` on one side and `Throwable` on the other 🤔

**Comment by ghostdogpr** [comment]
You could potentially transform the `E` into a `Throwable` in `GraphQLZServerEndpoint` (unless it's already a `Throwable`, then you just keep it), like it's done in lines 129-130 already.

**Comment by dylandoamaral** [comment]
I think we can't exactly do the same thing because the `E` belongs to the tapir endpoint not the ZIO effect. To map it into a `Throwable`, I have to provide a mapping between `E` and `Throwable`.

Providing a function from `E` to `Throwable` is easy but the contrary is inapplicable.

**Comment by ghostdogpr** [comment]
Right. Are your errors actually not `Throwable`? Caliban requires that on resolvers anyway.

**Comment by dylandoamaral** [comment]
No, I used https://tapir.softwaremill.com/en/latest/endpoint/statuscodes.html to create my error system that allow the program to return errors as jsons for other status code than `success`. I then wanted to figure out if I can have both http and graphql routes but both error handling are totally different.

**Comment by ghostdogpr** [comment]
You could make a bidirectional mapping to a custom Throwable holding the status inside, and when you convert from Throwable, if it's any other Throwable you map it to Internal Server Error.

**Comment by dylandoamaral** [comment]
Yes I had something like that in mind! Thank you very much, you can close this issue if you don't plane to provide a common way to interface ZServerEndpoint with caliban.

Congrats for this wonderful lib 👏

**Comment by ghostdogpr** [comment]
Thanks! I'll close for now as I don't see a better way but we can reopen if there is.
