### ISSUE TITLE
Partial result for nested ZQuery

### ISSUE THREAD

**Issue by v-tec2706** [ghostdogpr/caliban#698]
Let's say I have following case:
```scala
case class User(name: String, friends: Zquery[Any, Throwable, List[String]])
case class Queries(
  user: UserArgs => ZQuery[Any, Throwable, User]
)
```
and I submit a request with following query: 
```graphql
{
 user1: user(id1)
 user2: user(id2)
}
```
and assuming that fetching `friends` for second user fails I'll get:
```graphql
data: {
   "user1": {
         "name": "John",
         "friends": ["Tom", "Emily"]
    },
    "user2": {
          "name": "Jack",
          "friends": null
     }
}
errors: [
{
      "message": "fetching friends failed",
      "path": ["user2"]
}]
```
but let's say that I want `friends` field to be `non-nullable` and I change `User` definition to be:
```scala
case class User(name: String, friends: Zquery[Any, Nothing, List[String]])
case class Queries(
  user: UserArgs => ZQuery[Any, Throwable, User]
)
```
then according to the specification which says:

> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. In that case, the path for the error should include the full path to the result field where the error occurred, even if that field is not present in the response.

[example](http://spec.graphql.org/draft/#example-08b62)
I expect result of request presented above to be: 
```graphql
data: {
   "user1": {
         "name": "John",
         "friends": ["Tom", "Emily"]
    },
    "user2": null
}
errors: [
{
      "message": "fetching friends failed",
      "path": ["user2"]
}]
```
but what I get is: 
```graphql
data: null
errors: [
{
      "message": "fetching friends failed",
      "path": ["user2"]
}]
```
Failure in nested query is propagated as a failure of the whole request.

Can I achieve my expected response with Caliban?

**Comment by ghostdogpr** [comment]
Seems to be a bug indeed. The logic to handle `ZIO.Die` is only at the whole query level currently, there's no logic to bubble it up.
