### ISSUE TITLE
Implement missing query validations

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#7]
Missing validations:
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Field-Selection-Merging
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Fragment-spread-is-possible
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Values-of-Correct-Type (while doing this, `ArgBuilder` error type should be changed to `ValidationError`)
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Input-Object-Field-Names
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Input-Object-Field-Uniqueness
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Input-Object-Required-Fields
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Directives-Are-In-Valid-Locations
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-Directives-Are-Unique-Per-Location
- [x] https://graphql.github.io/graphql-spec/June2018/#sec-All-Variable-Usages-are-Allowed

**Comment by paulpdaniels** [comment]
For field selection merging, there is a paper that details a faster implementation: https://tech.xing.com/graphql-overlapping-fields-can-be-merged-fast-ea6e92e0a01

And a reference implementation that was added to sangria: https://github.com/sangria-graphql-org/sangria/pull/12
