### ISSUE TITLE
`Schema.rename` on a union and inline fragments

### ISSUE THREAD

**Issue by guymers** [ghostdogpr/caliban#715]
Given the following schema:
```scala
sealed trait Union
object Union {
  case class Child(field: String) extends Union
}

case class Obj(
  union: Union,
)
case class Query(
  test: Obj,
)

object Schema {
  implicit val schemaUnionChild: Schema[Any, Union.Child] = Schema.gen[Union.Child].rename("UnionChild")
  implicit val schemaTestUnion: Schema[Any, Union] = Schema.gen[Union]
  implicit val schemaQuery: Schema[Any, Query] = Schema.gen[Query]
}
```

A query:
```graphql
query {
  test {
    union {
      __typename
      ... on UnionChild {
        field
      }
    }
  }
}
```

Produces the expected result:
```json
{
  "test": {
    "union": {
      "__typename": "UnionChild",
      "field": "f"
    }
  }
}
```

Renaming the `Union` using the `rename`  method on `Schema`:
```scala
implicit val schemaTestUnion: Schema[Any, Union] = Schema.gen[Union].rename("UnionRenamed")
```
gives the following:
```json
{
  "test": {
    "union": {
      "__typename": "UnionRenamed"
    }
  }
}
```

Using the `@GQLName` annotation produces the expected result.

**Comment by ghostdogpr** [comment]
I guess it comes from this line: https://github.com/ghostdogpr/caliban/blob/1308750033cd5df4d16fb49e3d35c30a7e1a5a9e/core/src/main/scala/caliban/schema/Schema.scala#L104
When the type is a union, we are using the subtype and should not overwrite the name. But we don't know it's a union so maybe the info needs to be added. Need to think about it 🤔

**Comment by ghostdogpr** [comment]
@guymers I opened a PR for this #728

If you wanna try my branch and confirm it works for you, that would be great. Otherwise I'll merge it in a few days.

**Comment by guymers** [comment]
#728 fixes the issue thanks!

I have found another rename issue in regards to objects though.

Adding `case object ChildO extends Union` and renaming it
```
implicit val schemaUnionChildO: Schema[Any, Union.ChildO.type] = Schema.gen[Union.ChildO.type].rename("UnionChildO")
```

results in the following schema:
```
union Union = UnionChild | UnionChildO

type UnionChild {
  field: String!
}

type UnionChildO {
  "Fake field because GraphQL does not support empty objects. Do not query, use __typename instead."
  _: Boolean
}
```

querying returns:
```
{
  "test": {
    "union": {
      "__typename": "ChildO"
    }
  }
}
```

If `Union.ChildO` is a `case class` with no fields then the returned `__typename` is `UnionChildO`

**Comment by ghostdogpr** [comment]
@guymers I updated my PR to fix that case too, can you kindly confirm? Thanks!

**Comment by guymers** [comment]
Can confirm that the updated changes fix that case as well, thank you!
