### ISSUE TITLE
Akka HTTP Adapter

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#72]
Add a new module similar to `caliban-http4s` named `caliban-akka-http` that exposes a REST and a WebSocket API for a given GraphQL interpreter.

If there is common code between the http4s and the akka one, it should be factored out.

I haven't used Akka in a while, so external contributors are welcome to pick this one up!

EDIT: HTTP is done, only WebSocket is missing

**Comment by jona7o** [comment]
I am currently work on a solution with an example. 
I haven't use ZIO in a production project, so i hope i'll use the best practises in my PR later this day.
If not, please give me some tipps.

**Comment by ghostdogpr** [comment]
@jona7o that would be awesome!

**Comment by jona7o** [comment]
I have finished the rest part and started with the ws part. 
This week my time is running out so i created a merge request. Perhaps someone else will finish the ws part until i have time for more contribution.

**Comment by jona7o** [comment]
Short hint for the faq:

if someone tries using caliban with lagom and not with akka the solution will look like this:

service-api:
`
def graphqlApi: ServiceCall[GraphQLRequest, GraphQLResponse[CalibanError]]

  override def descriptor: Descriptor = {
    import Service._
    named("graphql").
      withCalls(
        restCall(Method.POST, "/api/graphql", graphqlApi _)
      )
      .withAutoAcl(true)
      .withAcls(
        ServiceAcl.forMethodAndPathRegex(Method.OPTIONS, "/api/.*")
      )
  }
`

service-impl:
`
override def gqlApi(): ServiceCall[GraphQLRequest, GraphQLResponse[CalibanError]] = { graphQLRequest =>
    runtime
      .unsafeRunToFuture(
        interpreter
          .execute(graphQLRequest.query,
            graphQLRequest.operationName,
            graphQLRequest.variables
              .getOrElse(Map())))
      .future
  }
`
finally the DefaultRuntime can be injected while the Application is created by the LagomApplicationLoader

`
 implicit val gatewayZIORuntime = new DefaultRuntime {}

  override lazy val lagomServer: LagomServer = serverFor[graphqlGatewayService](wire[GraphQLGatewayServiceImpl])
`

**Comment by phderome** [comment]
I'd like to volunteer to pursue this for approximately the period of 1/2 of February.
