### ISSUE TITLE
Can't validate fragment at the root level of query

### ISSUE THREAD

**Issue by heyrutvik** [ghostdogpr/caliban#721]
Following query doesn't validate (though it's valid) hence Caliban throws an exception: `Fragment spread 'ID' targets an invalid type: 'Query'.` 
```
query {
  ...ID
}

fragment ID on Query {
  characters(origin: EARTH) {
    name
    origin
  }
}
```
But same query structured differently works,
```
query {
  characters(origin: EARTH) {
    ...ID
  }
}

fragment ID on Character {
  name
  origin
}
```

**Comment by ghostdogpr** [comment]
@heyrutvik Found the reason! https://github.com/ghostdogpr/caliban/pull/729
