### ISSUE TITLE
Cats fetch interop

### ISSUE THREAD

**Issue by ValdemarGr** [ghostdogpr/caliban#773]
Caliban is a very nice library to work with but the zio-query data sources do not play all that well with cats.
A cats variant of zio-query exists (https://github.com/47degrees/fetch).
Is this a feasible request?

**Comment by paulpdaniels** [comment]
It depends on how deep an interop you mean. There is already a `cats` interop that lets you define a schema in terms of `F[_]` so you could use `Fetch` there if you wanted. But the internals heavily rely on ZQuery so I don’t think we’d want to abstract the query type away.

**Comment by ValdemarGr** [comment]
Okay, thank you.
