### ISSUE TITLE
Client Writer reservedKeywords check incomplete

### ISSUE THREAD

**Issue by johanneshiry** [ghostdogpr/caliban#775]
Hi everyone,

first of all thanks for the library. I started working with it today and it has been very helpful so far. 

As I use gradle and not sbt for project builds, I manually had to add the `caliban-tools` to generate my schema class. After the generation the class did not compile, as our schema has a `_label_` field that interfers with the scala code syntax. The current implementation of `ClientWriter` converts the `_label_` to `def _label_:` which is not compiling. 

Short term workaround in our case is to just add `_label_` to `reservedKeywords` set in  `ClientWritter:628` in order to let `def _label_` become ``def `_label_`: `` which compiles seamlessly.

In the long run however I think it would make sense to have a proper check of a word starts or and with `_` in order to improve the code generation. 

If you're interested, I can hand in a PR for this within the next few days.

**Comment by ghostdogpr** [comment]
Sounds good, thanks a lot 👍
