### ISSUE TITLE
Mutation contains null values if None is provided 

### ISSUE THREAD

**Issue by johanneshiry** [ghostdogpr/caliban#778]
Hi again,

after generating a schema and using it to connect a client to an existing GraphQL endpoint I stumbled over the following situation and I don't know if this is a bug or a feature and I just use it wrong. 

**Background:**
I generated a schema using graphQL introspection. As a result also the encoder `encode(value: T)` methods are generated in the schema class. 
When I now built a Mutation using this schema and don't provide data for all fields, the fields I don't provide data for stay `None` in scala. As a result, the created mutation, contains `null` values which leads to ` "Cannot convert undefined or null to object"` issues when executing the query. 

**Mutation Creation Code:**
```scala
    Mutation.createEntry(
      Some(EntryCreateInput(
        title = title,
        subTitle = subtitle,
        content = content,
        url = Some(url),
        `type` = Some(EntryTypeType.url),
        publishDate = Some(ZonedDateTime.now().toLocalDate.toString) // todo
      ))
    )(Entry.view()(CloudinaryImage_File.view(),
      Tag.view(Language.view, CloudinaryImage_File.view()),
      _QueryMeta.view,
      Language.view,
      Source.view(GeoLocation.view(LocationGoogle.view)))
    )
```

**Invalid Mutation:**
```
mutation {
  createEntry(
    data: {
      publishDate: null
      title: "<Dummy>"
      subTitle: "<Dummy>"
      image: null
      content: "<Dummy>"
      summary: null
      url: "<Dummy>"
      tags: null
      language: null
      source: null
      hasBeenTagged: null
      type: url
    }
  ) {...}
```

**Workaround/Solution:**
A workaround for us is to adapt the generated schema encoder by adding `.filterNot(_._2.equals(__NullValue))` after the generation of each list. 

**Resulting Valid Mutation:**
```
 mutation {
  createEntry(
    data: {
      title: "<Dummy>"
      subTitle: "<Dummy>"
      content: "<Dummy>"
      url: "<Dummy>"
      type: url
    }
  ) {...}
```

**Question:**
Do I just use the client mutation builder wrong or is this the intended behavior? Or is this also a bug?
If this is a bug, adding `.filterNot(_._2.equals(__NullValue))` in `ClientWriter:421` would fix this. 

Thanks in advance for any response.

**Comment by ghostdogpr** [comment]
Hmm where does this error come from? It's not Caliban. Having `null` fields for optional input fields is valid graphql, I just tested it. 

We could potentially add a parameter to drop all null fields when building the query (controlling it per-field was discussed before but it is much more complicated).

**Comment by johanneshiry** [comment]
Thanks for the fast reply. We're using [KeystoneJS](https://www.keystonejs.com/) as API endpoint. I'm not that much experienced with GraphQL so you might be right and it is an issue on the KeystoneJS implementation side. 

If you're interested in such a parameter in the query building process, it could try to work on that (drop all null values, not per field). If you don't bother bc it is a KeystoneJS issue and the mutation is valid I'm fine if we leave it as it is. Please let me know what you think about it. I'm also going to hand in an issue in the KeystoneJS repo. Maybe they are (not) aware of this.

**Comment by ghostdogpr** [comment]
No problem for adding the option 👍

**Comment by MasseGuillaume** [comment]
I got the same issue with Query on the Magento API. I think it would make sense to be able to drop null values.

**Comment by johanneshiry** [comment]
Started working on a solution yesterday and I hope I'll find some time to finish it within the next two weeks. Keep you updated.

**Comment by MasseGuillaume** [comment]
Hi @johanneshiry, do you need help with this PR? It's a feature we need. I'm willing to spend the time to write the test or the documentation.

**Comment by johanneshiry** [comment]
Hi @MasseGuillaume - my main work kept me busy the last few weeks but I think I can spend some time on this within next week. However, if this is urgent to you, feel free to add the missing parts to the existing PR. 
I just send you a collab invitation. 

So far I think the main feature is ready but the tests are missing. If you start working in this pls let me know to prevent double work. If I start working on this I'll let you know as well here.

**Comment by ckittl** [comment]
Hey guys!

Just want to draw your attention to a possible shortcoming of the proposed solution. This is also with regard to #798.

## Example
I want to query entities, who's field `c` (of type String) is either empty or something specified. So, desired GraphQL query would look like
```graphQL
query {
  foo(
    where: {
      OR: [{c: null}, {c: "bar"}]
    }
  ) {
    a, b, c
  }
}
```

However, filtering out the null values, doesn't allow me to form the first part of the `OR` statement...

## Possible solution
I really appreciate Johannes attempt to have less pollution within the graphQL query. However, this raises the need, to explicitly state "that specific entry shall remain null". Maybe it would be possible to detect `*WhereInput` and omit filtering null values?!

**Comment by ghostdogpr** [comment]
The solution above is an optional parameter, so if you don't specify it you would keep the null values. The only problem is if you want both behaviors on different objects (keep null for one object and drop it for another). Is that what you meant?

A different solution could be to add a function `.dropNullValues` to `ArgEncoder` that would return a new `ArgEncoder` with the different behavior.  Then if you want it, you can simple create a `implicit val customArgEncoder = argEncoderFromCodegen.dropNullValues` and if it's in scope the implicit priority will pick it up over the autogenerated one. That way you can customize the behavior per input object type instead of at the whole query level. Wdyt?

**Comment by ckittl** [comment]
Hmmm... As I think a bit more in-depth about it and considering, that the Keystone API might experience issues with too many nulls, it would be more desirable to be able to explicitly state "that field is meant to be null". Might also be worthwhile for mutations, as when you would like to "delete" something from database...

**Comment by ghostdogpr** [comment]
Actually the solution I proposed in my last message gives the most flexibility since you have full control on the object before it gets turned into Json. The helper could even take an optional list of fields to keep or drop when they're null. 

The only drawback is that you need to do it explicitly for each input type. But maybe we could combine both solution so there's an overall setting and then you can override it locally.

**Comment by ghostdogpr** [comment]
Opened #923 for this
