### ISSUE TITLE
Caliban alternative to ProjectionName in Sangria

### ISSUE THREAD

**Issue by winsvu** [ghostdogpr/caliban#781]
I am migrating from Sangria to Caliban and I am facing a situation where I need to show a name for a field in my schema, but when I ask for the name of the field in the resolver implementation, I could have an alias or an alternative name for that field.

For example, let's say I have a schema like the following:
```graphql
type Query {
  journal: Journal!
}
 
type Journal{
  title: String
}
```

so, everybody can request the title of a journal like this:
```graphql
{
  journal{
    title
  }
}
```

Using ```caliban.execution.Field``` I want to get the list of fields that have been requested, so I am doing something like this ```field.fields.map(_.name)``` to get all the fields requested in the graphql query, however, I want **title** field to have a different name internally, because in my DB it has a name like **journal_title**, and using ```Field``` allows me to ask dynamically for fields in my DB.

In Sangria I can use the following to achieve that 
```scala
@GraphQLFieldTags(ProjectionName("journal_title"))
title: Option[String]
```

Is there any alternative in Caliban?

**Comment by ghostdogpr** [comment]
There is currently no alternative in Caliban. That would be nice to have indeed.

**Comment by winsvu** [comment]
Thank you @ghostdogpr

**Comment by paulpdaniels** [comment]
Would a directive on the field work? Then you can access the field data using the a special function that takes it as the argument.

```scala
@GQLDirective(ProjectedName("journal_title"))
title: Field => Option[String]
```

**Comment by ghostdogpr** [comment]
Yeah, it works well with directives, it's actually much more flexible than Sangria since you can do whatever you want (needs a little more code but you can make a nice little helper for it).

Example: https://scastie.scala-lang.org/fBe67HONRbu6FjsqWHui2Q

```scala
case class Query(
  @GQLDirective(Directive("test", Map("projected_name" -> StringValue("journal_title"))))
  title: Field => String
)

val query = Query(field => 
                    field.directives
                      .find(_.name == "test")
                      .flatMap(_.arguments.get("projected_name"))
                      .collectFirst { case StringValue(name) => name }
                      .getOrElse(field.name))
```
