### ISSUE TITLE
Cyclic reference in code generation for RootQuery/RootMutation

### ISSUE THREAD

**Issue by MasseGuillaume** [ghostdogpr/caliban#786]
version: 0.9.5

I'm generating client code and the output gives circular references:

```
[error] /home/gui/automat/wp-graphql-woocommerce-scala/src/main/scala/client.scala:40749:20: illegal cyclic reference involving type RootQuery
[error]   type RootQuery = RootQuery
[error]                    ^
[error] /home/gui/automat/wp-graphql-woocommerce-scala/src/main/scala/client.scala:42184:23: illegal cyclic reference involving type RootMutation
[error]   type RootMutation = RootMutation
[error]                       ^
```

If I comment out those lines, the client compiles fine.

**Comment by ghostdogpr** [comment]
Can you provide a way to reproduce? In itself it's not a problem, see https://github.com/ghostdogpr/caliban/blob/master/client/src/main/scala/caliban/client/IntrospectionClient.scala for example.

**Comment by MasseGuillaume** [comment]
Here is the output schema for WooCommerce: https://gist.github.com/MasseGuillaume/07eca4918655bcb52454656a049c7841

I'm sorry I can't reduce it further right now.

**Comment by ghostdogpr** [comment]
Ah isn't it because you have an object named `RootQuery` which clashes with the one from Caliban?

**Comment by MasseGuillaume** [comment]
Yup this looks like it

**Comment by ghostdogpr** [comment]
We either need to rename these (but that'll be breaking) or add these names to the list of reserved keywords so that an alternate name will be given.
