### ISSUE TITLE
Code generation for missing types

### ISSUE THREAD

**Issue by MasseGuillaume** [ghostdogpr/caliban#788]
I have yet another problematic schema for code gen. I cannot share the schema here because it's a private API but the general idea is that there is an object with a field that references a Type that does not exist. My workaround is to make this type available somehow:

```scala
package my.generated.package

package object graphql {
  /*
    Workarround, xyz use a type that is not defined anywhere:
  */
  type MyMissingType = Any
}
```
Would it make sense to add a flag to generate those missing types?

**Comment by ghostdogpr** [comment]
So you mean that the GraphQL schema is not valid?

**Comment by MasseGuillaume** [comment]
Ah actually, I don't think the type is missing from the schema, here is what I can extract:

Usage:

```json
{
  "name": "customFields",
  "description": "This field would contain type data",
  "args": [],
  "type": {
    "kind": "INTERFACE",
    "name": "Type",
    "ofType": null
  },
  "isDeprecated": true,
  "deprecationReason": "Please use 'custom.customFieldsRaw'"
}
```

Definition:

```json
{
  "kind": "INTERFACE",
  "name": "Type",
  "description": null,
  "fields": [
    {
      "name": "typeRef",
      "description": null,
      "args": [],
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "OBJECT",
          "name": "Reference",
          "ofType": null
        }
      },
      "isDeprecated": false,
      "deprecationReason": null
    },
    {
      "name": "type",
      "description": null,
      "args": [],
      "type": {
        "kind": "OBJECT",
        "name": "TypeDefinition",
        "ofType": null
      },
      "isDeprecated": false,
      "deprecationReason": null
    }
  ],
  "inputFields": null,
  "interfaces": null,
  "enumValues": null,
  "possibleTypes": null
}
```

**Comment by ghostdogpr** [comment]
Do you pass the schema as a file or by URL?

**Comment by MasseGuillaume** [comment]
by URL

**Comment by ghostdogpr** [comment]
Maybe it has something to do with the fact that it's deprecated.

If you have time, I'd be interested to know if the type is returned by https://github.com/ghostdogpr/caliban/blob/d11a92b206129a6540feaaf7f1d8b7dbd68b7c9c/tools/src/main/scala/caliban/tools/IntrospectionClient.scala#L22

**Comment by ghostdogpr** [comment]
@MasseGuillaume did you figure it out?

**Comment by MasseGuillaume** [comment]
I will take a look now.

**Comment by MasseGuillaume** [comment]
I think there was a mistake in the schema and they fixed it. I cannot reproduce it.
