### ISSUE TITLE
Subscriptions don't work with zio.Runtime.default

### ISSUE THREAD

**Issue by agtArcher** [ghostdogpr/caliban#804]
I am working on simple examples with using of Caliban, Zio layers, and Lagom. 
Here is a subscription method to get Source from Caliban:
```
def subscriptions: ServiceCall[GraphQLRequest, Source[ResponseValue, NotUsed]] = ServiceCall { request =>
  val zioTask = for {
            interpreter <- GraphQLSchema.api.interpreter //val api: GraphQL[CounterService]
            result <- interpreter.executeRequest(request)
            stream <- {
              result.data match {
                case ResponseValue.ObjectValue(List((_, value: StreamValue))) => value.stream.toPublisher.map(Source.fromPublisher)
                case _ => UIO(Source.single(StringValue("Couldn't get stream")))
              }
            }
          } yield {
            stream
          }
}

val serviceLayer: ZLayer[Any, Throwable, CounterService] //the main zio layer
```
There are two ways to run this task: 1) provide layer and run via Runtime.default:
```
val providedZioTask = zioTask.provideLayer(serviceLayer)
Runtime.default.unsafeRunToFuture(providedZioTask)
```
 2) run via custom Runtime:
```
val customRuntime: Runtime.Managed[CounterService] = Runtime.unsafeFromLayer(serviceLayer)
customRuntime.unsafeRunToFuture(zioTask)
```
Queries and mutations work in both ways, but subscriptions work only in the second way (got stream only with using custom zio.Runtime)
(I hope I explain it good enough)

**Comment by ghostdogpr** [comment]
Can you describe how it doesn't work? What happens?

Also I noticed you seem to call `interpreter <- GraphQLSchema.api.interpreter` at each request, which is not the recommended way. You should create the interpreter only once and then reuse it for each request.
Similarly, I don't think you should `provide` the layer for each request, because it will recreate it every time.

See the example for Akka Http which I guess is similar to your case https://github.com/ghostdogpr/caliban/blob/86317130468ffc1a4727a1d1ed35375f00b6f84b/examples/src/main/scala/caliban/akkahttp/ExampleApp.scala#L27

**Comment by agtArcher** [comment]
Thanks for the advice with interpreter
I backtracked the issue and found that the source is always returned but somehow the subscriber doesn't add to the subscriber's list when I use layer providing.

Here is my subscribe layer implementation:
```
class EventSubscriber(updateEventsSubscribers: Ref[List[Queue[Counter]]]) extends Subscriber.Service {

  /**
   * Publishes a new default counter's update.
   *
   * @param counter the updated default counter to publish.
   * @return
   */
  override def publishUpdateEvents(counter: Counter): IO[Nothing, List[Boolean]] = updateEventsSubscribers.get.flatMap[Any, Nothing, List[Boolean]] {
    UIO.foreach(_) { queue =>
      queue
        .offer {
          counter
        }
        .onInterrupt(
          updateEventsSubscribers.update(_.filterNot(_ == queue))
        )
    }
  }

  /**
   * Streams updates of the default counter.
   *
   * @return the stream with updates.
   */
  override def showUpdateEvents: ZStream[Any, Nothing, Counter] = ZStream.unwrap {
    for {
      queue <- Queue.unbounded[Counter]
      _ <- updateEventsSubscribers.update(queue :: _)
    } yield ZStream.fromQueue(queue).ensuring(queue.shutdown)
  }
}

object EventSubscriber {

  /**
   * Provides the Subscriber layer.
   */
  val live: ULayer[Subscriber] = {
    ZLayer.fromEffect(Ref.make(List.empty[Queue[Counter]]).map(new EventSubscriber(_)))
  }
} 
```

The example for Akka Http uses custom runtime, which is working correctly, but I want to make this with usage of default zio runtime  which requires me to provide a service layer to run zio task

If it is still not clear what I mean, I will write when my example is in the public repository

**Comment by ghostdogpr** [comment]
I think you have no choice but to make a custom runtime. If you call provide for each request, a new service will be created each time and nothing will be shared between requests.

**Comment by agtArcher** [comment]
Got it. Thanks. I will write when my example is in the public repository in case I missed something
