### ISSUE TITLE
Validation Error when the same interface is used in multiple unions

### ISSUE THREAD

**Issue by MollardMichael** [ghostdogpr/caliban#826]
Hello here,

I'm trying to do something and I end up with

ValidationError Error: Type 'ForbiddenRejection' is defined multiple times (OBJECT in io....schema.Types.InitiateCreditTransfersPayload.ForbiddenRejection, OBJECT in io....schema.Types.RefundPayload.ForbiddenRejection).

This error happens when I create the interpreter `federate(partnerGql).interpreter` from a GraphQL generated with caliban-codegen-sbt.

The reason with this happens is that the generation generated two sealed trait with the same case class name.

A simplified version of the graphql schema looks like this:

```graphql
interface Rejection {
  message: String!
}

type ForbiddenRejection implements Rejection {
  message: String!
}

type Query {
  query(id: ID!): QueryPayload!
  query2(id: ID!): Query2Payload!
}

type QuerySuccessPayload {
  id: ID!
}

type Query2SuccessPayload {
  id: ID!
}

union QueryPayload = QuerySuccessPayload | ForbiddenRejection
union Query2Payload = Query2SuccessPayload | ForbiddenRejection
``` 

For now the only solution I have is to never do this.

Am I doing something wrong ?

**Comment by ghostdogpr** [comment]
Would you be able to post a simplified reproducer (ideally on scastie)? That'd help us!

**Comment by MollardMichael** [comment]
I'm sorry this is something that happened on new project I just joined and my first time writing code in scala. 
I think it's a bit too much for me to boostrap a projec.

I think the issue is mainly that 
- union are generated as sealed trait with case class (meaning that the case class with the same name will be generated by on my schema)
- - we are using the generated code as source for our App (so we can't edit the @Gql annotations to give it a different name (I'm not sure we want that because it might have an impact on the schema).

**Comment by ghostdogpr** [comment]
Oh, I see. So ideally it should generate such case classes outside of the companion objects and make them extend multiple sealed traits. Can you verify that it produces the expected schema if you do it this way (by modifying the generated code)?

**Comment by AlixBa** [comment]
I've tried something based on your comment, @ghostdogpr . I'll test it ASAP on a `.interpreter`
