### ISSUE TITLE
GraphQL federation gateway based on Caliban

### ISSUE THREAD

**Issue by zvuki** [ghostdogpr/caliban#828]
Is it possible/supported?

**Comment by ghostdogpr** [comment]
It's not supported. Technically I guess it's possible but would require a lot of efforts. @paulpdaniels thoughts?

**Comment by paulpdaniels** [comment]
Yeah most definitely would require a lot of effort. There are a also different stages of federation. If you just want to be able to stitch together several graphs you could merge them using the `|+|` operator (though admittedly we don't have this for remote schemas yet, but there is a contributor working on it). If you need an actual gateway the big piece that would be needed for that is the `QueryPlanner` which figures out which parts of a query need to go to which graph and is able to flatten out and reconstruct a completed graph. If you are also planning to take advantage of managed federation then it also needs to have support for introspecting the "super graph" and polling for updates.

I have started playing around with this locally on my own, but it's mostly for academic purposes so I haven't had the time to actually devote to making it work.

**Comment by ghostdogpr** [comment]
You might be interested in #896 that was just merged.

**Comment by ghostdogpr** [comment]
I'm going to close this because I think this is outside the scope of caliban as a library. I think that if anyone is motivated to build this, it can be another library built on top of caliban (and we can point to it from the federation docs). Happy to merge any contribution that adds missing bits required to make it work.
