### ISSUE TITLE
Input enums are inconsistently suffixed with "Input"

### ISSUE THREAD

**Issue by rtimush** [ghostdogpr/caliban#83]
When enum is used as an input type, the query requires values equal to the names of the case objects (which makes sense), but in the schema returned by the introspection query, all values are suffixed with `Input`.

With the following definition:
```scala
sealed trait Numbers
case object One extends Number
case object Two extends Number
```

The query works:
```graphql
query {
  foo(input: One) { ... } 
}
```

But the schema says:
```graphql
foo(input: Number!): FooResult

enum Number {
  OneInput
  TwoInput
}
```

The expected schema is either
```graphql
enum Number {
  One
  Two
}
```
or
```graphql
enum NumberInput {
  One
  Two
}
```
depending on #80.

**Comment by ghostdogpr** [comment]
Good catch! It doesn't happen when the enum is used both as an input and as an output (like my type `Origin`) but it indeed happens when you use it only as input.
