### ISSUE TITLE
Spray-json backend for AkkaHttpAdapter

### ISSUE THREAD

**Issue by mjarosie** [ghostdogpr/caliban#841]
AkkaHttpAdapter [requires a pluggable JSON backend](https://github.com/ghostdogpr/caliban/blob/660beea/adapters/akka-http/src/main/scala/caliban/AkkaHttpAdapter.scala#L24). As far as I understand, [the only available JSON backends are for circe and play](https://github.com/ghostdogpr/caliban/tree/660beeae538768d817a73cb4535e0e3bd1a8cb82/adapters/akka-http/src/main/scala/caliban/interop). This feature request is for implementing JSON backend for [spray-json](https://github.com/spray/spray-json). Unless it's already available and I am searching in a wrong place? I'm new to Caliban and Scala in general. Would this kind of backend be hard to implement?

**Comment by ghostdogpr** [comment]
You are right, it is not currently implemented. You already identified the place where the code is for circe and play. As you can see, it's not very complex if you are familiar with the JSON library (just converting a few types from/to JSON).

**Comment by ghostdogpr** [comment]
This will be covered by https://github.com/ghostdogpr/caliban/pull/1125 (any json backend will be usable).
