### ISSUE TITLE
Compiler never completes with complex schema. 

### ISSUE THREAD

**Issue by tmilner** [ghostdogpr/caliban#852]
I've recently started investigating Caliban and setup a test project using an example schema file which has types that are self recursive. 

For example:
```graphql
input BooleanFilter {
  isNull: Boolean
  is: Boolean
  not: BooleanFilter
  or: [BooleanFilter!]
  and: [BooleanFilter!]
}
```

As a side note - I started off using code gen, but found that there file generated would not compile. It seemed to create the types in the case object of every union it existed in. So if a type was in 2 unions it would be defined twice. It also seemed to ignore interfaces which led to other issues. But that is not the issue I am here to report, I ended up re-writing a custom version of the SchemaWriter which did not create multiple copies of the case classes and also correctly handled Interfaces. This means sub types are not always in the companion object of the sealed trait, which I know can cause issues with Magnolia. But I think its unrelated. 

The main issue is that now I have this complex schema generated into what appears to be valid Scala code, but the compiler does not manage to complete the task of deriving the Schema types needed. I have increased the memory up to 8GB and it still runs out of memory after about 15mins of trying to compile.  I have tried adding to the custom schema writer so that it defines the implicits for each type in the generated code (as per the warning here - https://ghostdogpr.github.io/caliban/docs/schema.html), but that does not help. I have tried defining custom schema types (https://ghostdogpr.github.io/caliban/docs/schema.html#building-schemas-by-hand) for each type automatically as part of code generation, but even with them it fails to complete compilation (OOM error).

From my session trying to debug the compiler I could clearly see it was getting stuck in the macros, but I am not sure how to narrow it down further. 

Also I do not have a minimal example yet, but I am working to produce one. 

Thanks, 
Tom

**Comment by ghostdogpr** [comment]
Are you sure the implicit schemas you define are in scope and actually used? In the scenario where you would define everything manually (including the root schemas), Magnolia macros wouldn't be involved at all. I'd try reaching that point (even without a real implementation, using `???`) so that it compiles and then removing them step by step to see which ones are actually necessary.

Otherwise as you said, if you can reproduce it on a smaller scale I can take a look. 

Feel free to drop on the discord as well where you might get other feedbacks/ideas than mine.

**Comment by tmilner** [comment]
Hmm I think I was going down the wrong path. I tried to recreate it and I cant. 

Currently I have a large schema that compiles, but as soon as I either try to create a server (so trigger derivation of types) or add any kind of implicit (`Schema.gen[X]`, `Schema.genMacro[X].schema` or using `obj`) the build his an OOM error.

Still digging into whats happening, but I had a minimal example of nested types that worked so I dont think its that. Maybe its just the sheer number of case classes I have.

**Comment by tmilner** [comment]
I've had no luck at all. Bringing in any kind of implicit makes it immediately stop compiling and I am not sure I can dedicate any more time to debugging. If anyone thinks they know why a large schema would cause this please let me know. But for now I am going to close this issue. Thanks.
