### ISSUE TITLE
Incorrect error returned when using default function Schema and input argument contains field named "value"

### ISSUE THREAD

**Issue by mszczygiel** [ghostdogpr/caliban#879]
I've prepared testcase that covers this issue here: https://github.com/mszczygiel/caliban/commit/548b54df20da354a6e92749d78e38f5f6e8ad21a

Returned error is `Can't build an Int from input "value"` which is incorrect, and this is due to arbitrary name chosen in https://github.com/ghostdogpr/caliban/blob/master/core/src/main/scala/caliban/schema/Schema.scala#L360

Workaround is to provide my own `functionSchema`, but possibly proper error handling could be built into caliban itself? Maybe `"value"` could be provided from some `ArbitraryName` implicit, or even be optional and fail in case it's not provided and argument is not wrapped in a case class.

**Comment by ghostdogpr** [comment]
I think it can be fixed more simply by applying the fallback logic only if we are in the case with no wrapping case class (the same condition used in `toType` a few lines above). So you want to try? You already have a nice test 😄 If not I can do it.

**Comment by mszczygiel** [comment]
Right, that would work, too. I'll try to fix it in a few day then. Thanks for the response :)
