### ISSUE TITLE
Caliban Client Codegen: Not using ID type in method signature for top-level queries

### ISSUE THREAD

**Issue by hollinwilkins** [ghostdogpr/caliban#905]
Consider the following GraphQL schema:

```graphql
type Query {
    testQuery(testId: ID!): TestType
}

type TestType {
    name: String
}
```

Running caliban codegen on it will result in this Scala:

```scala
import caliban.client.FieldBuilder._
import caliban.client.SelectionBuilder._
import caliban.client._
import caliban.client.Operations._

object GQLTest {

  type TestType

  object TestType {
    def name: SelectionBuilder[TestType, Option[String]] = Field("name", OptionOf(Scalar()))
  }

  type Query = RootQuery

  object Query {

    def testQuery[A](testId: String)(innerSelection: SelectionBuilder[TestType, A]): SelectionBuilder[RootQuery, Option[A]] =
      Field("testQuery", OptionOf(Obj(innerSelection)), arguments = List(Argument("testId", testId)))
  }

}
```

The problem is that the type of `testId` in the method signature to `testQuery` is a `String`. This fails typechecking when making the call to the server. The server is expecting `testId` to be an `ID`.

**Comment by hollinwilkins** [comment]
I should also note, this is when setting `useVariables = true` to create the request.

**Comment by ghostdogpr** [comment]
You're right. The problem with using `ArgEncoder` on the argument type is that we lose the information on the graphql type. Maybe the codegen should provide the graphql type information when it creates `Argument`. Will think about this and see if I can make it work.

**Comment by ghostdogpr** [comment]
Tentative fix: https://github.com/ghostdogpr/caliban/pull/906
