### ISSUE TITLE
Update AuthExampleApp

### ISSUE THREAD

**Issue by jdepassos-mdsol** [ghostdogpr/caliban#908]
Looking at the example AuthExampleApp, the context wrapper gives us access to the http headers, and via its own query resolver we can pull those values, but is it possible to pass http headers to Query members instead?

Can we update AuthExampleApp to show this

eg Query definition
```scala
final case class Query(
    study: (Map[String, String], Field) =>
```

**Comment by ghostdogpr** [comment]
No it is not possible to do it that way. The supported way is to provide it via the ZIO environment like in the examples.
