### ISSUE TITLE
Error response incorrect for an invalid field input

### ISSUE THREAD

**Issue by ali-at-github** [ghostdogpr/caliban#911]
Hi, 
I have a mutation which accepts a BigDecimal input to a field. If I supply an invalid value for it, I get the mutation name in the `data` object of the response. e.g:

`mutation{
 createBook(
  name:”Book1”,
  description:"test",
  Price:”2”
) {
  id
}
}`

Response i get is:

`{
  "data": {
    "createBook”: null
  },
  "errors": [
    {
      "message": "An internal error occured",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createBook”
      ],
      "extensions": {
        "code": "internal.unexpected.error",
        "message": "Can't build a BigDecimal from input \"2\""
      }
    }
  ]
}`

Notice the `createBook: null` in the `data` object. I expect it to return `data: null` instead.

**Comment by ghostdogpr** [comment]
@ali-at-github I believe it is working as expected. I added 2 tests in [this commit](https://github.com/ghostdogpr/caliban/commit/2e4d6ec571ca15a1b66f6e4f8a0ef0c94c80513d). The first one fails parsing an argument when the field is optional (`Task`), the second one when the field is not optional (`UIO`). The result contains the field for the first one and is just `null` for the second one.

Closing this, but if you think there is still a problem, please provide some code to reproduce.
