### ISSUE TITLE
Client Codegen doesn't handle the name properly with play projects.

### ISSUE THREAD

**Issue by paulpdaniels** [ghostdogpr/caliban#950]
Currently the client codegen uses a regex based system to extract the name of the client from the file name (or falls back to `Client` if it can't find it). The regex however relies on the presence of `/scala` in the path name which breaks with `play` (and any custom directory structures).

Work around is to make your client projects part of a separate module if using play (one that follows the correct directory structure). But given that play is pretty widely used it seems like we could support it out of the box since it is just about adding a `|play` to the regex.

Issue illustrated here: https://scastie.scala-lang.org/ucJFJg63QHqsgHHDl7AibQ

**Comment by ghostdogpr** [comment]
Sure, let's add `|play` 👍
