### ISSUE TITLE
SchemaLoader skips @deprecated directive

### ISSUE THREAD

**Issue by v-tec2706** [ghostdogpr/caliban#994]
Looks like `SchemaLoader.fromCaliban(...)` does not include deprecated directive to `FieldDefinition` while `SchemaLoader.fromString(...)` does, that triggers `changes` in `compareAllTypes(...)` when calling `SchemaComparison.compare(...)` method.

**Comment by ghostdogpr** [comment]
@v-tec2706 hmm, it doesn't seem to be the case. There is a test case `compare Caliban schema with string schema` and I tried adding `@GQLDeprecated("...")` to a field, the test is still passing. Woud you be able to provide a reproducer?

**Comment by v-tec2706** [comment]
So, when I modify that test: 
``` scala
testM("compare Caliban schema with string schema") {
  val schema: String =
    """
    type Hero {
      name(pad: Int!): String!
      nick: String! @deprecated(reason: "some reason")
      bday: Int
    }
    
    type Query {
      hero: Hero!
    }
      |""".stripMargin

  case class NameArgs(pad: Int)
  case class Hero(name: NameArgs => String, @GQLDeprecated("some reason") nick: String, bday: Option[Int])
  case class Query(hero: Hero)

  val api = graphQL(RootResolver(Query(Hero(_ => "name", "nick", None))))

  assertM(for {
    diff <- SchemaComparison.compare(SchemaLoader.fromString(schema), SchemaLoader.fromCaliban(api))
  } yield diff)(equalTo(Nil))
}
```
it fails with: 
```
[info] - SchemaComparisonSpec
[info]   - compare Caliban schema with string schema
[info]     List(Directive 'deprecated' was deleted from field 'nick' of type 'Hero'.) did not satisfy equalTo(List())
```

**Comment by ghostdogpr** [comment]
@v-tec2706 you're right, I tested wrongly. Opened https://github.com/ghostdogpr/caliban/pull/1006 to fix it.
